### ISSUE TITLE
Get rid of Gov.uk Branding in UI

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#1]
**What?**
- Colours are pulled in via an NPM from a deprecated UK repo
- We need to update the colours to CDS agreeable ones (Use the colour pallette from digital.canada.ca, Black, white, Dark grey, yellow highlights) As a placer holder until we get design help
- Replace Gov.uk UI logos with GoC logo

**Why?**
- Doesn't look very good and creates some design faults
- Should be considered with the Font change in https://github.com/cds-snc/CANotifier/issues/24

**Comment by willeybryan** [comment]
@willeybryan  First step, confirm Notifier name

**Comment by timarney** [comment]
Going to close this - we can adjust further under fresh tickets for any specific updates.
