### ISSUE TITLE
Develop key message(s) and cheatsheet for talking about Notify

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#1000]
Clear and cohesive messaging that highlights the benefits of the product to prospective users.

--- Condense content into ONE sentence or tweet with the key takeaway point we want the audience to remember

Messages that builds trust and credibility:
- what it is
- why it matters
- trustworthy
- evidence based

Follow-up: reorganize content around key message

[Marketing plan](https://docs.google.com/document/d/1E7bPyCMLbKBGQ_7iSIGhkhyhM5HvxHVbizquq5wND7A/edit#heading=h.knjlmeuwwf4q)

**Comment by ClementineHahn** [comment]
Ioana to start on this today to ensure passing to Anik before she goes on vacations and there is continuity of work on this

**Comment by mcman12** [comment]
possibility that this gets done by end of day today.
