### ISSUE TITLE
Investigate "Change Password" issue

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-api#1002]
From @sboisvert on Slack:

> I'm on https://notification.alpha.canada.ca/services/SERVICE ID/smtp and it says "Generate a new password if you forgot it." But I can't seem to generate one.

Response from @maxneuvians 
> You would need to remove the SMTP integration and create a new one

We should either make it clear that to change the password you need to recreate the integration, or actually allow the users to change the password for the existing integration.

**Done When**
- SMTP Relay page has Port 587 listed and says 'delete and recreate relay to get a new password.'

**After you create:** 
THIS RELAY HAS BEEN DELETED
![image](https://user-images.githubusercontent.com/46505127/86024962-a981b000-b9fb-11ea-85e0-2c4bb84df3ed.png)

**On successive visits**
THIS RELAY HAS BEEN DELETED
![image](https://user-images.githubusercontent.com/46505127/86024778-6aebf580-b9fb-11ea-9a13-892c79fd322d.png)

**Comment by willeybryan** [comment]
@sastels This is only exposed to platform admins. 
The same page also displays The port as 465 when it's 587.

We need to do some touch ups on that page to change the text.
