### ISSUE TITLE
Create policy & procedure docs from STRM controls

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#1004]
**Done When**
- Access control policy & procedure is written
- Public content policy & procedure is written
- Audit policy & procedure is written
- Configuration management policy & procedure is written
- Contingency plan policy & procedure is written
- Authentication policy & procedure is written
- Incident response policy & procedure is written
- Risk Management policy & procedure is written
- Secure software development Lifecycle and acquisition policy & procedure is written
- System Monitoring policy & procedure is written

**Comment by ClementineHahn** [comment]
AS a result of review of previous cards done by @sastels and @brdunfield , @willeybryan will update docs that will reflect new security processes suggested with proof required. 
End of this week work should be done for first draft 🤞

**Comment by ClementineHahn** [comment]
Incident response policy & procedure is in progress, 
Looking to start Risk Management policy & procedure as soon as possible (today or tomorrow)

**Comment by mcman12** [comment]
3 left, working on it. still on track for sprint end

**Comment by willeybryan** [comment]
[Access control policy & procedure](https://docs.google.com/document/d/1DB4pUvki-UHIAE2aF0VYb6aLkFEiM-iT79jYDZsmOOk/edit) is written
[Public content policy & procedure](https://docs.google.com/document/d/1zfdZkHyntK2YWJdXh5BA8jLO5yK-dMBNYRtCdeoV6JA/edit) is written
[Audit policy & procedure](https://docs.google.com/document/d/1tuLJjbNqOooCUtYmgHwxUyeFT7XZBYc8w38btdWaQhU/edit) is written
[Configuration management policy & procedure](https://docs.google.com/document/d/12u6sLfI8BMH3uJD1ThNOeOaXLQjWU8m-AlpOJft79SM/edit) is written
[Contingency plan policy & procedure](https://docs.google.com/document/d/1VWry7kp2kiiaN1dC_GI3oEI8Nze4zJV1NnW84RaoKOs/edit) is written
[Authentication policy & procedure](https://docs.google.com/document/d/1d7mxFWzRaXnMUEJk1HvtyIY0Em_I_nRNiV6wr2i6G-U/edit) is written
[Incident response policy & procedure](https://docs.google.com/document/d/1qXNiHdFy95CNnmdtITIEb_rYgJs1i_pwTbQZkAJnHyc/edit) is written
[Risk Management policy & procedure](https://docs.google.com/document/d/1JXI30uF7PpzLUIM5gUCBVHPtx5B9MqOsfhaiCVakxio/edit) is written
[Secure software development Lifecycle and acquisition policy & procedure](https://docs.google.com/document/d/1eB6G4AsIqHmw6JQPuy8eivs7DBKuqw39ZPbcNO4ZIuI/edit) is written
[System Monitoring policy & procedure](https://docs.google.com/document/d/1dqS264MuZJzgg1i1N8J0VGX3d0pfnI4RgpVk0JOlpAU/edit) is written

[Notify code of conduct](https://docs.google.com/document/d/13M4A-iiQA5aXUGiAFJkUVdMGUZrfH-5H8BvNoYk2e4o/edit?usp=sharing)
