### ISSUE TITLE
Write and share research plan for next prioritized activity

### ISSUE THREAD

**Issue by AnneMarieMulumba** [cds-snc/notification-api#1006]
**Done when**
- New Research plan is written and shared with team for comments and suggestions
- Possible activities are listed, commented with proposed order and with assessment on possible time and capacities needed to run

https://docs.google.com/document/d/1FblS_fcGn0LRjyctfZ3TdThHgMUmN0eVcj7Sd-e2Isc/edit?usp=sharing

**Comment by ClementineHahn** [comment]
new priorities directions drafted and shared with the team, discussed with design team . 
Start picking activites to propose prioritisation.

**Comment by ClementineHahn** [comment]
By end of sprint , reprioriser les nouvelles directions

**Comment by ClementineHahn** [comment]
Martha started her own new doc to synthetise possible directions and activities, to be shared with team soon.
