### ISSUE TITLE
Investigate app 500 errors with '.json' in the URL

### ISSUE THREAD

**Issue by brdunfield** [cds-snc/notification-api#1009]
We've had a couple ops alerts recently where URLs contain '.json' at the end and a 500 is thrown.

New Relic logs: https://rpm.newrelic.com/accounts/2691974/applications/283469061/filterable_errors#/show/6e93934b-bafc-11ea-89e1-0242ac11000b_0_3941/stack_trace?top_facet=transactionUiName&primary_facet=error.class&barchart=barchart

A brief check in the admin code shows support for `.json` in the code in a few routes. My hunch is that this is for data download, however more investigation is needed.

It also seems to be this particular route: `/services/{service-id}/notification/{notification-id}.json` which has thrown the errors so far.

**Comment by sastels** [comment]
Works with a notification I just sent, might be only failing sporadically 😞

**Comment by brdunfield** [comment]
Maybe have a dig through the logs and filter for '.json' to see if you can find some commonalities?

**Comment by sastels** [comment]
The admin is doing a request to api here
https://github.com/cds-snc/notification-admin/blob/master/app/notify_client/notification_api_client.py#L63
and getting a 503, which according to
https://airbrake.io/blog/http-errors/503-service-unavailable
means the server (api) is up but temporarily unavailable. Will investigate further...

**Comment by sastels** [comment]
error admin is reporting is
```
"API unknown failed with status 503 message Request failed"
```

**Comment by sastels** [comment]
For some reason the api pods are rebooting before / during the admin request
```
fields kubernetes.pod_name, @timestamp, log
| filter (@timestamp >= 1595348002000 and @timestamp <= 1595349315000)
| filter ((@logStream like /api-/ and (log like /Starting/ or log like /Stopping/) ) or (@logStream like /admin-/ and @message like / 503 /))
| sort @timestamp asc
```
![image](https://user-images.githubusercontent.com/8228248/88204251-03e7e800-cc19-11ea-972c-bb59ff359ce2.png)

**Comment by brdunfield** [comment]
API pods rebooting.. That sounds similar to the other issue we've been trouble shooting. However I feel like we noticed this .json issue well before the alarms started going off 2 weeks ago.

Is it possible that these request failures are just happening to happen when a pod is cycling? It seems odd that so many of them happen to be '.json' requests.. 🤔

**Comment by sastels** [comment]
🤷 these are good points. Also, we still need to verify that pods are always rebooting when we have this json error and that it's not just a coincidence. But a 503 "I'm not ready" error is probably what you'd expect from a pod that is in the middle of starting. If the pod rebooting is the cause, then
- why are the pods rebooting (is it PP / something else / something benign?)
- should admin handle the situation differently? rather that pass along a 503 error, maybe send back json with a "try again later" message?

**Comment by willeybryan** [comment]
This is probably caused by the pods crashing which is part of a bigger issue.
