### ISSUE TITLE
Content changes to terms of use page

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-api#101]
**Page:** https://notification.cdssandbox.xyz/features/terms

Please replace the current text with the text in the following google doc: https://docs.google.com/document/d/1VPChhp94EOSCMcKBW67Tv2PJ5mKpR-NzCfBtAuuC1co/edit#

**Special instructions:** in the replacement text, in the bullet that reads "not send unsolicited messages . . " there is a reference to a page of the UK gov't service manual. The link for that page is given earlier in the terms of use. There are headings on that page for transactional messages and subscription messages. Can we please hyperlink to those where the bullet says "Please follow the transaction and subscription criteria in the GOV.UK Service Manual"?
Thanks!

**Comment by YedidaZalik** [comment]
I think that link can stay. The support page has been revised in and I think @willeybryan wants users to contact him for support while we test, but Bryan please advise if I am wrong.

**Comment by willeybryan** [comment]
I want all the contact us stuff to go to CDSPlatform.PlateformesSNC@tbs-sct.gc.ca
So that we can manage that mailbox later

**Comment by brdunfield** [comment]
Trying to actually use the contact us form (both locally and live) gives a zendesk 401 error. @timarney 

I will still merge the terms content PR as the error already exists in live and doesn't have to do with content changes.

**Comment by timarney** [comment]
This one covers the ZenDesk fix.
https://github.com/cds-snc/notification-api/issues/60
Also
https://github.com/cds-snc/notification-api/issues/68

**To clarify those:**
I was thinking that we can swap out the call to the ZenDesk api endpoint to a new one we create that basically fires an email (via a template) to us with the details from the form submission.  

Are we all on the same page?

**Comment by willeybryan** [comment]
@timarney Yeah that works for me 100%

If this actually gets big we can connect it back to a ticketing system later.
