### ISSUE TITLE
Content change to Home Page (0.0)

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-api#102]
**Page:** https://notification.cdssandbox.xyz/

- Please delete the word "now" in the line "Try Notification . . ."
- In Add text message template image (https://notification.cdssandbox.xyz/static/images/product/01-templates.svg?f1f89c55b8a16fc6e5c2342d3b0492d1), please change "Notify" to "Notification"
- Replace "Integrate . . . " with " Integrate Notification with your web application or back office system"

**Note:**
If not possible to change Notify to Notification as it is SVG and we don't have that font, I have created a replacement image here.

![image](https://user-images.githubusercontent.com/46505127/61314761-55ba8e80-a7cb-11e9-99c3-e60546d295a2.png)

**Comment by willeybryan** [comment]
Hey, I approved this change and that is my bad but it says on the page: 'Integrate Notification with your web application or back off system.' instead of '...back office system.'

As for the image I am going to see about getting us some .SVG files.

**Comment by timarney** [comment]
"back office system" typo is merged.

**Comment by YedidaZalik** [comment]
@timarney This is just a little thing but when "letter" was removed, an extra comma and space was left in the sentence " You don’t need any technical knowledge to create email, or text message templates."
Can you please remove the comma after "email" so it reads
"You don’t need any technical knowledge to create email or text message templates."
Thanks!

**Comment by timarney** [comment]
@YedidaZalik there's a pull request in now for that typo.

**Comment by YedidaZalik** [comment]
Thank you!

**Comment by timarney** [comment]
Closing this.

@ todo we'll fix the images once we have them or some software to create them.

> As for the image I am going to see about getting us some .SVG files.

**Comment by willeybryan** [comment]
I made this for Eman to help us out, I am getting french translated for the images https://github.com/cds-snc/notification-api/issues/134
