### ISSUE TITLE
Remove "Support" page (EN-only)

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#1021]
https://notification.alpha.canada.ca/support

Remove (or update and translate) new-found "Support" page (EN-only)

We link to this page in the "Confirm new email template" -- removing this link means we may need to adjust API calls.

<img width="479" alt="Screen Shot 2020-07-09 at 8 07 42 AM" src="https://user-images.githubusercontent.com/38330843/87038226-6f629c00-c1bb-11ea-98d5-b0cc2acd82a6.png">

<img width="805" alt="Screen Shot 2020-07-09 at 8 07 26 AM" src="https://user-images.githubusercontent.com/38330843/87038239-74275000-c1bb-11ea-971d-aff94f12fc2f.png">

**Comment by brdunfield** [comment]
https://github.com/cds-snc/notification-api/pull/1023
points the templates to the correct contact us URL. Not sure if that closes this card?

**Comment by brdunfield** [comment]
We can take the page / route out entirely as well
