### ISSUE TITLE
Rework on call for Notify

### ISSUE THREAD

**Issue by ClementineHahn** [cds-snc/notification-api#1022]
The current ON Call schedule for Notify is tracked here https://docs.google.com/document/d/1b5SYSbFiW-T-tFooX5GNPmM9wVXn4rLB2lbrBEU-Eew/edit#

It is also captured in Ops Genie . 

Early July, a few people assigned on On call for Notify demonstrated they were not confident to do their shift as planned. 
Two main factors : 
- in summer context last minute vacations scheduling
-  intense workload of people already working on Exposure Notification and also in on call for Notify becomes 

**Done when** 
A new calendar for ON call  Notify is done, approved by all people concerned in doc AND set up in Ops Genie

**Comment by ClementineHahn** [comment]
New schedule proposed that matches all availabilities . Action left to do is implement in Opsgenie Thanks to @willeybryan 

- Wed July 8th 9am/Wed July 15th 9am     "Product: @Ross Ferguson / Development: @Tim Arney "Notify only
- Wed July 15th 9am/Wed July 22nd 9am  "Product: @mario  / Development: @Stéphane " for Notify only
- Wed July 22nd 9am/Wed July 29th 9am  "Product: @Bryan Willey [he/him] / Development: @Steve Astels " for Notify only
- Wed July 29th 9am/Wed Aug 5th 9am     "Product:  @John O'Brien  / Development: @Max "  for Notify & EN
- Wed Aug 5th 9am/Wed Aug 12th 9am.     "Product: @Stephen Y (he/il)  / Development: @Tim Arney " for Notify & EN
- Wed Aug 12th 9am/Wed Aug19th 9am.     "Product: @mario / Development: @Stéphane " for Notify only
- Wed Aug 19th 9am/Wed Aug 26th 9am.    "Product: @Bryan Willey [he/him]  / Development: @Steve Astels " for Notify only

**Comment by willeybryan** [comment]
@ClementineHahn I can for all entries except for Ross and S-Yates. Neither are in the ops genie system.

**Comment by ClementineHahn** [comment]
All Entries in ops genie possible are done. Cards considered done
