### ISSUE TITLE
Alternate sending domains not logging to dashboard

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#1026]
**Steps to Reproduce**
- in platform admin settings Change the sending domain on a service to another working one other than default. There is only 2 working domains so I set one up here on my testing one https://notification.alpha.canada.ca/services/c31680dd-8d0d-4e9f-be06-0d2f201aeaf8/notifications/email?status=sending%2Cdelivered%2Cfailed
- Send an email

**Expected**
- Email appears in inbox, dashboard updates to sent, then delivered

**Actual**
- Stays on sending forever/fails after 24 hours to technical failure

**Comment by brdunfield** [comment]
Is this possibly a callback issue, similar to how delivery status does not work on a local developer setup?
