### ISSUE TITLE
Fix test API key bulk sends bringing down API pods

### ISSUE THREAD

**Issue by brdunfield** [cds-snc/notification-api#1027]
For some reason, bulk sends using a test API key cause our API pods to get overloaded and die.

This might have to do with the fact that the SES callback is mocked in a test key send, and happens a lot quicker than it would in reality?

**Done when:**
API pods are no longer killed by a test key bulk send

**Comment by willeybryan** [comment]
After discussion the proposed solution is to batch the API test keys into small enough groups not to take down the pods.

**Comment by mcman12** [comment]
pushing to sprint 28 to find a more robust answer

**Comment by willeybryan** [comment]
Multiple things cause pod crashes, working on it as a bigger issue.
