### ISSUE TITLE
Content changes to Create an Account Page (1.0)

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-api#103]
**Page:** https://notification.cdssandbox.xyz/register

- Please change "Must be from a government organisation" to "Must be a federal government email address"
~~- Mobile number: Needs to be seamless for the user. Please ensure it is configured so that the the phone number works if a person puts a 1 at the start or not.~~

**Comment by timarney** [comment]
> Please ensure it is configured so that the the phone number works if a person puts a 1 at the start or not.

@willeybryan let's `track` + `test` separately.

**Comment by willeybryan** [comment]
I will spin it off to its own ticket in the backlog

**Comment by timarney** [comment]
Merged the content updates.
