### ISSUE TITLE
Ideate on possible actions to improve the current service experience and address gaps or barriers

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#1030]
[Tracking Marketing Actions
](https://docs.google.com/spreadsheets/d/1JBoyLVQGaHvZwnsVT322CaG5GronwKrU5am4MedFHnM/edit#gid=0) extracted from [Product Lifecycle](https://app.mural.co/t/cppd0120/m/cppd0120/1593542890988/aaaa6f4b991175d41f835e60940f53809c405e0a)

Update [Marketing Strategy](https://docs.google.com/document/d/1E7bPyCMLbKBGQ_7iSIGhkhyhM5HvxHVbizquq5wND7A/edit)

HMW match the needs of (potential) clients with what we offer?

- go through product lifecycle
- compare what they expect/want with what we offer
- come up with ideas for what we can do more of/better or what we can remove/do less of

**Comment by ClementineHahn** [comment]
Series of chat happened to gather insights on pertinent place in GC to talk to potential users. As a results content was added on Maps.

**Comment by anikbrazeau** [comment]
Ioana started preparing this doc with marketing strategy actions: https://docs.google.com/spreadsheets/d/1JBoyLVQGaHvZwnsVT322CaG5GronwKrU5am4MedFHnM/edit#gid=0
