### ISSUE TITLE
SPRINT 27 - 20/07 to 31/07- 1) Prep Domain Migration + ATO tasks so that we can launch beta 2) bilingual branding available so we're OLA and FIP compliant.  - 3)research and marketing aligned on Beta roadmap

### ISSUE THREAD

**Issue by ClementineHahn** [cds-snc/notification-api#1032]
By the end of the sprint we aim to have : 

- everything technically prepared and ready that we can to prepare to move GC Notify to it's new domain so that we can launch beta. Prep Domain Migration + ATO tasks ( Threat list, SRTM, PIA check-list, Finish collect evidence )

- a bilingual branding available so our users can email in both languages in an OLA and FIP complaint way so that we can be inclusive of all users.

- research and marketing aligned on Beta roadmap for its first several sprints so that we can set up other goals for success.

**Comment by willeybryan** [comment]
By the end of the sprint we aim to have everything ready that we can to prepare to move GC Notify to it's new domain and launch beta. (Technical, Marketing plan, Recipients research.)

By the end of the sprint we aim to to have a bilingual branding available so our users can email in both languages in an OLA and FIP complaint way.

By the end of the sprint we aim to have a decided and aligned roadmap for the first couple sprints of Beta.
