### ISSUE TITLE
Define how we will measure impact on recipients: user metrics

### ISSUE THREAD

**Issue by AnneMarieMulumba** [cds-snc/notification-api#1033]
Use research insights from interviews to inform how we will measure success and progress of GC Notify as a product for recipients.

**Done when:**
- 3 user metrics are defined by the team for Beta

https://docs.google.com/document/d/1UEb_0jM7DgQAzy26WEKG8oh6zkMl8P_WAamBOnYUPyk/edit?usp=sharing

**Comment by willeybryan** [comment]
V1 done
https://docs.google.com/spreadsheets/d/15qLMzSGPGSwr9AJJDjJ6wQr8Egk7CBebeFzHdScN0PI/edit#gid=0
