### ISSUE TITLE
Content change to Check your phone (1.0.1)

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-api#104]
**Page:** Unavailable right now as SMS is disabled (Maybe https://notification.cdssandbox.xyz/registration-continue) 

- Change "Text message code" to "Please enter security code"

**As seen on page:**
![image](https://user-images.githubusercontent.com/46505127/61316213-7cc68f80-a7ce-11e9-96fb-fdbffccf1f24.png)

**Comment by timarney** [comment]
Note: https://notification.cdssandbox.xyz/two-factor
