### ISSUE TITLE
Translate french strings from notification-utils

### ISSUE THREAD

**Issue by brdunfield** [cds-snc/notification-api#1041]
**Translations ready to implement:**
Old FR: "Not a valid international number"
New EN: "Not a valid phone number"
New FR: "Numéro de téléphone non valide"

EN: "Must be a valid phone number"
FR: "Doit être un numéro de téléphone valide"

EN: "Not enough digits"
FR: "Pas assez de chiffres"

EN: "Not a valid country prefix"
FR: "Entrer un préfixe de pays valide"

**Have translations in admin but are not translated in utils:**
"Not a valid email address"

**Needs translation:**
"Not a valid local number"

**Comment by brdunfield** [comment]
It turns out there is a way to access these messages from the admin and translate them. Changing from M to S

**Comment by anikbrazeau** [comment]
EN: "Not a valid email address"
FR: "Entrer une adresse courriel valide"

EN: "Not a valid local number"
FR:  "Entrer un numéro de téléphone valide"
