### ISSUE TITLE
Get Nova Scotia a dedicated NS phone number?

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#1046]
**Problem**
When sending SMS to Recipients they are quick to disregard the message it if it comes from an unfamiliar area code they don't recognize.

**Story**
When confirming appointments, NovaScotia wants a dedicated phone they can advertise online, so people know to expect it. 

**Done when?**
- A dedicated Phone number from Amazon we can assign to NovaScotia services in the Notify UI, honestly any will do

**Stretch Goals**
- Something with a Nova Scotia Area code

**Comment by brdunfield** [comment]
Based on the knowledge Steve M. gathered when originally implementing PinPoint, there are a couple things to note here:
We can't actually assign a dedicated number to NS. Any number we assign them might and probably will be randomly selected by other services using SNS from time to time.

See: https://docs.google.com/document/d/1Iu4tzJIVQ3h6dVAZlqJrhLDiF1bGRPvsmtaAtJNspUM/edit#
