### ISSUE TITLE
Tackle Comprehension Gap - Write new content that clarifies GC Notify and highlights benefits and value prop

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#1054]
**Links**
- [Figma](https://www.figma.com/file/bgHBy4o1STV4DlpkpdtIUV/Beta-Marketing-%2B-Clarifying-GC-Notify?node-id=6%3A2093)
- [Marketing Strategy](https://docs.google.com/document/d/1E7bPyCMLbKBGQ_7iSIGhkhyhM5HvxHVbizquq5wND7A/edit)

**Story**
When directing GC people to Notify we want them to be able to learn how Notify solves their problems quickly and easily so they can move on to evaluate the software with a trial. 

**What?**

Update GC Notify with more clear and cohesive information about the solution:
- Have clear and cohesive overall problem statement (at least internally)
- Have clear and cohesive overall positioning statement for solution benefits (at least internally)
- Define problems faced by each segment and answer with specific value (based on table provided by product)
- Update Homepage to highlight value proposition
- Expand features and benefits section to answer GC needs
- Develop checklist that shows how GC Notify meets GC requirements
- Compare and contrast Notify in competitive analysis
- Add guidance page for how to create better notifications
- Publish case studies and examples of ideal transactional use cases
- Clarify the process for how to integrate the API

**Done when** : Tickets of concrete specific task to publish updated/new content are created .  (one ticket per type/place of content)

**Comment by willeybryan** [comment]
https://docs.google.com/spreadsheets/d/1JuIj21VG4mGZkM1SkUapIJH22wVesv56y1z1iQw13sc/edit#gid=0
