### ISSUE TITLE
SPRINT 28 - 04/08 to 14/08- 1)Alpha Finish : Branding. 2) Alpha Finish : Investigate and document Crash pods. 3) Prep Beta : Create new web content that clarify GC Notify

### ISSUE THREAD

**Issue by ClementineHahn** [cds-snc/notification-api#1055]
Goals are capturing specific objectives the product teams intend to tackle within a sprint period. They need to be :
- specific. Meaning with an intended concrete results
- realistic. Meaning drafted with team capcity and time contraints in mind 
- aligned with Road Map. Meaning we can rely them to actual steps outlined in the user road map

**Comment by ClementineHahn** [comment]
Proposals : 
- Spike on assessing Notify alert , goal is to be able to identify problems in tuning those, propose actions, create cards to solve those as a result ?
- Act on prioritised recommandations Marketing action plan ?
- Complete branding actions leftover frmo Sprint 27
- Thanks to reprioritised reserch directions, rework and update B research plan with detailed research activites re-ordered

**Comment by willeybryan** [comment]
Proposals:
By the end of the sprint we aim to:
- Figure out why pods keep crashing
- Align on research and Beta Roadmap
- Have Outreach start creating Marketing Collateral

**Comment by willeybryan** [comment]
Team Talks:
- Please can we finish branding - Left over from last sprint
- Guidance on Notifications - Look to writing these ticket in Backlog
- Dev tune up. Brand name changes(Covid team isn't using master as branch name), list variable name changes

**Comment by willeybryan** [comment]
Take two:
By the end of the Sprint we aim to
- Clarify how we will communicate Beta to everyone
- Prepare research direction and roadmap for Beta Sprint 0
- Beta Polish (Tech stack, github, Crashes, and Guidance)

> 

>
