### ISSUE TITLE
Set an s3 Bucket expiry of month for health Canada s3 bucket

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#1058]
**Story**
When writing security controls we said we don't store user uploads in S3 buckets for over a month so that we can reduce our privacy impact. 

**What?**
- Add a lifecycle rule to the HC s3 Bucket of 28 days. (As Feb is the shortest month.)

**notes**
How do I create a lifecycle policy for an S3 Bucket
https://docs.aws.amazon.com/AmazonS3/latest/user-guide/create-lifecycle.html

**Comment by brdunfield** [comment]
Is this related to / the same the stretch goal for #973 ?

**Comment by willeybryan** [comment]
Yes actually!
Caitlin discovered it was a problem in her audit. I discovered if it was in a separate bucket we could just put a policy on the bucket and that would fix the problem. 

Health Canada is ok with this.

**Comment by willeybryan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Set S3 bucket expiry  for HC S3 Bucket](https://trello.com/c/iUpvfH74/46-set-s3-bucket-expiry-for-hc-s3-bucket)

**Comment by AntoineAugusti** [comment]
Looked at this and I want to confirm a few things before changing anything.

The S3 bucket we are talking about is `notification-alpha-canada-ca-csv-upload`?. Currently, it has a lifecycle rule to delete any object after **44 days**.

![Screen Shot 2020-09-21 at 15 01 44](https://user-images.githubusercontent.com/295709/93809572-6eb69f00-fc1b-11ea-9848-f7fdb583cb04.png)

So Health Canada already benefits from this feature.

- Do we want to reduce this rule to 28 days?
- Do we want to reduce this rule only for Health Canada? If yes, we can add a prefix rule just for them.

**Comment by brdunfield** [comment]
Health Canada does not use this bucket. I don't have it off the top of my head, but can confirm it is not this one.

**Comment by AntoineAugusti** [comment]
@brdunfield Can't find the bucket on S3 and I don't see the code routing to different buckets. Can you talk to me on Slack to sort this when you want? 😄

**Comment by brdunfield** [comment]
Have a look here:

https://github.com/cds-snc/notification-admin/pull/550
and / or here
https://github.com/cds-snc/notification-admin/pull/673

On Staging, "Bethany Test Service" and "McMutry Test Service" have been enabled to access this

**Comment by AntoineAugusti** [comment]
Thanks! The bucket name should be the one in the `BULK_SEND_AWS_BUCKET`environement variable, set to `notify-csv-dump`. Did not find this S3 bucket within the accounts I have access on AWS.

**Comment by brdunfield** [comment]
I will make some time to look into this tomorrow :)

**Comment by brdunfield** [comment]
I am not sure when this happened but there is a lifecycle on this bucket already, set to 7 days. This is also reflected in the files I see in the bucket - the oldest is dated Sept 15.

Do we want to increase this to 28 days? @willeybryan

**Comment by willeybryan** [comment]
@brdunfield Nah, more restrictive reduces privacy impact, and HC only uses the CSVs once. 
This meets my needs. I guess we must have put it in during previous work.

Good job everyone, I will make sure this is reflected in the security and privacy docs. 
Sorry about that, thanks for looking into it.

**Comment by brdunfield** [comment]
I vaguely recall Steve Astels doing this? But I can't locate evidence on GitHub.
