### ISSUE TITLE
Tackle Awareness Gap - Create marketing collateral that aligns with problem awareness for different GC roles

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#1059]
Create outreach campaign for problem awareness:
- Identify channels
- Write taglines
- Plan messages
- Create visuals

Time permitting, work with Vic and Phil to put [marketing strategy](https://docs.google.com/document/d/1E7bPyCMLbKBGQ_7iSIGhkhyhM5HvxHVbizquq5wND7A/edit#) in motion for Beta?

**Comment by ClementineHahn** [comment]
Updated home page in Figma and added lot of content to tackle awareness gap
