### ISSUE TITLE
Content changes to Resend Email Link (1.1.1.1)

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-api#107]
**page:** https://notification.cdssandbox.xyz/email-not-received

- Replace "Email messages sometimes take a few minutes to arrive" with  "Sometimes email messages take a few minutes to arrive".

- Please move the button "Resend email link" to right after the first paragraph. Placing it in between the two paragraphs"

- Please change the second paragraph to the following: "Has your email address changed since you joined Notification? Please ask your account manager to reset it."

**Comment by timarney** [comment]
PR - https://github.com/cds-snc/notification-admin/pull/57

**Comment by YedidaZalik** [comment]
@timarney  - hi Tim, I was trying access this page, but I received this message instead:
jinja2.exceptions.TemplateSyntaxError
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 't'
Thanks!

**Comment by timarney** [comment]
Thanks - spotted and fix this one late yesterday.

<img width="686" alt="Screen Shot 2019-07-24 at 7 32 30 AM" src="https://user-images.githubusercontent.com/62242/61790449-3af8a300-ade5-11e9-9ad7-ee88dd136d60.png">

1. @willeybryan we should add a card to look into tooling i.e. Sentry or something to flag on on `user found` broken pages.

2. We need to figure out what pages / routes don't have test coverage.  To start thinking we can look into pulling a list of routes in use.
