### ISSUE TITLE
Updated threat ENUMS list to Match mitigations from Diagram

### ISSUE THREAD

**Issue by ClementineHahn** [cds-snc/notification-api#1073]
In order to complete the ATO for Notify Beta phase , we need to complete the threat list. 

In order to do this : 

- In the doc Update threat list 
-  go to the tab “external entity, Data store, Processes 
- **update only the yellow line.** 
https://docs.google.com/spreadsheets/d/167wtA5zKQrdGEH0WzSCYISvgMEX5eAZsRCw0xLiBE3k/edit#gid=1734898491

- for threat that concerns CDS organisation wide and solutions are at the level of CDS , we must link to "CDS threat list" and tagg Caitlin on it to link to this doc

**Comment by willeybryan** [comment]
Updated Yellow lines with descriptions
