### ISSUE TITLE
Update Homepage Content including Images

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#1075]
**Links**
- [Figma](https://www.figma.com/file/bgHBy4o1STV4DlpkpdtIUV/Beta-Marketing-%2B-Clarifying-GC-Notify?node-id=6%3A2093)
- [Marketing Strategy](https://docs.google.com/document/d/1E7bPyCMLbKBGQ_7iSIGhkhyhM5HvxHVbizquq5wND7A/edit)

**Story**
When directing GC people to Notify we want them to be able to learn how Notify solves their problems quickly and easily so they can move on to evaluate the software with a trial. 

**What?**

Update GC Notify with more clear and cohesive information about the solution:

- Clarify core offering and value to audience
- Highlight value proposition
- Show how it meets GC needs and requirements
- Answer common questions in product itself

**Why?** 
Have something solid to share out and link to

**Done when**
Changes are available in FR an EN in Figma ready to be implemented, reviewed, and new card to implement is created

**Comment by ClementineHahn** [comment]
Updated yesterday , on going

**Comment by ClementineHahn** [comment]
Done check list:

- [ ] Content created

- [ ] Policy review @sboots 

- [ ] Français revision Elise

**Comment by anikbrazeau** [comment]
Bilingual v5 is being reviewed by Elise this week
https://www.figma.com/file/bgHBy4o1STV4DlpkpdtIUV/Beta-Marketing-Clarifying-GC-Notify?node-id=6%3A2

**Comment by anikbrazeau** [comment]
French reviewed. Latest version ready to implement on the right side of Figma:

- _v6_Checklist-EN Aug 25_
- _v6_Checklist-FR Aug 25_

[Will requires a change in global navigation]

**Comment by anikbrazeau** [comment]
Content is almost ready to implement.

See Figma pages all the way to the right here: https://www.figma.com/file/bgHBy4o1STV4DlpkpdtIUV/Beta-Marketing-Clarifying-GC-Notify?node-id=6%3A2

v6 Homepage EN - Aug 25
v6 Features FR Aug 25

Illustrations are still being revised.
Testimonials are being gathered.
