### ISSUE TITLE
Content change Choose a Service (0.1) and About your Service (0.2) pages

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-api#108]
**Pages:**
- https://notification.cdssandbox.xyz/accounts
- https://notification.cdssandbox.xyz/add-service

**What?**
- Is it possible to combine these two pages into one?
- Remove "Who runs this service?" and the options that below it. ~~Radio button Question (Bryan would like to know: Where does this get saved?)~~
- Change terminology of 'Service' to '@YedidaZalik will fill this in later'

**Comment by timarney** [comment]
@willeybryan 

> Where does this get saved?

The data gets saved to the services table in the database.  Not sure if that answers your question if not can you clarify further?

**Comment by timarney** [comment]
@YedidaZalik 

> Is it possible to combine these two pages into one?

What value / advantage do you see if we combine these pages?

**Comment by willeybryan** [comment]
Yes That answers my question! thanks!

**Comment by timarney** [comment]
Going to close this and we can discuss this note separately.

> Is it possible to combine these two pages into one?

Yes possible but what's the advantage (users are unlikely to be creating services very often - are we trying to save them time or what else are we considering?)

**Comment by YedidaZalik** [comment]
Thanks - probably best to wait on this anyway until Bryan & Sean can discuss various definitions of "service" at our meeting.
