### ISSUE TITLE
Typo: missing space after "ODS" variable

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#1080]
Missing space:

**EN** Save your file as a CSV, TSV, **ODS^or** Microsoft Excel spreadsheet

**FR** Enregistrez votre fichier comme tableur, en format CSV, TSV, **ODS^ou** en feuille de calcul Microsoft Excel

<img width="504" alt="Screen Shot 2020-08-11 at 10 04 55 PM" src="https://user-images.githubusercontent.com/38330843/89967267-07223280-dc1f-11ea-9df4-9843a9de6213.png">

<img width="415" alt="Screen Shot 2020-08-11 at 10 04 48 PM" src="https://user-images.githubusercontent.com/38330843/89967268-07bac900-dc1f-11ea-812b-2e33b0b51e43.png">

**Comment by brdunfield** [comment]
Closed by https://github.com/cds-snc/notification-admin/pull/755
