### ISSUE TITLE
Switch all instances of "login" to "sign-in" to match "Sign in" action in header

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#1082]
![image (1)](https://user-images.githubusercontent.com/38330843/90144498-e3f5a100-dd4c-11ea-8558-86ed0b04a181.png)

**Comment by willeybryan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Replace Login with Sign in](https://trello.com/c/vHZdEVMk/45-replace-login-with-sign-in)

**Comment by AntoineAugusti** [comment]
@anikbrazeau Do you want the title to be "Sign-in history" or "Sign in history"?

There are quite a few instances of "login" or "log in" in https://github.com/cds-snc/notification-admin/blob/master/app/translations/csv/en.csv. Could you say what you want to keep/change?

**Comment by anikbrazeau** [comment]
When it's an adjective describing a noun, let's do "sign-in" 
When it's on its own as an action: "sign in"

Generally, 
- If it replaces "login" it should be "sign-in"
- If it replaces "log in" it should be "sign in"
