### ISSUE TITLE
content change to Example Text Message Template (First time account Creation)  (0.3 example steps 1-3, 2-3, and 3-3)

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-api#109]
**Pages: (Relative to my service)**  
- https://notification.cdssandbox.xyz/services/cb9c86a3-d62f-4e87-bcb7-89f6e660365d/start-tour/4a2983ee-602a-4d9c-9874-086924fdc4e7
- https://notification.cdssandbox.xyz/services/cb9c86a3-d62f-4e87-bcb7-89f6e660365d/send/4a2983ee-602a-4d9c-9874-086924fdc4e7/test/step-0?help=2
- https://notification.cdssandbox.xyz/services/cb9c86a3-d62f-4e87-bcb7-89f6e660365d/template/4a2983ee-602a-4d9c-9874-086924fdc4e7/notification/check?help=2
https://notification.cdssandbox.xyz/services/cb9c86a3-d62f-4e87-bcb7-89f6e660365d/notification/86e23ca6-e5b2-450b-812d-c1819db18e25?help=3

**What?**
- Please replace text in side list "The template pulls in the data you provide" with "You enter data in the template"

**Notes:**
Screen Shot of the area in question:

![image](https://user-images.githubusercontent.com/46505127/61383425-a76f2180-a87c-11e9-87f2-3e0bec1ed687.png)

**Comment by timarney** [comment]
@YedidaZalik @willeybryan 

I don't think "You enter data in the template" would be correct to say.

You're providing data to the templates either via the api script or via a csv / excel spreadsheet.

**Comment by willeybryan** [comment]
Yeah, I get that. The demo isn't clear on how that works later though so it can set expectations we don't want the user to carry through. 

You are right too because you don't enter data into the template, not here.

@YedidaZalik we may want to instead add a note on the page in 0.3 step_2-3 that says later you will be able to populate this information from a spread sheet to set future expectations.

**Comment by YedidaZalik** [comment]
@willeybryan @timarney  
Would it be okay to say " The template pulls data from your spreadsheet"?

**Comment by willeybryan** [comment]
Yeah that could work, it sets expectations correctly in my mind.

**Comment by timarney** [comment]
It won't always be a spreadsheet.  If your using the api the developer can define the list however they want.

**Comment by YedidaZalik** [comment]
Would "The template pulls data from your list" work?

**Comment by timarney** [comment]
Depends on what you want to call a list.

If I'm sending data to a single person using the api the code doesn't really pull from a list I'm just providing a couple of values.

```javascript
notifyClient
    .sendEmail(templateId, "test@example.com", {
      personalisation: {
        first_name: "Tim"
      }
    })
```

**Comment by YedidaZalik** [comment]
How about "The template pulls information from your data"?

**Comment by timarney** [comment]
Sure.

**Comment by timarney** [comment]
Merged.
