### ISSUE TITLE
[Card to Break down for each artifacts] Design Timeline doc : reflect past iterations and decisions on the product

### ISSUE THREAD

**Issue by ClementineHahn** [cds-snc/notification-api#1109]
**Why:** 
- Take stock of what we've learned and what we've done before planning what happens next
- Help someone who is onboarding orient themselves on the project
- Understand how research insights informed design decisions and which ones made it to production
- Understand how we should order priorities
- Only make new mistakes/changes and learn new things going forward

**Links:**
- [Timeline of design events](https://docs.google.com/document/d/1lT4vyCqB924nHWUxtmzSgw5Z8sPcQl-EJi3kUGuizB8/edit#)
- [Deliverables re-organized by category or theme](https://docs.google.com/document/d/12TB5FqQW0ttlrSeW2aQNtipgRMsfxEYjzaDbpnd3hrs/edit#heading=h.ysu24j5q6pgt)
- [Storylines Documentation Deck](https://docs.google.com/presentation/d/1gwK4b-R3izYsAh12MVWkFknWDR7URkxTPp1jHU9gULc/edit#slide=id.g4cea57f733_0_0)

**Done when:**
A scannable source of truth exists to understand design interventions so far

**Comment by ClementineHahn** [comment]
Discussion with design team to reflect on how to reorganize the content and make it more accessible .

**Comment by ioanacontu** [comment]
We've abandoned mapping it in Figma, now working on a [Slide deck](https://docs.google.com/presentation/d/1gwK4b-R3izYsAh12MVWkFknWDR7URkxTPp1jHU9gULc/edit#slide=id.g4cea57f733_0_0) that suits the purpose better and allows for more flexibility of content and future maintenance of the documentation.

**Comment by ClementineHahn** [comment]
Ioana to review the goal and the audience of this doc to wrap up in the next couples days

**Comment by ClementineHahn** [comment]
Discussion with research and review to refine the audience of this doc and the next steps.
