### ISSUE TITLE
Document Tools needed to work with Notify (Kubernetes)

### ISSUE THREAD

**Issue by ClementineHahn** [cds-snc/notification-api#1111]
Connecting to the kubernetes clusters
Accessing the databases (Hasura)
Cloudwatch queries

**Comment by sastels** [comment]
[Connecting to the kubernetes clusters](https://docs.google.com/document/d/18w44esbq00JClsvHvlcrSiEnolCIlV5n-YKdVsq6bJk)
[Accessing the databases (Hasura)](https://docs.google.com/document/d/1gax1PXUPTBejw2c8WMF1LP-uGFk_UkTySoAFgOateZI)
[Cloudwatch queries](https://docs.google.com/document/d/1iqsUODS_BCYc6CDIO7noq9mUluS0qiMf8JdymDClITE)
