### ISSUE TITLE
Incident bounce rate response

### ISSUE THREAD

**Issue by ClementineHahn** [cds-snc/notification-api#1115]
Incident report: https://docs.google.com/document/d/1-EZVE-Gn66Cjin7sjbxSz3nXjPSNYEctz6pTlCHPC0o

- [x] Create a channel

- [x] Take actions for immediate answer

- [x] Create an incident report 

- [x] Run the review (to be happening Friday 11th Sept)

**Comment by sastels** [comment]
Turned on the suppression list for SES with the CLI command
```
aws sesv2 put-account-suppression-attributes --suppressed-reasons BOUNCE COMPLAINT
```

Sent a bad email through the admin and verified that it was added to the suppression list list with
```
aws sesv2 list-suppressed-destinations
```
Also verified the next day that other addresses had been added to the list.
