### ISSUE TITLE
Team tools and Sprint cycle redo

### ISSUE THREAD

**Issue by ClementineHahn** [cds-snc/notification-api#1116]
Goal is for team to realign on ideal sprint process and which tool for each steps

**Comment by willeybryan** [comment]
https://docs.google.com/drawings/d/1WAUr2WsQ3O6zmdmLI3Kr80myz5BR88ouNPvdxBoifss/edit
https://docs.google.com/drawings/d/1xhp7rQEBdfSK9A8OfMkwZpbH66OFuvWfLAj5M9gThgs/edit
https://docs.google.com/drawings/d/1xhp7rQEBdfSK9A8OfMkwZpbH66OFuvWfLAj5M9gThgs/edit
