### ISSUE TITLE
Step 1: Get Notify Running Locally

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#1124]
Developer Google Drive Location:

https://drive.google.com/drive/folders/1hZARZrl35Oj42CvpoonvlWkt8fShSbS3

**Comment by ClementineHahn** [comment]
Done when : Documentation in the "read me" is updated in EN and FR

**Comment by sboisvert** [comment]
https://github.com/cds-snc/notification-admin/pull/773

**Comment by sboisvert** [comment]
https://github.com/cds-snc/notification-api/pull/1140
