### ISSUE TITLE
International SMS stuck in sending on staging

### ISSUE THREAD

**Issue by AntoineAugusti** [cds-snc/notification-api#1126]
On staging, I tried to send an SMS to my :fr: number and it’s stuck in `sending`. Checked that Send international text messages is "On" but no luck.

![Screen Shot 2020-09-14 at 15 21 43](https://user-images.githubusercontent.com/295709/93130108-0d814f80-f6a0-11ea-9d14-f3517a4301b3.png)

@brdunfield pointed
> It is interesting that it is stuck in sending though, as we mock SMS responses to always show as delivered since we do not have access to a callback from the providers

My service link: https://staging.notification.cdssandbox.xyz/services/44d3d6df-8c46-49fe-97b6-7acddc8077ac

**Comment by brdunfield** [comment]
This is a result of staging config. International messages work on prod.
