### ISSUE TITLE
Document Prod Push

### ISSUE THREAD

**Issue by ClementineHahn** [cds-snc/notification-api#1127]
Document How we proceed with Prod Push for Nottify and make it easy step by step and checklist what to do.

**Comment by brdunfield** [comment]
https://docs.google.com/document/d/17kVWBN4OK_mSgTK7h_dTyC1kpjcY_UhXOn1FpolH-GM/edit#

Draft. I'm going to take another pass to flesh it out when I have the time.

**Comment by brdunfield** [comment]
Going to close this for now - the doc can update and iterate as needed in the future
