### ISSUE TITLE
Bug: branding images not showing up

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#1130]
<img width="681" alt="Screen Shot 2020-09-17 at 11 29 45 AM" src="https://user-images.githubusercontent.com/38330843/93493029-77d10480-f8d9-11ea-8910-1ceea01f0305.png">

**Comment by willeybryan** [comment]
Dupped here for now while we figure this all out https://trello.com/c/cYObE6KE/26-branding-images-not-showing-up-in-preview

ALL IS WELL

**Comment by brdunfield** [comment]
They are showing on staging - looks like they just weren't uploaded to the prod bucket. Should be a quick fix :)

**Comment by brdunfield** [comment]
Uploaded!
