### ISSUE TITLE
Clean up and Remove old CSS

### ISSUE THREAD

**Issue by brdunfield** [cds-snc/notification-api#1138]
Part of #1131 

Once our new CSS system is rolled out onto all Notify pages, we need to clean up and remove the old system.

Done when:
All old CSS files and references are removed from Notify

**Comment by willeybryan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Investigate Tailwind as the preferred solution compared to other viable options](https://trello.com/c/wuTQBfGk/32-investigate-tailwind-as-the-preferred-solution-compared-to-other-viable-options)

**Comment by willeybryan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create a Staging environment with no CSS to Test New CSS](https://trello.com/c/1FoCUHsS/12-create-a-staging-environment-with-no-css-to-test-new-css)
