### ISSUE TITLE
Content changes to New Template Page (3.0.3)

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-api#114]
**Page:(Relative to my service)**
- https://notification.cdssandbox.xyz/services/cb9c86a3-d62f-4e87-bcb7-89f6e660365d/templates/add-email
- https://notification.cdssandbox.xyz/services/cb9c86a3-d62f-4e87-bcb7-89f6e660365d/templates/add-sms

**What?**
- Please replace "Formatting" with "Format"
- Please replace "To add a callout, use a caret:" with  "To emphasize text, use a caret. There will be a grey bar beside the text you want to emphasize".
- Please replace "Personalisation" with "Add personal information"
- Please replace "Use double brackets to personalize your message:" with "Use double brackets to add personal information about the recipient:"
- Under "Optional content" replace text before the example with the following :
"You can enter optional content in your template by uploading a spreadsheet with information about your users. " 
"For example, your spreadsheet may include the age of each user.  You want users who are under 18 to receive optional content.   Use double brackets and '??' to include the optional content."
- Please replace the text after the example with the following:
" For each recipient on your spreadsheet, you must indicate 'yes' to show or 'no' to hide this content."

**Comment by timarney** [comment]
FYI- @willeybryan if you or anyone else has time to test the "Optional content" that would be good. The CSV upload should be working now.

**Comment by willeybryan** [comment]
@willeybryan Test CSV upload and Optional content with mailinator inboxes

Also do I get this email myself? because that would be handy.

**Comment by willeybryan** [comment]
@timarney I tested the CSV upload and it uploaded, but it wouldn't send. I got the following screen. 


![image](https://user-images.githubusercontent.com/46505127/61726352-80629500-ad3f-11e9-9269-3b4a64a2a4db.png)


https://notification.cdssandbox.xyz/services/cb9c86a3-d62f-4e87-bcb7-89f6e660365d/start-job/28e39e11-41e6-4645-a0e2-c662f658c3b8?original_file_name=Mailinator+Test+23_7_2019.csv

**Comment by timarney** [comment]
Okay - yes confirmed it's throwing an error.  Let's add a card for that to fix.
