### ISSUE TITLE
Create a security.txt file for vulnerability disclosure practices

### ISSUE THREAD

**Issue by AntoineAugusti** [cds-snc/notification-api#1148]
Related to https://github.com/cds-snc/digital-canada-ca/issues/1492

We should let people know how to reach us to disclose security issues.  @obrien-j will provide content for this TXT page, based on spec defined at https://securitytxt.org

**Done when**

The security.txt is available at https://notification.alpha.canada.ca/.well-known/security.txt

**Comment by AntoineAugusti** [comment]
What do you think of this first version?

```
Contact: mailto:security@cds-snc.ca
Contact: mailto:securite@cds-snc.ca
Preferred-Languages: en,fr
Policy: https://github.com/cds-snc/.github/blob/master/SECURITY.md
Hiring: https://digital.canada.ca/join-our-team/
Hiring: https://numerique.canada.ca/rejoindre-notre-equipe/
```

**Comment by RenDavidDimen** [comment]
I personally feel like this makes sense. 

I noticed that other `security.txt` files in the org refer to the [Vulnerability Disclosure Policy for COVID Alert](https://github.com/cds-snc/covid-alert-documentation/blob/main/VulnerabilityDisclosurePolicy.md) for more information. Should one specific to Notify be created and referenced in our `system.txt` file as well?

**Comment by AntoineAugusti** [comment]
@RenDavidDimen We've got a security page so we may as well link to it https://notification.alpha.canada.ca/security

**Comment by RenDavidDimen** [comment]
Added route with relevant information to route `/.well-known/security.txt`
