### ISSUE TITLE
Content change to Team Members (4.0)

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-api#115]
**Page:(Relative to my service)**
- https://notification.cdssandbox.xyz/services/cb9c86a3-d62f-4e87-bcb7-89f6e660365d/users

**What?**
- Under the heading "Team members" add the following:
"Share templates with your team"
- Then before the name of the existing team members add a sub-heading:
"Current team members"
- Change button that says "Invite a team member" to "Invite someone to join your team"

**Comment by timarney** [comment]
@YedidaZalik @willeybryan 

Does Team members ... Current team members seem repetitive in this screen? 

![Screen Shot 2019-07-23 at 10 24 39 AM](https://user-images.githubusercontent.com/62242/61720296-8010cc80-ad34-11e9-92fe-56d95022f60d.png)

**Comment by YedidaZalik** [comment]
You are right, thanks for pointing that out- let's try without "current" 
Hopefully the new wording about "invite someone . . ." should make it clear.

**Comment by willeybryan** [comment]
Yeah, get rid of 'current team members', It seems that it isn't even true because it will show people who have been invited but haven't yet accepted the invite.
