### ISSUE TITLE
When being used across Canada we need dynamic timezone to support everyone

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#118]
**What?**
- Timezone is currently hardcoded to America/Toronto. We want to make the dynamic to the users location.
- UI elements will need to pull in the time zone for Logging when messages were send or sending bulk messages

**Why?**
- we want to be able to support users across Canada and not confuse them.

**Comment by maxneuvians** [comment]
We need to find all the places in the UI where time is shown and make it browser dynamic

**Comment by maxneuvians** [comment]
A lot of the UI stuff was closed with dynamic time support through the browser. https://github.com/cds-snc/notification-admin/pull/110. Items remaining in this ticket are:

- Fix tests in admin, that had been skipped
- Make the API timezone configurable for when it runs the reports
- Fix the API tests that have been skipped
- Fix the Utils tests so they can use a dynamic timezone

**Comment by willeybryan** [comment]
I will make tickets for those tests and config.
