### ISSUE TITLE
API endpoint for data download from dashboard

### ISSUE THREAD

**Issue by jidicula** [cds-snc/notification-api#1199]
Thanks for creating this tool! My team over at [Digital HR](https://github.com/Digital-HR) in DND use this for our apps. We were wondering if it's possible for your team to also create an API endpoint for the report download (see attached). We would like to keep more persistent logs of which emails are being sent when and to who, and setting up a cronjob to query the API every 7 days would be ideal, rather than manually downloading the CSV each time.

Alternatively, do you have a better suggestion using existing functionality that might help us with our logging needs?

![image](https://user-images.githubusercontent.com/12765385/103094198-b65a1780-45ca-11eb-9358-0eaf4dcaee5d.png)

**Comment by AntoineAugusti** [comment]
Hello @jidicula!

Notify has a callback/webhook functionality: Notify can send a POST HTTP request to an endpoint you specify with a delivery receipt for each email/text message sent.

The documentation for that is accessible at https://notification.canada.ca/callbacks once you're signed in:
![Screen Shot 2020-12-24 at 16 13 39](https://user-images.githubusercontent.com/295709/103096079-be1cba80-45d0-11eb-8889-79bd04f06f10.png)

Do you mind getting in touch with us at https://notification.canada.ca/contact to chat with your team after the holidays?

**Comment by jidicula** [comment]
Great, I'll look into this, thanks!

And I'll definitely be in touch in the new year! Have a great holiday!

**Comment by jidicula** [comment]
@AntoineAugusti I just sent a message via the form, hope to chat soon!
