### ISSUE TITLE
Notification can't use the GDS font so we need an alternative that won't break the layout. 

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#12]
**What?**
- We have to use a different font
- This could change the layout so things will have to be tweeked and redesigned
- Can we find a font that is similar in shape, size, and kerning, to minimize problems
- How hard is it to swap the font?

**Why?**
- GDS owns the rights to their font and we don't

**Comment by willeybryan** [comment]
Sean suggested Lato as a replacement

**Comment by timarney** [comment]
Removed UK font.  Using a system font stack (arial / helvetica) for now.  Can switch to Lato or whatever later once we have a designer involved.
