### ISSUE TITLE
Content changes and rewrites to Security page

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#121]
**What?**
- Security page needs content to reflect out security posture
https://notification.cdssandbox.xyz/features/security

**Why?**
- We need to state our security posture
- Get ready for translation

**Comment by YedidaZalik** [comment]
Security page rewritten after consults with @sboots about removing some sections and @willeybryan about rewriting some technical language:https://github.com/cds-snc/notification-api/issues/143
linking to https://docs.google.com/document/d/1SSgY3iXycjq4JyzbUc7w26NR-cKhLonzAi30pvXkqWQ/edit#heading=h.t34jn1d2dbmg
