### ISSUE TITLE
Bug: Three sms messages receieved on sign up

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/notification-api#124]
A user reported receiving three SMS messages with validation codes when they signed up to the service. This is also reflected in the database. We need to investigate if this is a one time occurrence or a repeatable bug. 

**notes**
- Seems to be on fresh accounts
- Seems to works fine if we are just sending templated SMS from a live service

**Comment by timarney** [comment]
Currently testing.

2 tests so far have sent a single text message.

**Comment by maxneuvians** [comment]
In case it comes up again 

https://github.com/cds-snc/notification-api/blob/master/app/user/rest.py#L212-L213

**Comment by timarney** [comment]
Going to write some logic to stop multiple sends in < TIME_FRAME .

Parking and will come back it soonish.
