### ISSUE TITLE
Phone number user experience 

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#128]
**What?**
**Page:** https://notification.cdssandbox.xyz/register

- Mobile number: Needs to be seamless for the user. Please ensure it is configured so that the the phone number works if a person puts a 1 at the start or not. 

**Why?**
- We don't want users to have it work or not depending on weather they add a 1 at the start of their phone number

**Comment by maxneuvians** [comment]
I have tried this with the following combinations:

1-613
1613
+1613
613

They all work
