### ISSUE TITLE
Change the name of the branch in all notify repos to 'main'

### ISSUE THREAD

**Issue by dj2** [cds-snc/notification-api#1289]
Notification repos left to change to `main`:

- [ ] Notification-admin
- [ ] Notification-api
- [ ] Notification-utils 
- [ ] notification-document-download-api 
- [ ] notification-document-download-frontend
- [ ] notification-pr-bot
- [ ] notification-scheduler
- [ ] notifications-bulk-send

**Comment by AntoineAugusti** [comment]
The main problem is with our deploy pipeline https://github.com/cds-snc/notification-pr-bot/blob/aa7a3a15129dd3dd48111c4f82ab7b50f643d9de/index.js#L17-L43 and Kubernetes https://github.com/cds-snc/notification-manifests

**Comment by AntoineAugusti** [comment]
Related to https://github.com/cds-snc/notification-admin/issues/1020 https://github.com/cds-snc/notification-pr-bot/issues/16 https://github.com/cds-snc/notification-document-download-frontend/issues/55 https://github.com/cds-snc/notification-document-download-api/issues/38

**Comment by dj2** [comment]
For the PR bot, what happens if there is an entry in there for a branch that doesn't exist? Do we know if the bot will just ignore it? If it does, we could add 'main' alongside 'master' in the list and then remove 'master' post deploy.

If it doesn't support it .... do we control the code, could I make it supported?

For Kubernetes, I don't have knowledge of kubernetes so I don't know how hard it would be to migrate. Do you deploy on every push? Could we prepare the kubernetes change in a branch  that gets committed soon after the changes to other repos?

**Comment by yaelberger-commits** [comment]
@jzbahrai can you please have a look at this one? Thanks

**Comment by HEYGUL** [comment]
I have the feeling this issue could be closed (`main` branch seems now alive instead of `master`).

**Comment by jimleroyer** [comment]
Yes, the mainline branch for all our active projects are now in `main` for quite some time.
