### ISSUE TITLE
Content change to new task flow slide 5.0 documentation

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-api#130]
Please replace all text before the bulleted list with the following:

**Technical documentation** (but in header shorten to **Technical docs**)

Application Programming Interface (API) documentation to send messages automatically.

**Libraries**

Choose a library to integrate our API with your web application. The technical documentation will open in a new tab hosted by GOV. UK Notify.   GOV.UK  kindly shared Notify so that Canada can build Notification.

**Comment by willeybryan** [comment]
Merging with Doc changes on https://github.com/cds-snc/notification-api/issues/135
