### ISSUE TITLE
Content change to https://notification.cdssandbox.xyz/email-not-received

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-api#131]
**Page:** https://notification.cdssandbox.xyz/email-not-received

**What?**
- Please change "do not" to "don't"

[Sorry to add this change which I forgot the first time round: web writing recommends contractions to be friendlier in tone]

**Comment by timarney** [comment]
@YedidaZalik I believe this was updated yesterday.  Does this look correct? 

<img width="745" alt="Screen Shot 2019-07-25 at 7 55 07 AM" src="https://user-images.githubusercontent.com/62242/61872533-955f3580-aeb1-11e9-97e2-aad58691ee4e.png">

**Comment by YedidaZalik** [comment]
Yes  but could you please change "recieve" to "receive"?
Sorry I did not catch that earlier!

**Comment by timarney** [comment]
Fixed here - https://github.com/cds-snc/notification-admin/pull/78
