### ISSUE TITLE
SVG images to edit for Home page

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#134]
**What?**
- Home page images for Notification 
- image 1 Needs Notify changed to Notification
- Rewrite everything in image 1 and 2 because we don't have the font and we need to translate it
- Make a second copy for French

**Why?**
- Can't use GDS font due to copyright
- Need to translate text

**Notes**
- Image 1 https://notification.cdssandbox.xyz/static/images/product/01-templates.svg?f1f89c55b8a16fc6e5c2342d3b0492d1
- Image 2 https://notification.cdssandbox.xyz/static/images/product/03-spreadsheet.svg?26ba478c6b7bf53ff0844a9d5b6300ad

**French Text**
- Please stand by, double checking my work.

**Comment by willeybryan** [comment]
French Translations for images:

mage 1

Modèle d'ajout de message texte

Message
Salut ((Nom)), 
J'essaie Notification. Aujourd'hui nous sommes ((jour de la semaine), et ma couleur préférée est ((couleur)).
Sauvegarder

Image 2

Ajouter des destinataires

Adresse courriel | Nom | Couleur
@exemple.com
Rouge
Vert
Bleu

**Comment by maxneuvians** [comment]
Best effort Image 1:

[01-templates-fr.zip](https://github.com/cds-snc/notification-api/files/3517303/01-templates-fr.zip)

**Comment by maxneuvians** [comment]
Best effort Image 2:

[03-spreadsheet-fr.zip](https://github.com/cds-snc/notification-api/files/3517327/03-spreadsheet-fr.zip)

**Comment by maxneuvians** [comment]
First image yellow boxes broken in chrome, work in FF
