### ISSUE TITLE
Unable to send Emails in bulk to uploaded list

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#141]
**Steps to reproduce:**
- Navigate to a template
- Click Send
- Upload a list of recipients (I opted to download the provided template on this page, fill it in with text edit, then reupload it, I also used addresses at Mailinator.com)
- Click send now

**Expected**
- It sends
- Emails in Inboxes
- Emails logged in Dashboard

**Actual**
- An unexpected error occurred
- No emails logged as sent
- No emails recieved

**Notes**
- 
![image](https://user-images.githubusercontent.com/46505127/61797270-10164b00-adf5-11e9-95ef-fe338fc92515.png)

**Comment by timarney** [comment]
I have this working locally as of this a.m

On the staging server the upload steps work but it seems to get stuck in the queue.  Will look into that.

<img width="809" alt="Screen Shot 2019-07-25 at 7 26 20 AM" src="https://user-images.githubusercontent.com/62242/61872308-02260000-aeb1-11e9-9b27-8e295ee8d646.png">

**Comment by timarney** [comment]
Works on staging.
<img width="827" alt="Screen Shot 2019-07-25 at 9 38 19 AM" src="https://user-images.githubusercontent.com/62242/61878976-11f91080-aec0-11e9-99a0-69d3a22dda1a.png">
