### ISSUE TITLE
Content change to new email template https://notification.cdssandbox.xyz/services/cb9c86a3-d62f-4e87-bcb7-89f6e660365d/templates/add-email

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-api#142]
**Page:** https://notification.cdssandbox.xyz/services/cb9c86a3-d62f-4e87-bcb7-89f6e660365d/templates/add-email

- Please put a colon after  "Your recipients won’t see this:'

- Please put a colon after "There will be a grey bar beside the text you want to emphasize:"

- Please change "For each recipient on your spreadsheet, you must indicate ‘yes’ to show or ‘no’ to hide this content" to

- "For each recipient on your spreadsheet indicate:
-- ‘yes’ to show optional content
--  ‘no’ to hide optional content"

Thanks!

**Comment by YedidaZalik** [comment]
@timarney  
Was this the item where you had suggested the term "spreadsheet" was not accurate?
I can't  find the github notes about that, so maybe I'm thinking of a different item?

**Comment by timarney** [comment]
I would say spreadsheet is accurate here:

It refers to this section of the interface.

![Screen Shot 2019-08-06 at 10 04 20 AM](https://user-images.githubusercontent.com/62242/62546509-9a1cd580-b831-11e9-94a0-64106dc267cf.png)

Feel free to re-close or otherwise :)

**Comment by YedidaZalik** [comment]
okay great!
