### ISSUE TITLE
Content change to Usage page https://notification.cdssandbox.xyz/services/e609f6b0-0390-45b0-aaae-f4cc92c713e4/usage

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-api#145]
**Page:** https://notification.cdssandbox.xyz/services/e609f6b0-0390-45b0-aaae-f4cc92c713e4/usage

- In the two blocks at the top of the page, please change "financial" to "fiscal" 
Thanks!

**Comment by willeybryan** [comment]
Usage page is getting hidden, parking this until such a time as it isn't anymore
