### ISSUE TITLE
Content changes to Message status page https://notification.cdssandbox.xyz/features/messages-status

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-api#146]
**page:** https://notification.cdssandbox.xyz/features/messages-status

**What?**

Message status
(1) Please replace the first  2 paragraphs on the page with : 
“ Notification’s real-time dashboard lets you check when your message was delivered. You can also check the status of your messages.

(2) There are 2 places at bottom of  chart where says try a different channel. Please replace the word “channel” with “method”

(3) Below the chart, after the heading“Types of message status”
Please replace the first two paragraphs with this:

“Notification has the following types of message status (API message status may be different and is found in technical documentation):”

(4) For emails, please replace the first sentence beside “Sending” with: 
“Notification has sent the message to the email provider.”

(5) Please replace the description of email technical failure with:

There was a connection problem between Notification and the email provider. You’ll have to try sending your messages again.”

(6) For text messages, please replace the first sentence beside “Sending” with “Notification has sent the message to the cellular provider.”

(7) Please replace the description of text message technical failure:

There was a connection problem between Notification and the cellular provider. You’ll have to try sending your messages again. You will not be charged for text messages that are affected by a technical failure.

**Comment by timarney** [comment]
@willeybryan 

> (2) There are 2 places at bottom of chart where says try a different channel. Please replace the word “channel” with “method”

RE: “channel” with “method” ... these are part of the .svg file so I can't edit

**Comment by willeybryan** [comment]
Cool, thanks for the heads up! Don't worry about that now I will log that for later.

**Comment by YedidaZalik** [comment]
:)
