### ISSUE TITLE
Improve test coverage - Get a list of URLs/Routes that don't have test coverage

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#149]
**What?**
- We need a baseline test coverage of pages and routes so that we can identify and fix gaps

**Why?**
- We don't know how much test coverage we have on pages exposed to users. 
- Better test coverage ensures a more stable UX
- Identify gaps to improve reliability

**Comment by willeybryan** [comment]
Here is a copy of all possible routes from the admin side https://gcdigital.slack.com/archives/CAG3WKMC4/p1564146831003900

**Comment by willeybryan** [comment]
Once we have this, what should we do with it?
As the URLS are private, what should we do to improve coverage?

**Comment by timarney** [comment]
Looks like the majority of the routes have roughly 70%+ coverage 

Running this gives us the results.
```
py.test -n4 --maxfail=10 --cov=app --cov-report=term-missing tests/ --junitxml=test_results.xml --strict -p no:warnings
```

With that plus we now have Sentry and a 404 report (Google Analytics ) in place we're in a much better spot to catch the gaps as we go.

**Comment by willeybryan** [comment]
Sounds like no further action is needed at this time.
