### ISSUE TITLE
TIME: Sprint-ly Security Bump! (Fortnightly), Merge Conflicts

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#150]
**What?**
- For Sprint Alpha 1 we need to ensure we update security in our repos
- Pull upstream security patches
- Resolve Snek vulnerabilities
- From last bump: To bump jQuery to 3.x we need to investigate the failing tests for fullscreenTable.js

**Why?**
- The security czar requires an offering in order to ensure we can keep peoples information safe

**Comment by timarney** [comment]
Fixed fullscreenTable issue here https://github.com/cds-snc/notification-admin/pull/83 we're now on jQuery 3.x.

Will bump other deps as they come up.

**Comment by timarney** [comment]
All up to date.
