### ISSUE TITLE
S3 Buckets for Email Branding and attachments

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#151]
**What?**
- Email branding requires the ability to upload logos for users to attach to their service
- We need an S3 bucket that the system can CRUD
- Eventually we will want to put in attachments and that will need a bucket to CRUD as well
- Users will need to see what their branding will look like so we need to be able to see previews from the buckets

**Why?**
- Future development will require these buckets

**Comment by timarney** [comment]
https://github.com/cds-snc/notification-admin/pull/86
https://github.com/cds-snc/notification-api/pull/163
