### ISSUE TITLE
What products or services in Government exist that could use a notification system?

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#16]
**What?**
- We build a one off notification api system for IRCC to send email notifications
- What other Gov Products and Services are there that could use Email, or more important SMS?
- Does anyone currently send SMS?

**Why?**
- We need people who could use out notification system API
- SMS is a big value add and competitor differentiator.

**Comment by AntoineGarciaSuarez** [comment]
Related questions: 

- When services send notifications to their users, how do they do that? At what frequency? 
- What kind of resources, and tools or templates do they need?

**Comment by willeybryan** [comment]
Can't find anyone who uses SMS
