### ISSUE TITLE
Content changes to Emails page https://notification.cdssandbox.xyz/features/email

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-api#165]
**Page:**
- https://notification.cdssandbox.xyz/features/email

**Please change:**
- first line to "Send an unlimited number of free emails with Notification"
- second bullet "personalise" to "personalize"
- change "You can also integrate . . . " to "Your developers can also integrate. . ."
- delete entire "Email branding" section
- delete entire "Send files by email section"
- first line after "Add a reply-to address" please change to "Notification lets you choose the email address where users can send their reply"
- delete "See pricing for more details"

Thanks!

**Comment by YedidaZalik** [comment]
Hi @timarney sorry to bug you - The first part of Pricing got deleted when you removed the last line. Please add back in using same formatting as for sms:

**Pricing**
It’s free to send emails through Notification.

Thx!

**Comment by timarney** [comment]
@YedidaZalik 
Like this?
![Uploading Screen Shot 2019-07-30 at 3.08.17 PM.png…]()

**Comment by timarney** [comment]
https://github.com/cds-snc/notification-admin/pull/94

**Comment by YedidaZalik** [comment]
Great - thanks!
