### ISSUE TITLE
Content changes to text messages page https://notification.cdssandbox.xyz/features/sms

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-api#166]
**Page:**
- https://notification.cdssandbox.xyz/features/sms

**Please change:**
- in the first line, "UK" to "Canadian"
- second bullet, "personalise" to "personalize"
- under "Receive text messages, change "Let people" to "Users can"
- Change the heading "Show people who your texts are from"  to "Show people who sent your texts"
- In the the line above "Pricing"  please delete the words "from the default of GOVUK"
- Please delete the explanation under "Pricing' and replace with "Each service you set up has an annual allowance of 25,000 free text messages

Thanks!

**Comment by YedidaZalik** [comment]
Reviewed :)

**Comment by YedidaZalik** [comment]
Apologies @timarney 
 - I created a confusing heading. I see that now when I read it online. Can you please change "Show people who sent your texts" to "Show the sender of your texts"
- thanks and apologies again

**Comment by timarney** [comment]
@YedidaZalik 

Will be pushing up a PR with this:

<img width="682" alt="Screen Shot 2019-07-30 at 3 15 25 PM" src="https://user-images.githubusercontent.com/62242/62158195-e79ebd00-b2dc-11e9-8e35-0e45eaa1951d.png">

**Comment by timarney** [comment]
Updated in 
https://github.com/cds-snc/notification-admin/pull/94
