### ISSUE TITLE
Content change to About your service page https://notification.cdssandbox.xyz/add-service

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-api#167]
**Page:**
- https://notification.cdssandbox.xyz/add-service

**What?**
- Please hide question "Who runs this service?" as well as the buttons with options that are underneath the question

**Notes**
- The buttons only appear after you advance the page by clicking Add service. 
- Add service should advance to the next page without showing the radio buttons
- If you select a service name that is already is use the buttons will appear as well. 
- I have attached screen shots to show the current flow. 

![image](https://user-images.githubusercontent.com/46505127/62132188-9249b800-b2aa-11e9-933e-c0d0fe68243a.png)

![image](https://user-images.githubusercontent.com/46505127/62132313-d2a93600-b2aa-11e9-8b7b-f22fbc40f86e.png)

**Comment by timarney** [comment]
This was handled already.
![Screen Shot 2019-07-30 at 2 16 58 PM](https://user-images.githubusercontent.com/62242/62154544-ea95af80-b2d4-11e9-9b1f-b8e74cdaea2d.png)

**Comment by willeybryan** [comment]
Then bad news bears, this is a bug report. 

**Steps to reproduce:**
- Navigate to https://notification.cdssandbox.xyz/add-service
- Enter test as the name of your service

**Expected:**
- Service name is already in use

**Actual:**
- List of UK government designations appears

**Comment by timarney** [comment]
Yup will track down the bug.

**Comment by YedidaZalik** [comment]
I still get the "Who runs this service? and radio buttons" when I enter a service name.  @timarney @willeybryan Is that because of the bug?

**Comment by timarney** [comment]
https://github.com/cds-snc/notification-admin/pull/93

**Comment by timarney** [comment]
@YedidaZalik when you visit https://notification.cdssandbox.xyz/add-service prior to submitting a value that already exists?

**Comment by timarney** [comment]
@willeybryan should be fixed for both cases now 
https://notification.cdssandbox.xyz/add-service

**Comment by timarney** [comment]
<img width="548" alt="Screen Shot 2019-07-30 at 3 25 46 PM" src="https://user-images.githubusercontent.com/62242/62158831-63e5d000-b2de-11e9-9e7a-9c9d9e6c9e03.png">

**Comment by YedidaZalik** [comment]
Great !
