### ISSUE TITLE
Content Review: Email for when service is turned live

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#173]
**What?**
- Review content of email for when a service is turned live

**Why?**
- Needs to be updated for GoC

**Comment by willeybryan** [comment]
Copy and paste of body: Email was forwarded to Bryan and Yedida

Hi Tim Arney,AWS is now live on Notification.You can send up to 250,000 messages per day.As a live service, you’ll need to know who to contact if you have a question, or something goes wrong.To get email updates whenever there is a problem with Notification, it’s important that you subscribe to our system status page:https://status.notifications.service.gov.ukIf our system status page shows a problem, then we’ve been alerted and are working on it – you don’t need to contact us.Problems or questions during office hoursOur office hours are 9.30am to 5.30pm, Monday to Friday.To report a problem or ask a question, go to the support page:https://www.notifications.service.gov.uk/supportWe’ll reply within 30 minutes whether you’re reporting a problem or just asking a question.The team are also available to answer questions on the cross-government Slack channel:https://ukgovernmentdigital.slack.com/messages/govuk-notifyProblems or questions out of hoursWe offer out of hours support for emergencies.It’s only an emergency if:no one in your team can log ina ‘technical difficulties’ error appears when you try to upload a filea 500 response code appears when you try to send messages using the APIIf you have one of these emergencies, email details to:ooh-gov-uk-notify-support@digital.cabinet-office.gov.ukOnly use this email address for out of hours emergencies. Don’t share this address with people outside of your team.We’ll get back to you within 30 minutes and give you hourly updates until the problem’s fixed.For non-emergency problems or questions, use our support page and we’ll reply in office hours:https://www.notifications.service.gov.uk/supportEscalation for emergency problemsIf we haven’t acknowledged an emergency problem you’ve reported within 30 minutes and you need to know what’s happening, you can escalate to:orThanksNotification team | no one in your team can log ina ‘technical difficulties’ error appears when you try to upload a filea 500 response code appears when you try to send messages using the API
-- | --
no one in your team can log ina ‘technical difficulties’ error appears when you try to upload a filea 500 response code appears when you try to send messages using the API

**Comment by YedidaZalik** [comment]
Questions for @willeybryan 
- are we keeping the subscription section and changing it to a Canadian url?  Or just deleting that part for now?
- for the questions, problems, emergencies part: should that link to contact us page for now, and if so where is that page
-the support page is as follows: https://notification.cdssandbox.xyz/support
- I thought we had changed that or should I revise it to indicate there is limited support during this trial period?

**Comment by willeybryan** [comment]
-  If by subscription section you mean:

![image](https://user-images.githubusercontent.com/46505127/62544691-46f55380-b82e-11e9-91bc-1e20ed30a73d.png)

Then cut that, we don't have that yet and we won't for a while.

-  We aren't going to do emergencies. Feedback/issues/everything should, for now, all be directed to https://notification.cdssandbox.xyz/support/ask-question-give-feedback 

- We changed it to hide it. I want to direct all feedback to the above link.

**Comment by YedidaZalik** [comment]
Please replace the email with the following:

Hi Tim Arney,

AWS is now live on Notification.

You can send up to 250,000 messages per day.

If you have a question, or something goes wrong, please contact us [hyperlink to https://notification.cdssandbox.xyz/support/ask-question-give-feedback ]

We’ll reply as soon as possible.

Thank you from the Notification team.
