### ISSUE TITLE
Service Transaction: We need an official looking form that users can sign up to receive notifications from

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#176]
**What?**
- Make an HTML form that captures (Name and Email)
- Straight forward, Ideas: Contact your MP, Ask a question, Request a benefit
- ~~Call the form Apply for a Tax Benefit (Alternatively, fork CRA teams code as they should have all this)~~
- Have the form on a public-ally accessible URL
- Make it look official with government branding (Put a disclaimer at the bottom that this is for testing purposed only and isn't real)
- Put a check box at the end saying "Please notify me of updates with my application"
- If that box is checked: send them this notification 0b81be20-f93c-433c-9edb-cc04c33c576d
From this service e609f6b0-0390-45b0-aaae-f4cc92c713e4
(https://notification.cdssandbox.xyz/services/e609f6b0-0390-45b0-aaae-f4cc92c713e4/templates/0b81be20-f93c-433c-9edb-cc04c33c576d)

**Why?**
- Rudimentary demo of signing up to receive notifications. 

**Subtasks & Notes**
- Probably need a github repo for it
- need a form.cdssandbox.xyz type domain
- We will need to get it translated after, but lets get it up, then reviewed, then translated
- We can build the rest of a service around this and make it look real
- You could fork IRCC schedular, or the benefits finder instead, WE JUST NEED TO GET EMAIL AND NAME

**Comment by timarney** [comment]
I think forking the CRA demo makes the most sense as it light as far as tech and gives us form styling / layout for `free`.

I also see value there as we can demo sending from a CSV to a group of people where we give them an access code to login with - https://claim-tax-benefits.azurewebsites.net/login/code
 
People can `login` using the example provided or use the one we send them via notification.

<img width="498" alt="Screen Shot 2019-08-01 at 9 22 12 AM" src="https://user-images.githubusercontent.com/62242/62296857-ffda1d80-b43d-11e9-8fdb-b428d5be226a.png">

**Comment by timarney** [comment]
@willeybryan how do you want to proceed with this?

We haver a minimum setup now

-> Send access code via admin tool
-> Login via access code
-> Confirm name
-> Enter email
-> Receive notification

We can spend some time building out a proper login via maybe https://aws.amazon.com/cognito/

**Comment by willeybryan** [comment]
@timarney  I tried playing with https://claim-tax-benefits.azurewebsites.net/login/code and I couldn't get to the part to enter an email and get a notification.

Do I have to use a different access code than the one in the example?

I want to try and pad the other end. Testing users on login seems less valuable than putting an interaction in the notification that sends the user back into the system. Example: we could send them to a schedular for a tax consultation which notifies them again of their appointment they made.

**Comment by timarney** [comment]
Wrong URL.

**Comment by timarney** [comment]
The login just allows us to save info back as need be ... i.e. so can can identify the logged in user with whatever action / data they input.

Thinking we should meet (as a group) to pin down our use case scenario flow.

**Comment by timarney** [comment]
@willeybryan let's spin up a "fresh" issue based on the meeting today for this one.
