### ISSUE TITLE
Review/revise content text message page https://notification.cdssandbox.xyz/features/sms

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-api#177]
Will need to change:
- "You can also integrate" to "Your developers can also integrate"
- Show users that text message is from your service
When Notification sends your message, the text displays your service name. This shows users that the message is from your service.
Or we could change "user" to "recipient" but then then we need to use "recipients" in the first line under the heading "Receive text messages" but that will be awkward . . .
See suggestions from Anik on Slack and work on this some more
- Remove connection to Zendesk and replace with link to Contact Us form

**Comment by timarney** [comment]
@YedidaZalik 

Where did we end up for this?

>Or we could change "user" to "recipient" but then then we need to use "recipients" in the first line under the heading "Receive text messages" but that will be awkward . . .

> See suggestions from Anik on Slack and work on this some more

**Comment by YedidaZalik** [comment]
I'm still working on this

**Comment by YedidaZalik** [comment]
@timarney @willeybryan  please let me know how this reads as replacement for "Receive text messages" and "Show the sender of your texts" 

**Receive text messages**
You can let the public send messages to your service or reply to your texts.
You can see and reply to the messages you receive, or set up an automated process to manage replies.
Contact us to request a unique number for text message replies.
**Display your sender name**
When Notification sends your message, the text displays your service name. This shows people that the message is from your service.
You can change the text message sender name in your service settings.

**Comment by willeybryan** [comment]
Lets leave out "You can let the public send messages to your service or reply to your texts." 
I don't think we can offer that right now. 

In fact the page looks like this: https://notification.cdssandbox.xyz/services/142de8b0-7555-4df9-aca5-f64ca998aa62/service-settings/set-inbound-sms

But I don't know how we could set something like that up in canada.

**Comment by YedidaZalik** [comment]
okay, it reads fine without that line as far as I can see. So if the rest is fine and @timarney agrees, then the rest of this change can be made.

**Comment by timarney** [comment]
@maxneuvians hid the inbound message links yesterday.

If you can summarize the updates that would be helpful.

**Comment by YedidaZalik** [comment]
Before summarizing, question to @willeybryan  - we removed "You can let the public send messages to your service or reply to your texts."  That's still leaves the following heading and lines, which now may lack context. Can we remove this whole section, or should we keep some info about this functionality?

**Receive text messages**
You can see and reply to the messages you receive, or set up an automated process to manage replies.
Contact us to request a unique number for text message replies.

**Comment by willeybryan** [comment]
Yeah,
I want the whole thing gone. I don't want to have to worry about text message receipt yet. 
"Receive text messages
You can see and reply to the messages you receive, or set up an automated process to manage replies.
Contact us to request a unique number for text message replies."

**Comment by YedidaZalik** [comment]
So summary of changes is to please leave the first part of the page as is, but remove everything else starting with "Receive text messages" and replace with the following:

**Display your sender name**
When Notification sends your message, the text displays your service name. This shows people that the message is from your service.
You can change the text message sender name in your service settings.

**Pricing**
You can send 25,000 free text messages per year from each service you create.
