### ISSUE TITLE
Identify on the user interface where we are showing time

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#181]
**What?**
- Document all the spots in the UI where time zones are pulled in

**Why?**
- We need to change that on #118 to dynamic

**Comment by maxneuvians** [comment]
So far found in:

Dashboard
Notification detail page
API page
Report page

**Comment by willeybryan** [comment]
Sent page right after sending https://notification.cdssandbox.xyz/services/cb9c86a3-d62f-4e87-bcb7-89f6e660365d/notification/1c8b5d82-dbdb-4bce-a862-c3dd57a7b5ae?help=0

Don't know if that is different than dashboard because the navigation places me in dashboard

**Comment by maxneuvians** [comment]
Found most of the items be searching for the date formatters
