### ISSUE TITLE
Fix a selection of Broken tests, Admin, Api, and Utils

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#198]
Ticket that broke the tests: https://github.com/cds-snc/notification-api/issues/181

Related to https://github.com/cds-snc/notification-api/issues/118

**What?**
- Fix tests in API
- Fix tests in Admin
- Fix test in Utils

**Why?**
- We need tests to run

**Notes**
- If you wanted to refactor the tests while there to make them less brittle that would be a good use of time.
- Let me know if we should split this into 3 issues

**Comment by maxneuvians** [comment]
Fixed utils in https://github.com/cds-snc/notification-utils/pull/17
