### ISSUE TITLE
When using our copy of the notify repo we should connect it to our github actions/apps so we can automate as much testing as we can

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#2]
**What?**
- Figure out what Github actions we can apply to the repos
- What actions we should
- Then apply them

**Why?**
- Test our own tech and ensure we don't make little mistakes.

**Comment by maxneuvians** [comment]
All repos now have CI/CD

https://github.com/cds-snc/notification-utils/pull/2
https://github.com/cds-snc/notification-api/pull/75
https://github.com/cds-snc/notification-admin/pull/8
