### ISSUE TITLE
To be FIP compliant we should ensure that when GoC sends notifications that we include the Canada Logo

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#20]
**What?**
- compliance with https://en.wikipedia.org/wiki/Federal_Identity_Program
- Electronic Communications need to be signed with Canada Logo
- Replace the Gov.UK notify branding with our branding

**Why?**
- Requiring images means requiring attachments which means working to support that for GoC users specifically

**Comment by timarney** [comment]
Updated the admin with some initial branding.  

This does not include the emails.

**Comment by willeybryan** [comment]
![fip banner](https://user-images.githubusercontent.com/46505127/60816138-09d26e80-a167-11e9-9aae-cd06f2fdae5e.gif)

This should be at the bottom of messages

**Comment by timarney** [comment]
@willeybryan @sboots - 

Email template - 

Add flag (Gov of Canada) left + Wordmark right to the bottom only nothing at the top or?

**Comment by willeybryan** [comment]
I know I said bottom, but I am not sure where I got that from. Top might be fine/preferred.

**Comment by timarney** [comment]
This seems to overlap with https://github.com/cds-snc/notification-api/issues/39

**Comment by willeybryan** [comment]
Yeah, oops. It does, if #39 is done we should be good enough for now. 
Did we also update the from address as seen on #59 ? 
My two factor emails still are all Gov.uk'ed up. Is that a separate template?

**Comment by timarney** [comment]
The branding is updated so we're covered there.  

There's a bunch of DB migrations + a few others pieces that will happen when we spin up a fresh database.  Until than you will get the "old" branding + UK content in the emails.

**Comment by willeybryan** [comment]
Including Email content? Works for me. I will close This and #59 based on that advice as it seems to have done everything.
