### ISSUE TITLE
Content addition to Terms of Use https://notification.cdssandbox.xyz/features/terms

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-api#204]
**page:** https://notification.cdssandbox.xyz/features/terms

Purpose: to provide context for GOV.UK style manual:

Possible replacement for first paragraph under the heading "When using Notification" - @timarney @willeybryan please advise whether you think this helps and/or what else is missing:

Consider when to send emails or text messages and how to write them. You can read more about this in the GOV.UK Service Manual [hyperlink to writing text messages and emails]. 

GOV.UK developed the original notification system. Canada’s Notification team recommends following the UK guide, while adjusting for the Canadian context.

**Comment by willeybryan** [comment]
This works for me
