### ISSUE TITLE
Translation button starts on English when it should start on Français (My browser is english)

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#205]
**Steps to Repro**
- In an incognito window navigate to notification.cdssandbox.xyz
- Look at the top bar see English
- Click English

**Expected**
- Button should say Français and change me to Français
- The button should then change to english, and if clicked again go back to english

**Actual**
- Button says english
- Click the button and it says english
- Click the button again and it says Français while the page content is english (This is the good state)

**Comment by timarney** [comment]
@brdunfield - I have a fix for this in place ... while I was working on the JavaScript translation scripts.

**Comment by brdunfield** [comment]
Sounds good, I'll jump on something else!
