### ISSUE TITLE
We need to figure out how attachments can work

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#207]
**Background**
- After exploring government use cases we have found that people want to attach things. Like PDF copies of forms or letters they would otherwise send via letter mail
- While they could just create this stuff in an email template, that presents a barrier to adoption since they already have this PDF copy. To change the policy and process to send new copy would take longer than adopting the software
- Attachments remove this blocker by allowing users to attach links
- I think we already have an S3 bucket for attachment files

**What we need to know?**
- If a platform admin goes to a service and selects uploading documents they get this page: https://notification.cdssandbox.xyz/services/cb9c86a3-d62f-4e87-bcb7-89f6e660365d/service-settings/can-upload-document
- With that page in mind do we need to build a document download service?
- Would could a document upload/download companion to Notification look like? (https://send.firefox.com/    https://github.com/mozilla/send)
- The API Documentation explains that they just send a link and you can upload a 2mb or less PDF file only. Is this arbitrary or does Notify have something to do with this limit?
- Where and how would the user upload a file? Is it API only?
- Can we do different files per user with the variable?

**Expected Output**
- To do list of Dev tasks to make attachments work.
- list of technical Blockers to making attachments work.
- Select a solution for our upload

**Notes**
- More background on the IRCC specific use case can be found here https://docs.google.com/document/d/1wIQULlrNew93CKAWIkQRHOtU0mSGl9gX7jICg7kBxaE/edit#heading=h.rnau9cvd9odw
- platform admin service specific page in question 
![image](https://user-images.githubusercontent.com/46505127/62626330-1fb58980-b8f5-11e9-9ced-661b2de16f7d.png)

- GraphQL upload could be helpful https://github.com/jaydenseric/graphql-upload
- This uploader written by Dave might be useful https://github.com/cds-snc/cppd-doc-uploader
- From API documentation 
"Send files without the need for email attachments.

This is an invitation-only feature. Contact the GOV.UK Notify team to enable this function for your service.

To send a file by email, add a placeholder field to the template then upload a file. The placeholder field will contain a secure link to download the file.

"Download your file at: ((link_to_document))""

**Comment by maxneuvians** [comment]
We need to talk to @obrien-j about scanning attachments for malware

**Comment by willeybryan** [comment]
Yeah I made a ticket for that https://github.com/cds-snc/notification-api/issues/211, but can't we just pick one ourselves or ask @damcom333 ?

**Comment by timarney** [comment]
Noting this from the API:

https://docs.notifications.service.gov.uk/node.html#add-a-placeholder-field-to-the-template

https://docs.notifications.service.gov.uk/node.html#upload-your-file

**Comment by maxneuvians** [comment]
I have asked for access to mlwr.ca which is the CSE tool for malware scanning. 

I have also found https://github.com/alphagov/document-download-frontend and https://github.com/alphagov/document-download-api which are the applications that handle uploading files to a S3 bucket.

The current functionality is that people create templates with links to files ex: `((my_cool_file))` and then using the API client specify a file to be uploaded with the notification. The currently exists no way to send a file from a the UI. We need to discuss in planning if we want to prove this out and if we want to add the UI for uploading from admin.

**Comment by maxneuvians** [comment]
API (https://github.com/cds-snc/notification-document-download-api) is running

**Comment by maxneuvians** [comment]
This is more or less functional ex: https://document.notification.alpha.canada.ca/d/5gn2sAOQRbCqrvTMkscT5A/nam5x8KBRoCmpEPEAK2Jgg?key=np2ViKWzWU44tLvNa4P0nFoXaJFLGkv2agAZbC4NG2E

I am going to break up the remaining issues so that we can address them one by one

**Comment by maxneuvians** [comment]
Only thing left to figure out is if we want a UI component to allow attachments through the admin section
