### ISSUE TITLE
Uploads should be scanned for Viruses

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#211]
**What?**
- Select a Virus scan that can run on stuff uploaded to S3 Buckets
- Make it run on all CSV uploads at first
- Test to make sure they still work

**Why?**
-  We will need it for people uploading attachments to sister attachment service
- .CSV files is all people can upload on trial modes and such

**Comment by maxneuvians** [comment]
Still waiting on approval from mlwr.ca

**Comment by maxneuvians** [comment]
Received approval and tested out the API which looks like it works well. The big difference is that this service is async. You send up your file, the server tells you it is in a queue, and then you query until the file is processed. The UK code uses a sync version where you upload the file and then the wait till the server scans it and sends a response back to you.

Making the existing code async will require time. Also we need to verify the level of confidentiality of files we can upload to mlwr.ca. As a result we should prove out the upload file use case.
