### ISSUE TITLE
Scheduling a Notification in the UI is a terrible UX and needs updating

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#217]
**Steps to Reproduce/Find:**
- Here is my instance of it https://notification.cdssandbox.xyz/services/cb9c86a3-d62f-4e87-bcb7-89f6e660365d/07054a05-2a6b-4d42-9aa5-3969ed61b655/check/05b15507-e56d-4986-ba20-3f5f61927171?original_file_name=2+person+test.csvoriginal_file_name=Bulk+send+test+sheet+-+Sheet1.csv
- To replicate, go to send an email message to a CSV list of people
- After you upload the list you will be taken a page to send the emails
- If you click here to pick a date and time to send the message you will begin to see the issues

**Current Behaviour:**
- I have to click a button for a day, like Today, or Tomorrow
- Saturday shows up as just the Letter S (Bug?)
-Once I have clicked a button, such as Tomorrow. I get 24 radio buttons to select the hour of the day
- To cancel I must scroll to the bottom of the radio buttons and select done (Should probably say cancel)
- If I select a time it collapses and saves the time, jumping the page around.
- Can't navigate it with a keyboard, just skips over time selection.

**Desired Behaviour:**
- We want an accessible date picker alternative
- Must be accessible (Can't jump page around, won't cause a screen reader to read 24 lines of hours, Keyboard navigable, Shows the date and time clearly after setting it, Shows the Time zone you are setting this in) 
- Preferably some sort of Calendar and time input that lets a user set the date and hour of day that fits onto the page without expanding it
- 2 radio buttons, Now as a default option. Second radio button gives you the Calendar input
- Probably want to Find a calendar date picker/schedular from some where that we can use rather than making our own. 
- Don't let user actually set a time zone, just reflect the time zone they are in. 

**Why?**
- The UX of scheduling a notification is garbage and if people start using for the use cases we have found this they will interact with that and it won't reflect well on the software. 
- Accessibility is blocked by this

**Notes:**
Current behaviour:
![image](https://user-images.githubusercontent.com/46505127/62715606-d5a0d680-b9ce-11e9-8991-afe547cfaa55.png)

After clicking a button:
![image](https://user-images.githubusercontent.com/46505127/62715629-e18c9880-b9ce-11e9-95bd-4b84de976d5b.png)

Mockup of what I am thinking:
![image](https://user-images.githubusercontent.com/46505127/62716528-4a284500-b9d0-11e9-8b51-8c167067a7aa.png)

Mockup After clicking Date button:
![image](https://user-images.githubusercontent.com/46505127/62716784-b86d0780-b9d0-11e9-8bfd-f73f5e86cc8c.png)
Stolen from Google Calendar, so I imagine final version will look vastly different

**Notes**
UX audit Slide 9 https://docs.google.com/presentation/d/1IqcsdBF2I4bvKEwOhRHr3bHCaHQN0JKcWo8FG43Rxuc/edit#slide=id.g5f7f6f0ada_0_9

**Comment by willeybryan** [comment]
@AntoineGarciaSuarez I am proposing an UX change here, while we don't have any direct research to support this with users. The current interface is, not accessible. I was wondering if I could get your opinion on these changes. Do you think they are a good idea?

**Comment by AntoineGarciaSuarez** [comment]
Hi bryan, great idea. I spotted severals UX and UI issues. Here is what I'm suggesting. In parallel of the recruitement, I could identify on each page of the product usabilities issues and categorize them. Then, with the user's insight, we will be able to prioritize them and suggest design solution. I could begin that during the current sprint. What do you think?

**Comment by willeybryan** [comment]
Julianna Recommends https://www.24a11y.com/2018/a-new-day-making-a-better-calendar/

**Comment by timarney** [comment]
Simplified the interface down to a day select and an hour input.

![screenshot_from_2019-08-21_14-25-41](https://user-images.githubusercontent.com/62242/63457822-ac953280-c41f-11e9-99bc-03b0d2f8fbf0.png)

After doing some research into accessible day pickers decided against going that route for now.

> Complex widgets like date pickers are really easy to get wrong; in fact, something working beautifully for some users may present barriers for others. Custom widgets require thorough testing to get right, especially on Windows and mobile screen readers due to their high usage by people with disabilities. You’ll often hear accessibility professionals recommend using native HTML elements first. The unfortunate thing, however, is those browser defaults aren’t always accessible, either…and our best bet is to come up with standard solutions that can be shared and implemented in various JavaScript projects. Accessible component libraries and guides are really helpful here.

https://a11ywins.tumblr.com/post/182992115383/aria-authoring-practices-on-accessible-date

It's likely we will end up building "something" possibly based on https://unfetteredthoughts.net/a11y/calendar/calendar.html in the future in which case we can come back to this as need be.

**Comment by timarney** [comment]
Also tons of great info here

https://www.drupal.org/project/drupal/issues/3072906

>Problem 1: jQueryUI is going to be deprecated
As part of this deprecation, the jQueryUI datepicker is among the components that need to be removed/replaced.

<hr>

>I'm honestly shocked and appalled that accessibility of native datepickers is so incredibly bad 😨 And I did not realize that we only used jQuery UI's datepicker only on browsers that do not support the native datepicker, meaning that 91% of users (who then use a native datepicker) are subjected to this horrible accessibility! 😔

<hr>

>We need to consider the realistic option of dropping the DatePicker design pattern. Some of these widgets that jQuery UI incorporates like the Accordion and Tabs are real design patterns: https://www.w3.org/TR/wai-aria-practices-1.1/#aria_ex - And that's great. However, the calendar pattern is not on there. That's alarming.

>We can tell from the features of the calendar that this was not designed inclusively and it was not well tested against assistive technologies.

<hr>

>The main a11y consensus is that date fields are best treated as text fields that permit a user to type in. The required format can be conveyed with a visible description and aria-describedby.

> A fancy date-picker widget can be available too, but best practice is that users should not be forced to use it.

<hr>

> Spent some time on the react-dates prototype, but it's definitely not complete. Continuing would require a nontrivial amount of additional work so I'm going to pause for now and share some of my observations. Perhaps that will help determine if it's worth devoting additional work to this option:

**Comment by timarney** [comment]
>I'd always say that datepickers are an a11y nightmare, a usability nightmare, and a development timesink. They CAN be done well, but the above three things always seem to cancel out their usefulness.
https://twitter.com/sonniesedge/status/1161988837700190208

**Comment by timarney** [comment]
Just use a text input ->
>Let’s face it — there are no properly accessible date picker components available, and even if there were, they would be hard to navigate due to the screenreader ...

https://twitter.com/timarney/status/1161963910536339457

**Comment by timarney** [comment]
"Designing The Perfect Date And Time Picker"

See this for a bunch of use cases:

https://www.smashingmagazine.com/2017/07/designing-perfect-date-time-picker/

**Comment by timarney** [comment]
Here's the https://wet-boew.github.io/v4.0-ci/demos/datepicker/datepicker-en.html

All the above to say -

> "It's complicated"

**Comment by timarney** [comment]
@willeybryan flagging this from the RCMP repo as it relates to the "Date Picker" topic

https://github.com/cds-snc/report-a-cybercrime/issues/712
