### ISSUE TITLE
Enhance two factor options with  Fido U2F support

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#221]
**What?**
- Existing two factor options include email link or SMS, both of which we believe to be less secure than a Yubikey
- Label all UI elements that refer to Yubikey as Security Key so we don't have branding
- Add an entry in users profile to configure a Yubikey(Security Key) here https://notification.cdssandbox.xyz/user-profile
- Update user options to support sign in with a users Yubikey(Security Key) (IF they have one configured, otherwise leave the selection greyed out, alt text over the radio button specifying they have not configured a Security Key) here https://notification.cdssandbox.xyz/services/cb9c86a3-d62f-4e87-bcb7-89f6e660365d/users/6e4362f5-b547-4dde-b330-10aff4b4887a
- Update Sign-in method page to note Yubikeys(Security Keys) are an option here https://notification.cdssandbox.xyz/services/cb9c86a3-d62f-4e87-bcb7-89f6e660365d/service-settings/set-auth-type

**Why?**
- We think there is value in demoing Yubikeys as a higher security option back to GDS and DTA
- Yubikeys are required for CDS Gmail accounts, and as CDS is acting as the platfrom admin of this service we should ensure that we have the same level of security as our gmail accounts since they have similar risks incase of being compromised.

**Comment by maxneuvians** [comment]
API part here: https://github.com/cds-snc/notification-api/pull/226

**Comment by willeybryan** [comment]
I am not seeing: 

- Update user options to support sign in with a users Yubikey(Security Key) (IF they have one configured, otherwise leave the selection greyed out, alt text over the radio button specifying they have not configured a Security Key) here https://notification.cdssandbox.xyz/services/cb9c86a3-d62f-4e87-bcb7-89f6e660365d/users/6e4362f5-b547-4dde-b330-10aff4b4887a

- Update Sign-in method page to note Yubikeys(Security Keys) are an option here https://notification.cdssandbox.xyz/services/cb9c86a3-d62f-4e87-bcb7-89f6e660365d/service-settings/set-auth-type

Plus we should also update the team list as it ways signs in with text message code when we are using two factor
![image](https://user-images.githubusercontent.com/46505127/63030814-f78fd280-be80-11e9-8c7e-365f14819d83.png)

And I think a User should be able to change their two factor method themselves here https://notification.alpha.canada.ca/user-profile

And lastly, when I added my Security Key I didn't get an email that my profile had changed, which it should, like any other profile changes.

**Comment by maxneuvians** [comment]
Email notification fixed in https://github.com/cds-snc/notification-api/pull/249

**Comment by maxneuvians** [comment]
Agreed on the UI fix - I think we need to talk to @damcom333 if you should be able to turn off Fido2 if you have it (reason: we can't for all our other SaaS)

**Comment by maxneuvians** [comment]
Fixed the UI here https://github.com/cds-snc/notification-admin/pull/160
