### ISSUE TITLE
Content for privacy page during testing

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/notification-api#223]
**Page** https://notification.cdssandbox.xyz/privacy

Content change:

**Privacy**
GOV.UK developed the original notification system (hyperlink to UK github repo) and its UK privacy protections (hyperlink to UK privacy page under "privacy protections").
 
The Notification team is reviewing privacy for Canada’s system.  Please tell us about your privacy needs (hyperlink to feedback page under “tell us about your privacy needs”).

**Notes**
Hi @sboots  - @damcom333 pointed out that we need conditional wording for security and privacy pages, until we have verified that our security and privacy statements are accurate for Notification. 
Can you please let us know if this will work for the privacy page?

**Comment by willeybryan** [comment]
Yeah this is fine for now. Let's see what Sean says. I pinged him on slack.

**Comment by sboots** [comment]
Thanks @YedidaZalik and @willeybryan !

I'd say, sounds great for the first line but I'd change the second line to (for example),

> The Notification team is currently reviewing privacy requirements under the Privacy Act (link to https://laws-lois.justice.gc.ca/eng/acts/P-21/index.html). If you have specific privacy needs for your service, please let us know (link to feedback page).

When we have more details back from TBS ATIP, we may need to update this again. This sounds good for the moment though!

**Comment by willeybryan** [comment]
Any ETA on the deets from TBS ATIP?

**Comment by sboots** [comment]
Not yet! Sent them the "pre-PIA checklist" yesterday and Miranda emailed back saying they'd review it shortly. I'll keep you both posted!

**Comment by YedidaZalik** [comment]
Okay, so please replace the privacy page content with the following (some edits from Sean and some from me):

**Privacy**

GOV.UK developed the original notification system (hyperlink to UK github repo) and its UK privacy protections (hyperlink to UK privacy page under "privacy protections").

The Notification team is reviewing privacy requirements under the Privacy Act (link to https://laws-lois.justice.gc.ca/eng/acts/P-21/index.html). If your service has specific privacy needs, please let us know (link to feedback page).

**Comment by YedidaZalik** [comment]
@willeybryan the alignment of the paragraphs on the privacy page makes it a bit difficult to read (lines are too long). Can we please change it to similar margins as on the security page?

**Comment by willeybryan** [comment]
The privacy page just doesn't seem to have a side navigation to indent it. It expands to fill the width of the page by design, and that will change if your screen size changes. EG Smart phone screens the line will look different. It is actually an annoying idea to change that.
