### ISSUE TITLE
Rename Notification Demo Service to Passport Renewal Notification Demo

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#234]
When going through the process of signing up for notifications, we want the recipient to follow a real world use case, to ensure that we get the best usability testing data we can, to allow us to better figure out what kind of information a recipient wants. 

**ref** https://notification-demo-app.herokuapp.com/start

**What?**
- Rename app to Passport Renewal Notification Demo
- Change front page to match mockup

**Stretch Goals**
- Captcha or token in URL that gets sent to recipient to confirm to prevent bots from abusing the system

**Why?**
- We want a real world demo people can relate to, passports are something most people understand or can relate to things like drivers licences, health cards, etc. 

**Notes**
Mockup 
![image](https://user-images.githubusercontent.com/46505127/62964754-a4127b80-bdd1-11e9-9670-c6b099e9967c.png)

**Comment by timarney** [comment]
Updated.

We can loot at the "strech goals" separately.
