### ISSUE TITLE
Notification demo service should capture passport number or equivalent

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#235]
When subscribing for a passport expiry reminder, it is important to enter one's passport number to give a sense that the system knows who you are and establish trust with the recipient of the notifications. 

**ref** https://notification-demo-app.herokuapp.com/login/code
**Dependancy** https://github.com/cds-snc/notification-api/issues/234
- May not be needed or check the user if stretch goal was met

**What?**
- Change page to match mockup and let a user enter in a passport number

**Why?**
- Gives a sense of realism with the system like it will actually get information on the user

**Notes**
Mockup
![image](https://user-images.githubusercontent.com/46505127/62965279-acb78180-bdd2-11e9-9414-88190936655c.png)

**Comment by timarney** [comment]
Updated.
