### ISSUE TITLE
Notification demo should capture the information relevant to a passport expiry reminder

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#236]
When a recipient signs up to receive a notification we need to capture the information to go through the rest of the process. So that we can have them go through the rest of the process

**Ref** https://notification-demo-app.herokuapp.com/personal/name

**What?**
- Update form to capture Name, email, expiry date, and consent as per mockup
- Include token we can identify the user with if we need them to click a link in the email
- Continuing on this page should send a confirmation email from the templates created on https://github.com/cds-snc/notification-api/issues/237
- Feel free to leave the confirmation page after this alone, it can still display the thank you and confirmation number. 

**Why?**
- We will send this information in an email back to the user to confirm their subscription

**Notes**
Mockup
![image](https://user-images.githubusercontent.com/46505127/62966037-2e5bdf00-bdd4-11e9-87f7-b61398905807.png)

**Comment by timarney** [comment]
Done to the point where it will get the user info -> send an email -> send to confirm page...

Will pick up setting up a new template etc... for it to send to in #237
