### ISSUE TITLE
Create 3 new templates in the CDS ORG in Notification to send out as part of Passport service

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#237]
When a recipient walks through the demo process we want them to get notifications so we can test their reactions and understanding.

**Ref:** https://notification.cdssandbox.xyz/services/e609f6b0-0390-45b0-aaae-f4cc92c713e4/templates/all/folders/b3519e26-e60a-4651-aa4e-060493c44259

**What?**
- Create some templates for the folder in the Ref above

1. A template that confirms you requested notifications to this email from https://github.com/cds-snc/notification-api/issues/236 with a link back to the demo to confirm it. (avoid including info the user submitted)
2. A template that confirms you will receive a notification at some future date based on passport expiry -6 months. This confirms the users email is live and they accept the notifications. 
3. A template for the actual expiring somehow directing people to their nearest passport office. (Could use a link out to a map or page in service)

- Have team review templates
- Send templates for translation https://docs.google.com/document/d/1tXvuJlF2n33KzwiihUTgJNrSmRcTMPaoS1WoGap41-M/edit

**Why?**
- We want to create the look and feel of a real passport renewal service
- Notifications need to be available in both official languages

**Comment by timarney** [comment]
1st template starter is here: https://notification.alpha.canada.ca/services/e609f6b0-0390-45b0-aaae-f4cc92c713e4/templates/fc3bc882-2154-4b0e-93be-c503df70690a
