### ISSUE TITLE
Confirmation email needs pages to link to in the passport demo

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#238]
When we send a confirmation email to a user for submitting information we want the recipient to click a link to confirm the email is active and typed correctly. 

**What?**
- First New Passport demo page
- User click confirm in an email they are send, email has unique token that shows the users info in the browser again, with a thank you for confirming message
- Once Confirmed we want to send them template 2 from https://github.com/cds-snc/notification-api/issues/237
- Second new page - Move the user to a new page explaining thank you for signing up
- Have Include a 'Reminder review' or similar button to send the actual reminder notification so the user doesn't have to wait years. This sends them template 3 from https://github.com/cds-snc/notification-api/issues/237

**Why?**
- Creates a real confirmation page
- lets us fast track the users notification
- User is confident they will receive notification

**Comment by timarney** [comment]
@brdunfield @maxneuvians if one of you want to pick up on the other part of this one that would be great.  

```
Have Include a 'Reminder review' or similar button to send the actual reminder notification so the user doesn't have to wait years. This sends them template 3 from #237
```

I have a good chunk of the steps leading up to + sending the confirm mostly in place.

Potentially we might want to save the data to Air Table or something as well.

**Comment by timarney** [comment]
Talked to @maxneuvians I'll pick up the rest of this .... 

After the confirm screen will link to a "move forward in time" screen which will send the reminder.

**Comment by timarney** [comment]
Templates are here:
https://github.com/cds-snc/notification-api/issues/237

**Comment by timarney** [comment]
Going to close this one and setup fresh tickets as we need them based on @AntoineGarciaSuarez testing plans.

Confirm and Remind pages + emails are in place on the demo app.
