### ISSUE TITLE
Connect Notify to the CDS Dashboard system for Policy to monitor

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#243]
When reviewing the adoption of notify and how much it is being used, letting CDS see it's key metrics on a dashboard would be a big help, so that people don't have to go to multiple places

**What?**
- Remember this dashboard? https://cds-dashboard-ui.netlify.com/cost/?en
- Create a new Tab For notify
- Show how many services there are (Numbers: Trial, Live)
- Show how many notifications have been sent (Numbers: Email, and SMS)
- Show total cost of hosting number
- Show total cost of sending messages

**Why?**
- Lets policy track key metrics
- Lets Product update explainer summary
- Lets people demo the value easier

**Comment by maxneuvians** [comment]
https://cds-dashboard-ui.netlify.com/notification?en
