### ISSUE TITLE
Prepare Demo app copy and content for translation

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#252]
Dependency : https://github.com/cds-snc/notification-api/issues/250

**What?**
- Ensure text from demo app can be gathered into one file and translated
- Wrap text in translation tech as needed
- Link this ticket to the file in Github

**Stretch Goal**
- Send for translation https://docs.google.com/document/d/1tXvuJlF2n33KzwiihUTgJNrSmRcTMPaoS1WoGap41-M/edit

**Why?**
- We will be usability testing with French speakers

**Comment by willeybryan** [comment]
Files to be found here https://github.com/cds-snc/notification-demo-service/tree/master/locales

**Comment by timarney** [comment]
Closing this as we're covered off the the "what" part now.
