### ISSUE TITLE
Documentation for Developers needed

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#255]
**What?**
- Document how to deploy all the necessary repos locally for our own developers
- Ensure that some one forking our work has the information to stand up their own copy
- Update Read-me's with this information
- Add FAQ section based on 'Bethany's Common Gotchas'
- Trouble shooting

**Why?**
- If developers change out of the team they need to be able to build the software
- If some one forks the code base they need to be able to build it with little help from us.

**Comment by timarney** [comment]
@brdunfield anything to note here?

**Comment by brdunfield** [comment]
The 2 biggest ones were:
- to more clearly document how to update requirements after pulling in master (initially the current documentation leads you to believe that you have to redo the freeze-requirements.txt if I remember correctly)
- Documentation on setting up / connecting to the local db and how / when to drop local databases to fix issues.

Additionally, the command I'm using to run celery on the api:
`celery -A run_celery.notify_celery worker --pidfile="/tmp/celery.pid" --loglevel=INFO --concurrency=4`
Is not documented anywhere. I'm not sure if the celery documentation in the readme is accurate or why the command I was told to use differs from it.

We're also missing a lot of documentation for the document downloader, but I'm not sure if that is in the scope of this issue.

**Comment by timarney** [comment]
For Celery I was using the command from the Readme and it seemed fine.  @maxneuvians ? 
https://github.com/cds-snc/notification-api#to-run-the-queues

Document downloader wasn't on the radar yet (but yes will need something).
