### ISSUE TITLE
I can't seem to update my password

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#278]
**Steps to Reproduce**
- Attempt to log in
- Says my password is wrong
- Select forgot my password
- Follow the reset link
- Select a new password
- Login and navigate to my user profile (https://notification.alpha.canada.ca/user-profile)
- Read: Password last changed 46 days ago (Strange, I thought I just changed it with forgot password)
- Click Change next to password
- Enter old password (That I just set in forgot password step)
- Enter new password

**Expected**
- Forgot password updates password last changed
- Changing my password should work and recognize the password I just set

**Actual**
- Error: 'Invalid Password'
- Password last updated 46 days ago
- Can't change my password
- I get a Text message confirmation code and I have to use my Yubikey

**Notes**
- If I enter in my old password, from 46 days ago into the Change password field i get the error: 'Choose a password that’s harder to guess'
![image](https://user-images.githubusercontent.com/46505127/63793723-4b150e00-c8ce-11e9-8d8a-8ac05d5c7fe1.png)

**Comment by maxneuvians** [comment]
Can't replicate - this is what I did:

- Log in
- Change password through change password in account functionality
- Password says, change just now

- Log out
- Log in with new password
- Password says, changed a minute ago

- Log out
- Click reset password
- Change password
- Log in 
- Password says, changed just now

**Comment by willeybryan** [comment]
Yeah, I guess it only impacts me. Blarg.

**Comment by willeybryan** [comment]
Every time I 'change' my password it sends me a text message code :|
