### ISSUE TITLE
When building Prototypes a Boiler plate would help get them off the ground faster

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#290]
**Story**
We are building demo apps to test with and stripping the CRA demo down each time, we need a stripped down functional boiler plate to save us that time.

**What?**
- Boilerplate repo of some sort that is built on the CRA app
- Keep Accessibility built in
- Make it easy to build forms in the app
- Connect to CI/CD
- Include tests for TTD
- Document how to fork it and stand it up on our GCP so that anyone at CDS can do it easily in Github Readme
- Ensure that forks can easily get package updates for security reasons

**Stretch Goal:**
- Can we avoid using PUG because it is hard to adopt developing in

**Why?**
- We duplicate work every time we need to make a new application that sends forms, we have a CRA demo that we know is good enough and we should capitalize on that

**Comment by timarney** [comment]
Going to move this to "done" and can iterate as we go. 

Current setup deploys to Heroku and I also setup a Google Cloud Build file + tested it using Google Cloud Run.
