### ISSUE TITLE
Prepare Database Migration for Templates so that Bilingual Templates are available at deploy of code

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#291]
- Dependency https://github.com/cds-snc/notification-api/issues/252

**What?**
- When a new notify gets setup with our code we need it to pull the french too
- Database migration scripts need to include this

**Why?**
- Development said it is important
- Future proofing our open source project.

**Comment by timarney** [comment]
This is prone to get out of sync if done using migrations.

If any of the templates are updated via the admin after the migrations are run the migrations won't contain the latest.  The database is the real source of truth.

**Comment by timarney** [comment]
Closing this - 

We will pull the latest template content from the existing database or backup of the database vs trying to keep the migrations in sync.
