### ISSUE TITLE
Fake pay your passport fees owed demo app

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#296]
Dependancy #290
Dependancy2 #319   

**What?**
- Using our boiler plate create a fake app that collects peoples payment data on their fee for passport application
- Collect name, email, phone number, Fake passport number
- Collect fake Credit card data (Drop down Visa/MC/Amex, number, exp date, CCV)
- Sends confirmation text or email based on user selection confirming payment
- Star out (***) fake info in confirmation email
- Include rough french in email

**Why?**
- App portfolio demo to GoC execs to show off what we can do
- Notify usability testing

**Comment by timarney** [comment]
Added a repo here - https://github.com/cds-snc/notification-demo-service-fees

**Comment by timarney** [comment]
If someone wants to create the template Ids + text overall for this i.e. the confirmation page that would be great until then I'll put this on hold.

**Comment by willeybryan** [comment]
Sounds good I will process that
