### ISSUE TITLE
Passport Demo Update for usability research

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#302]
**What?**
- Create a hidden interface in the passport demo for Research to use to send notifications for steps
- Send notification for Your application is being processed, We have received your passport please come and pick it up,
- On come in to pick it up can the email link to the schedule an appointment to come in and pick it up from #295

**Why?**
- More relevant user testing data

**Comment by timarney** [comment]
@willeybryan @AntoineGarciaSuarez if you can create templates and add the templates IDs back to the issue we can get this rolling.

**Comment by willeybryan** [comment]
I didn't use the priority queue for either of these, don't know if that matters.

Your application is being processed 1dcbfac6-6e46-4b1f-a2e4-be5f22698c8d
Passport ready for pickup 4b91332a-0356-4e9b-adea-ba42cead6216

Processed (https://notification.alpha.canada.ca/services/e609f6b0-0390-45b0-aaae-f4cc92c713e4/templates/1dcbfac6-6e46-4b1f-a2e4-be5f22698c8d)
Ready (https://notification.alpha.canada.ca/services/e609f6b0-0390-45b0-aaae-f4cc92c713e4/templates/4b91332a-0356-4e9b-adea-ba42cead6216)

@AntoineGarciaSuarez You may want to review and edit my french translations which are probably dubious at best.
