### ISSUE TITLE
Implement our new and improved homepage

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#306]
**What?**
- Implement our new redesigned homepage https://github.com/cds-snc/notification-api/issues/341#issuecomment-535497158 (french version here https://xd.adobe.com/view/06581e1e-5e34-4aa8-4867-a7cda0b2def2-7069/)
- Based on Designs by Content design and Research
- Will need english translation

**Why?**
- UX research and feedback has lead us to believe that this homepage will market Notify better to users

**Comment by willeybryan** [comment]
Waiting for french content review

**Comment by timarney** [comment]
Where are we at with this?

**Comment by willeybryan** [comment]
English design done, available on this issue https://github.com/cds-snc/notification-api/issues/341

**Comment by AntoineGarciaSuarez** [comment]
here are the assets for the french version ! can you confirm me those are ok?
[fr.zip](https://github.com/cds-snc/notification-api/files/3698411/fr.zip)

**Comment by timarney** [comment]
Thanks @AntoineGarciaSuarez those should work for the fr side 👍

**Comment by AntoineGarciaSuarez** [comment]
cool,I'll check with @caycefischer for the english ! :)

**Comment by timarney** [comment]
@caycefischer @AntoineGarciaSuarez can you review this?

I need to pick up https://github.com/cds-snc/notification-api/issues/402 to finish the contact form which is tied to that one.

**Comment by caycefischer** [comment]
on it - what's the staging URL again @timarney ?

**Comment by timarney** [comment]
https://notification-canada-ca-pr-209.herokuapp.com

Latest fixes we're

Making all fields required for the form
Making the page scroll back to the top of the form when there's errors

The form currently goes to a thank-you page but doesn't actually submit an email yet (as I need to fix the api to allow no logged in users to send).

Also currently if you fill in a non government address it will throw an error

```
Enter a government email address. If you think you should have access <a href="/support/ask-question-give-feedback">contact us</a>
```

Need to fix the actual message there.

That said - 

Do we want to block non gov emails?

This helps as far as spam but - not sure what the right call is here cc @willeybryan

**Comment by caycefischer** [comment]
Some design/CSS things :

- it's defaulting to Arial, can we get Helvetica first in the font stack instead?
- Some changes to the header styling at the large breakpoint:
```
@media (min-width: 641px)
.product-page-intro h1 {
    font-size: 42px;
    line-height: 1.1;
    max-width: 80%;
}
```
- top margin of this section is larger than that of the the other sections (looks like double) - it's better, can we make the top margins of every section that tall:
![image](https://user-images.githubusercontent.com/546495/66656691-7cdafd80-ec0c-11e9-92dc-38fd5df22fe5.png)
- footer is pretty tall, can we get all 4 links on one line, and reduce the padding of that section:
![image](https://user-images.githubusercontent.com/546495/66656739-9419eb00-ec0c-11e9-918c-82bc9a1f3c82.png)

**Comment by willeybryan** [comment]
Sorry, missed "Do we want to block non gov emails?"

No we don't want to block non-gov emails. We don't now all the possible gov domains. There could be other domains out there that we don't know about yet. We need to let those people message us if they think their domain should be included. 

UNLESS the development complexity is greatly increase by that. Then we can just find another way.

**Comment by timarney** [comment]
@willeybryan the Home Page PR https://notification-canada-ca-pr-209.herokuapp.com

Is updated to allow non gov emails now.
