### ISSUE TITLE
If Notify goes down intentionally or otherwise it should fail gracefully

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#322]
**Story**
During downtime (planned or unplanned) service operators using Notify should have an explanation that we are working to get it back up as soon as possible to alleviate their worrying and prevent them from contacting us or IT.

**What?**
- Downtime/maintenance page page for Notify based on designs here https://github.com/cds-snc/notification-api/issues/323#issuecomment-545568402
- This is a draft page we will have reviewed and translated (Guidance for page https://www.atlassian.com/blog/statuspage/maintenance-page-examples)
- Needs to have a URL that it can always be accessed even if Notify Can't
- Needs to be available even if Notify is down, so host is on a distinct instance. (Maybe even Azure incase AWS goes down?)
- Needs to fail over to this page when Notify is not accessible on the server (500 type errors?, 404 AWS?)

**Why?**
- SLOs and SLAs have this as a requirement
- To onboard more decision makers we need to make sure that we check the boxes that they are looking for in an live service
- Service operators can email us if stuff goes down and we want to avoid it.

**Comment by maxneuvians** [comment]
https://aws.amazon.com/blogs/aws/create-a-backup-website-using-route-53-dns-failover-and-s3-website-hosting/
