### ISSUE TITLE
Create content for a Downtime page

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#323]
**Story**
Users need to know if the service goes down that it isn't them, it is us, so they can manage expectations.

Decision makers want to know we have support for planned and unplanned downtime as part of an SLO

**What?**
- Our error pages need to be clear
- Users need to see something when we go down
- can base design off of this https://www.atlassian.com/blog/statuspage/maintenance-page-examples
- Mockup of page for development to implement

**Why?**
- The service needs to be more polished to go live and failing gracefully is a check box for that

**Comment by caycefischer** [comment]
FINALLY getting around to uploading the Generic* downtime page for Notify, sorry i kept forgetting

![downtime_generic](https://user-images.githubusercontent.com/546495/67420690-1b684680-f59d-11e9-841b-8d1f46a6d5b4.png)
**Title:** `Sorry, the Notify service isn’t available right now`
**Subtitle:** `There should be only a short disruption in service. If you have urgent questions, please contact us.`

![downtime_fr](https://user-images.githubusercontent.com/546495/67421381-5c148f80-f59e-11e9-9dc1-ef8a1f529c4f.png)
**Title:** `Désolé, le service Notify est pas disponible actuellement`
**Subtitle:** `Il ne devrait y avoir qu'une brève interruption du service. 
Si vous avez des questions urgentes, veuillez nous contacter.`

future:
- explore differentiating between a SERVICE outage and a WEBSITE outage (future, lower priority)
