### ISSUE TITLE
Migrate Notify from GCP to AWS

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#332]
**Story**
Decision makers seek confidence in the security of our system and moving to AWS makes it easier for us to convince them it is secure as AWS has been cleared in other instances for prot cloud.

**What?**
- End of Sprint AWS is coming to the office to help us migrate and teach us stuff

**Why?**
- Security
- We scored AWS help

**Comment by maxneuvians** [comment]
Everything should be in one AWS account now
