### ISSUE TITLE
When evaluating Privacy we need to know if Emails are stored in Logs

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#34]
**What?**
- GDS says they have an option to scrub the logs. It looks like info is only kept for 7 days anyway.
- Do we have that option?
- Can we turn that on or is it on by default?
- It stores the emails to show which ones bounces, can we still save bounces since they didn't work the emails don't reveal PII?

**Why?**
- If we aren't storing emails in Logs it reduces privacy complexity

**Comment by willeybryan** [comment]
@damcom333 Does it improve our security posture if it only stores emails for 7 days?

**Comment by maxneuvians** [comment]
There is a redacted flag for templates which I believe ensures it does not store the personal data,

**Comment by willeybryan** [comment]
Redacted how? as in it was a user option but now it isn't?
Can we turn it on by default? What does it impact?

**Comment by maxneuvians** [comment]
![Screenshot from 2019-07-11 15-06-49](https://user-images.githubusercontent.com/867334/61078181-15839680-a3ee-11e9-9b27-4c98817bf2fd.png)

**Comment by willeybryan** [comment]
Ah, Yeah I found that now. @YedidaZalik we will need to note down the Hide personalization box references 'Notify'

As for this it is good to have. We may want to put it on by default so that we absolve ourselves of liability of storing PII. I want @damcom333 's and @sboots 's inputs though.

**Comment by damcom333** [comment]
> @damcom333 Does it improve our security posture if it only stores emails for 7 days?

Well it doesn't hurt our security posture to have options. As long as those options work. I see this more like a capability that reduces potential impact of any breach of privacy that could occur. The damage is limited to what is currently available inside the system. I mostly see systems that aggregate their data forever. Therefore their potential for larger and larger impact, if a breach were to occur, is always increasing.

**Comment by willeybryan** [comment]
Ok so lets test and see how long stuff sticks around. If we get users and adoption then that makes the system a target, so we should then evaluate how to restrict stuff stored in logs to prevent the severity of a breach. 

For now as this is early stages and there is limited data in the system that could be compromised we can come back to this later in Alpha. 

@maxneuvians Can you change the Text box to read "Notification" instead of "Notify" for consistency on this ticket or should I make a separate one?

**Comment by timarney** [comment]
Looking at https://notification.cdssandbox.xyz the Notify has already been updated.

<img width="752" alt="Screen Shot 2019-07-17 at 7 59 23 AM" src="https://user-images.githubusercontent.com/62242/61373830-d8ddf200-a868-11e9-8ef0-eebf5a408a46.png">

**Comment by willeybryan** [comment]
Yeah, I think I noticed it changed almost everywhere. Some one did a find and replace on that. I am going to say this is done for now as it can be hidden upon sending and we can force that later should we desire, and even then it is only held for 7 days max.
