### ISSUE TITLE
For new homepage create english contenct

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#341]
Continuation of #289

**What?**
- Reverse engineer english content from french
- update and edit as needed. 

**Why?**
- New homepage to sell decision makers

**Comment by caycefischer** [comment]
**Link to French designs (_missing Contact form_):** https://xd.adobe.com/view/06581e1e-5e34-4aa8-4867-a7cda0b2def2-7069/screen/42bc7703-d76c-4de0-a0e3-56a22127576f/HomePage-FR-Notifications/

**English designs (v2):**
[Notify_Homepage_English.pdf](https://github.com/cds-snc/notification-api/files/3657893/Notify_Homepage_English.pdf)
![Notify_Homepage_English](https://user-images.githubusercontent.com/546495/65690970-136cc380-e03e-11e9-9426-febeabcd88bd.png)

**Remaining Design To-Dos:**
- Source illustrations (from Antoine, or re-create) - in English and French
- Re-translate English content into French (or merge changes)
- Informal design review to align with CDS design standards

**Comment by timarney** [comment]
Can someone extract the individual svgs for where the palceholders are for (En and FR) once I have those I should be able to pick this up.
