### ISSUE TITLE
Wrap Outstanding english translation strings to PO file for Translation

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#354]
**What?**
- Audit of Notify found missing French translations that need to be added to the PO edit file if they haven't been already. 
- New Strings and where they are is in this doc https://docs.google.com/spreadsheets/d/1ObRnqM2k41C5sG2aoOZAnKrgvF2v8v1wNheZH4U52yg/edit#gid=0
- Add new strings to Translation file here https://github.com/cds-snc/notification-admin/blob/master/app/translations/fr/LC_MESSAGES/messages.po

**Why?**
- Finish French Translation.

**Comment by timarney** [comment]
https://github.com/cds-snc/notification-admin/pull/205

**Comment by willeybryan** [comment]
I am worried something may have been missed on this ticket. 
I looked in the file and the push for some of the strings in the spread sheet like "Use my email address" and I couldn't find them. Without it in there we can't translate it, right? Am I missing something?

**Comment by timarney** [comment]
@brdunfield @smcmurtry this on is up for grabs.  I can help out again once I wrap the homepage.

Part of the issue the form issue i.e. check the create account form.

Fix for the forms per @brdunfield is to handle the translation in the template not in the form python code.

```
{% set name_label = _('Full name') %}
{% call form_wrapper(autocomplete=True) %}
{{ textbox(form.name,label=name_label, width='3-4') }}
```

**Comment by timarney** [comment]
@willeybryan at a point now where it would be best to translate the .po file and see what's left.
