### ISSUE TITLE
Rewrite content for International text messages

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#356]
**What?**
- Content on this page https://notification.alpha.canada.ca/services/e609f6b0-0390-45b0-aaae-f4cc92c713e4/service-settings/set-international-sms
- Needs update as it talks about UK pricing and stuff
- Remove UK reference, pricing reference
- Remove link to pricing page

**Why?**
- We aren't charging yet, but do let them know international can wrack up a bill

**Comment by caycefischer** [comment]
addressed here: https://github.com/cds-snc/notification-admin/pull/226

French still needs updating AFAIK

**Comment by timarney** [comment]
https://github.com/cds-snc/notification-admin/pull/227
