### ISSUE TITLE
Our first templates

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#357]
**Story**
When writing a template service operators are scared because they have never crafted one before, examples would help give them a foundational starting point. 

**What?**
- Templates for the template system. First template: Confirmation of Receipt 
- Create templates here: https://notification.alpha.canada.ca/services/93305b36-b0a0-4a34-9ab2-c1b7bb5ca489/templates

**Why??**
- People need to know how to write emails that recipients will trust
- People want to send notifications for specific reasons
- So we can test these guidelines on users later

**Comment by willeybryan** [comment]
Note to self: Expand links

**Comment by willeybryan** [comment]
Compiled from Research 

Research Findings:- Hyperlinks: Yes in the format 'Click Here to sign in: https://digital.canada.ca/?signin' so people can see, understand, and make sure that they end up at the link they clicked. Make sure to include https:// people trust the S- Make messages look and feel consistent. If all the messages from your service have the same branding people will learn to trust that brand.- When a user signs up to receive something via email, send them a confirmation email indicating they have signed up for this. Then they will expect other messages from that address with that look and feel. Since they just triggered the action they will trust the email based on it's timing. This helps build trust for future emails. 
- Including French copy after the english helps English people believe the email is from the GoC and not spam, People expect both languages
- Making sure the French copy matches the English copy is important for French users as it helps them validate the email.
- Including Hyperlinks to legal documents like the privacy act at the end/bottom of the email helps reassure people
- Including links to web pages that outline why they got this message also help at the end/bottom of the email helps reassure people.
- Offering a mechanism to unsubscribe helps people believe the message is trustworthy. (Even though the GoC isn't subject to CASL, it is still expected)- Offering another way to contact you should they have questions about the email (Phone, online form, etc)
Our most contentious finding is this:- Including a person's Name at the start of the email helps people believe the email, people expect the government to know their name.
It is contentious because some believe that this would cause a privacy issue because including a person's name and email would technically put two pieces of PII in the same place, but our argument people willingly put their names in emails all the time. 
So the jury is still out on that one. 

Don't, for security, privacy ,or trust reasons:
- Include session or personal information in the URL/hyperlink in the email, security and privacy concerns.
- Track people clicking the links in the email, privacy concern- Make spelling/grammar errors, people immediately think it is spam if we can't spell. Trust issue.- Have URL/hyperlinks in the email show just http://, People think https is more secure and therefore better- Attach files directly to the email, people are scared to download this as they think it is a virus and will call you to ask

**Comment by caycefischer** [comment]
The template has been updated - not sure how to get it to appear in this dropdown though: 

![image](https://user-images.githubusercontent.com/546495/71097724-72922e00-217e-11ea-91d8-8ba19f3d1abe.png)

**Comment by willeybryan** [comment]
Shows up for me and looks good,

![image](https://user-images.githubusercontent.com/46505127/71099374-28f71280-2181-11ea-9751-358016f98046.png)

**Comment by caycefischer** [comment]
Great!
