### ISSUE TITLE
Add a link to how to change your endpoint to Documentation

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#360]
**What?**
- Link to https://github.com/cds-snc/notification-api/wiki/How-to-change-your-API-endpoint%3F 
at the top of https://notification.alpha.canada.ca/documentation
- call link to it  "Changing your endpoint" 
- French 
"Changer votre point de connexion API"
- French link to https://github.com/cds-snc/notification-api/wiki/Comment-changez-vous-votre-point-de-connexion-API%3F

**Why?**
- So that people can decode GDS instructions in any language

**Comment by timarney** [comment]
https://github.com/cds-snc/notification-admin/pull/206
