### ISSUE TITLE
Bulk send of 2 didn't send

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#362]
**Steps to reproduce**
- Send this template with a 2 entry csv https://notification.alpha.canada.ca/services/c31680dd-8d0d-4e9f-be06-0d2f201aeaf8/templates/2e4ad8fc-83e1-498b-ad63-cca42e81954d
- One entry was to Bryan at CDS the other was to a mailinator email

**Actual**
- Job acted as scheduled and UTC time stamp even though it was send right away
- Job 'sent' at 'scheduled' time but only tried sending email for entry 2 in the csv to mailinator and got stuck
https://notification.alpha.canada.ca/services/c31680dd-8d0d-4e9f-be06-0d2f201aeaf8/notifications/email?status=sending%2Cdelivered%2Cfailed

**Expected**
- Scheduled jobs time stamps are not in UTC
- The job should have sent or reported failure, or tried to send the other entry by now

**Comment by maxneuvians** [comment]
Closed in https://github.com/cds-snc/notification-admin/pull/200
