### ISSUE TITLE
Can't rename folders with templates in them

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#364]
**Steps to reproduce**
- Try to rename this folder https://notification.alpha.canada.ca/services/e609f6b0-0390-45b0-aaae-f4cc92c713e4/templates/all/folders/91ab83bb-e135-4cb1-8da9-44070d9e83b1

**Actual**
- Page not found and folder doesn't get renamed

**Expected**
- Folder name gets changed

**Comment by timarney** [comment]
Can't reproduce

**Comment by willeybryan** [comment]
I get a 404 when I try to rename it.
But it works when It is a service I am actually a member of.
It seems like even though I am platform admin I don't have access to change other peoples folder names. 

This is fine. We can just remember that for now as this only impacts CDS.
