### ISSUE TITLE
Can we Print letters?

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#379]
**What we need to know?**
- Use existing print services to print letters we need to be able to send "...fully composed AFP files delivered via LPR to specifically setup print queues on their servers."
- Can we create AFP files? How? With what library?
- Can we send them via IBM LPR to a print server? How?

**Why?**
Letters is a legacy system but the assumption easier to integrate than open a print shop. We need to validate that assumption.

**Comment by maxneuvians** [comment]
First question to answer is if we can get a cloud to ground connection to send data into the print server queue?

**Comment by willeybryan** [comment]
Good question. 
I wonder how this would work normally. Does it all happen inside the firewall? How would we send something inside the firewall to SSC or PSPC to print?

@obrien-j Is there anyone we can talk to to find out more about letters?

**Comment by obrien-j** [comment]
I thought you'd never ask.

**Comment by willeybryan** [comment]
I've got the contact at PSPC a few weeks ago. Can spin that up whenever you think it makes sense. No one's chomping at the bit, so not a high priority.
