### ISSUE TITLE
Configure and Set URL and name for service (notification.alpha.canada.ca)

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#38]
**What?**
- We need a URL to put the service on that is bilingual, available, and looks official
- Talks have pointed us too The winner is Notification.Alpha.Canada.Ca
- please add notification.alpha.canada.ca to https://github.com/cds-snc/dns
- please update any URLs, Repos, to reflect Notification as the name. 

**Why?**
- Official languages act
- don't want people/mail services to disregard us as spam

**Comment by willeybryan** [comment]
How do I get a URL?

**Comment by obrien-j** [comment]
suggest changing the title of the ticket to be less prescriptive, more in line with your 'what?' in the original description.

Also to note: Notification in english, est le meme chose que notification en francais..... 

notifier in english refers more to a person/thing that notifies, where as in french, notifier, is the verb form 'to notify somebody of something'... it doesn't feel like the ideal word.

All that to say....

Our internal posture on domains is that we go through subdomain.<optional-dept>.alpha.canada.ca, into *.beta.canada.ca, before finally rocking into to notification.service.canada.ca

https://github.com/cds-snc/dns <-- for requests onto alpha.canada.ca, 

or

<insert principal publisher (esdc/tbs) web form> for requests to subdomain off of canada.ca (these are harder and slower)

**Comment by willeybryan** [comment]
@obrien-j  Lets say we wanted to use notification.alpha.canada.ca for now.
How do I get the ball rolling on the longer notification.canada.ca process?

**Comment by willeybryan** [comment]
The winner is Notification.Alpha.Canada.Ca

**Comment by maxneuvians** [comment]
Update the k8s deployment scripts, will work through the other repos and dependencies on the weekend and monday https://github.com/cds-snc/notification-kubernetes-deployment/commit/d94c945e0eca4cda8be3067338de945545904f96

**Comment by maxneuvians** [comment]
Updated all the repos to `notification`, just need the official alpha domain to go through

**Comment by obrien-j** [comment]
Still waiting on DTO, I pinged @sboots again to check their status.

**Comment by maxneuvians** [comment]
Working on this, https://github.com/cds-snc/dns/pull/35 need some help so it does not nuke the entire cds-snc.ca domain

**Comment by willeybryan** [comment]
This is a blocker to further research and testing. Other departments can't access the URL (Including TBS) because it has been marked as suspicious.

**Comment by obrien-j** [comment]
should be sorted out shortly bryan. It looks like our NS records through
SSC were removed.

**Comment by willeybryan** [comment]
Site still blocked. Blocking Usability testing. 
We need to move to *.canada.ca to unblock testing
