### ISSUE TITLE
a11y - VO on Create an account reads too much text on email field

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#387]
**Current**
- when creating a new account Email field reads far to much text with voice over and repeats a lot of information

**Desired**
- Cut the aria tag (i assume) down a bunch

**Why?**
- a11y audit

**Comment by timarney** [comment]
@JuliannaR what do you recommend here?

I believe the "too much text" is coming from the browsers auto-fill (could be wrong).

Can you clarify or point in the right direction to fix here.

**Comment by willeybryan** [comment]
Notes: "I looked at this with JAWS and NVDA lastnight, the experience is better with both. The experience with VO on a mac is much more verbose. There isn't an aria label, so I think there isn't much we can do currently to improve."
