### ISSUE TITLE
a11y - VO on Phone number field on create and account is listed as input field not text field

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#388]
**Current**
- During account creation VO reads phone number field as input field

**Desired**
- Text field like the rest so people don't think it is different.  

**Why?**
- Came out of a11y audit

**Comment by timarney** [comment]
@JuliannaR can you clarify further if there's anything we can do here.

The input use the "tel" type already.

<img width="500" alt="Screen Shot 2019-10-16 at 8 26 38 AM" src="https://user-images.githubusercontent.com/62242/66919201-e5502300-efee-11e9-998a-e5704ab98721.png">


https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/tel
```
...  inputs of type tel are functionally identical to standard text inputs
```

The main use can being it works different for mobile.

```
... 
they do serve useful purposes; the most quickly apparent of these is that mobile browsers — especially on mobile phones
```

**Comment by willeybryan** [comment]
That is neat, I didn't know they worked diff on mobile!

**Comment by timarney** [comment]
@JuliannaR - see https://github.com/cds-snc/notification-api/issues/388#issuecomment-542676410

**Comment by JuliannaR** [comment]
I think you are right here. I was thrown off why on the laptop they were reading as different fields.
