### ISSUE TITLE
When Sending Emails we don't want Gov.uk branding on them, we want our own so it isn't confused as spam

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#39]
**What?**
- Strip out branding from emails
- Replace with GoC Logo

**Comment by willeybryan** [comment]
@sboots Help ensuring we are FIP compliance with this using previous guidelines

**Comment by timarney** [comment]
The template for this are in a separate repo - found here 

https://github.com/alphagov/notifications-utils/blob/master/notifications_utils/jinja_templates/email_template.jinja2 

We also need to update the requirements in the admin:

git+https://github.com/alphagov/notifications-utils.git@33.0.0#egg=notifications-utils==33.0.0

**Comment by timarney** [comment]
Template is updated - https://github.com/cds-snc/notifier-utils
