### ISSUE TITLE
Contact us should work without sign in so people can ask about signing in

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#397]
**What?**
- We need the form to be able to adapt to if a user is logged in or not
- Form need to be able to be used across the site
- Mockup of stateful form for logged in user. 
- Use design of homepage form as foundation. 

**Why?**
- Two main issue for contact, are contact for questions or support issue.

**Comment by timarney** [comment]
@willeybryan 

Feels like this is rolled into

https://github.com/cds-snc/notification-admin/pull/209

Can you review and confirm?

**Comment by willeybryan** [comment]
Sadly it doesn't work, I tested and got this error
![image](https://user-images.githubusercontent.com/46505127/66836394-3bf62800-ef2f-11e9-8146-ada860592a38.png)

**Comment by timarney** [comment]
See my question regarding that here:

https://github.com/cds-snc/notification-api/issues/306#issuecomment-541053595

<img width="749" alt="Screen Shot 2019-10-15 at 9 41 35 AM" src="https://user-images.githubusercontent.com/62242/66836856-1cabca80-ef30-11e9-9a26-f5464ca78ac8.png">

**Comment by timarney** [comment]
Updated - the build takes about 12min.

**Comment by timarney** [comment]
@caycefischer 

Any reason this was re-opened?

**Comment by caycefischer** [comment]
oh, woops no, sry! i think i just hit the reopen button while scrolling the page on GH's weird kanban UI
