### ISSUE TITLE
Email branding gets crushed on Mobile

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#408]
**Steps to Reproduce:**
- Notify your self on a mobile phone. 
- Look at in you default email client. (Android -> Gmail)

**Expected**
- Canada logo to be separate and distinct

**Actual**
- Squished, See Screen Shot
![image](https://user-images.githubusercontent.com/46505127/67038940-5e826f80-f0ee-11e9-847a-c528582f9fb8.png)

**Comment by timarney** [comment]
Will be moving the Canada [] on the right to the bottom right.
