### ISSUE TITLE
Draft IA and Site nav mockup

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#409]
**What?**
- We need to know What could a Notify Support experience look like, contain, and how it should work. 
- Rough Design/mockup/screens/Diagrams what we want to do with our Support page. (Ideas: SLA?, Contact info?, Support Hours? import links?, FAQ?, Content Guide?, How to go live guide?, All file sent are scanned by CSE?)

**Why?**
- Pricing page needs to show its free somwhere
- We need to start testing and validating support experiences
- Current support flow was left rough after cutting out GOV.UK content
- Support process currently provides a below basic UX
- If we want to appear more professional we want people to be able to trust our support
- Support pager here has no content or french https://notification.alpha.canada.ca/support/thanks
- No pages lead to but this needs to be completely changed https://notification.alpha.canada.ca/support
- We have been working very closely with people for now but our net or trials is getting wider

**Features Page Notes**
- Should include all files uploaded to Notify are sent to CSE for virus scanning.

**Comment by willeybryan** [comment]
Spread sheet of communications https://docs.google.com/spreadsheets/d/1Xy_RqJhEd5E_G-g9kNmQ9wsm9t_S9MavBGPlL4jr2Ak/edit#gid=1520576439

New comms board https://trello.com/b/2e3E7MYQ/notify-leads-and-opportunities

**Comment by caycefischer** [comment]
first draft of new sitemap:
[SITEMAP NEW.pdf](https://github.com/cds-snc/notification-api/files/3918070/SITEMAP.NEW.pdf)
![SITEMAP NEW](https://user-images.githubusercontent.com/546495/70078805-68463080-15d1-11ea-8c1a-2ea0cc3e8b5c.png)
