### ISSUE TITLE
Update User Updates with what Updated

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#410]
**What?**
- Update Template (https://notification.alpha.canada.ca/services/d6aa2c68-a2d9-4437-ab19-3ae8eb202553/templates/5b39e16a-9ff8-487c-9bfb-9e06bdb70f36)
With "((What)) updated by ((User))"
- Send this for the same events we currently send it for
- Could be  (Password, phone number, name, Archived Status, others?), by )You, Admin, Service Owner)

**Why?**
- When and admin changes a users permissions the system sends an email saying something changed but doesn't tell them what, causing them to think they have been compromised.

**Comment by timarney** [comment]
Noting these files:
event_handlers.py
events_api_client.py

**Comment by timarney** [comment]
- [ ] phone number
- [ ] email
- [ ] password
- [] auth type?

**Comment by willeybryan** [comment]
Need to update code for password and permissions

**Comment by timarney** [comment]
This is done.

Note: There's when updated permissions the user auth type gets flagged as a change as well because there are no checks for previous values.

We can do some more complex checks etc.. as need be in a fresh ticket.
