### ISSUE TITLE
MSCA Alert me vs Notify

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#411]
We need to know stuff about what people want before we map out a service from the back end. 

**What?**
- Which do people prefer? why? what can be done better?
- Survey many, mixed methods?
- Help us determine when people want to get Notifications?
- Talk to and get research from IRCC, CRA, RCMP on what people want in their notifications

**Why?**
- Measure the benefit to the public of new notifications

**notes**
- Show slide 46 of this presentation
https://docs.google.com/presentation/d/1JXX4MuVVd660ICD5TNo9JKk9JuBMDW1EzWlsLBV79j4/edit?ts=5d9f6dd0#slide=id.g7c7ec690f9_0_0

**Comment by ioanacontu** [comment]
Add a map of the bigger service environment, including the intersections with the general service infrastructure, all stakeholders, and the decision making processes.
