### ISSUE TITLE
Audit and Cut unneeded Automated tests

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#413]
**What?**
- We have cut back on a lot of systems, like Letters, ZenDesk, UI content, and more. If there are still tests running on any of these we should be able to shut them down for now as they would no longer be needed. 
- Make tests pass after 8pm

**Why?**
- Testing is pushing built time higher and higher hurting out development velocity and increasing support difficulty.
- If we are trending towards live services using this we need to make sure we are capable of fast and responsive support

**Comment by maxneuvians** [comment]
It is safer for us to keep them `Skipped` because we may need them for other features ex. letters in the future
