### ISSUE TITLE
Audit and Refactor UI automated tests

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#414]
**What?**
- Automated tests in the UI need to be consolidated and updated to test relevant cases for our UI
- If possible remove tests we don't think are necessary
- Keeping in mind the new site map and how that could impact tests https://user-images.githubusercontent.com/546495/70078805-68463080-15d1-11ea-8c1a-2ea0cc3e8b5c.png

**Why?**
- We are going to start modifying the UI heavily and we don't want this to slow us down. 
- Improve build performance by reducing test numbers
- allows for faster response and quickly development feedback loops.

**Comment by timarney** [comment]
We'll do this as we go.  Much easier now that we're not pulling updates.
