### ISSUE TITLE
API Automated Test Audit

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#415]
**What?**
- Automated tests in the API need to be consolidated and updated to test relevant cases for our API
- If possible remove tests we don't think are necessary

**Why?**
- Improve build performance by reducing test numbers
- allows for faster response and quickly development feedback loops.

**Comment by maxneuvians** [comment]
It is safer for us to keep them `Skipped` because we may need them for other features ex. letters in the future
