### ISSUE TITLE
Change Branding Setting page needs qualifier

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#417]
**What?**
- The branding upload changer should include text under the header "Uploads need to be exactly 108px tall to fit correctly at the top of your emails" and wrap for french translation
- Indicate 'We will review your branding and implement it.' 

**Why?**
- So that people can change their branding and we can get back to them to say wrong size.

**Comment by timarney** [comment]
Merged - needs to be translated.

https://github.com/cds-snc/notification-admin/pull/267
