### ISSUE TITLE
Deploy 'Max'imum admin panel and wrap in Notify Auth

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#426]
**What?**
- Make the new admin system available to Platform team members on a URL we can access
- Wrap in the Notify auth so that unauthorized users can't get in
- Put a link to the new admin panel one at the top of the old one

**Why?**
- Old admin panel makes support hard for our use cases and we want to improve the UX for us. 

**Note**
(I imagine all the API calls look for our auth anyway, but we need to be authorized to access the URL, even if that means we have to go through Notify auth, The solution to this could just be Log in to Notify first then go to URL)

**Comment by maxneuvians** [comment]
The way the notify auth works it creates a new session every time you log in so if you logged in on one admin, it would kill the other admin session. Passing the session hash around might not be ideal security wise. I working on a different solution
