### ISSUE TITLE
Connect Notify to CDS patching system JAMF

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#429]
**What?**
- Emails are sent from JAMF <smtp.serviceaccount@cds-snc.ca> to users at CDS when we need to update software and they should come from our fantastic template email system instead if possible
- Find Damien and see if we can connect this to Notify with the API

**Why?**
- We send these emails from smtp when we could be using our own Notify platform with templates. 
- It was decreed that all internal CDS use cases should use Notify where possible. 

**Example**
Currently these look like, so a template can be created with this. 
![image](https://user-images.githubusercontent.com/46505127/67490404-312f4780-f641-11e9-9c4b-bcd91990747f.png)

**Comment by damcom333** [comment]
Noted.

**Comment by maxneuvians** [comment]
Moved to platform backlog vs notify backlog
