### ISSUE TITLE
Set up Prometheus and Grafana

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#433]
**What?**
- Set up an instance of prometheus as a data source
- Set up a Grafana instance
- Connect them
- Figure out system metrics we want to monitor

**Why?**
- System load trends over time and DB load is handy in monitoring a service.

**Comment by timarney** [comment]
@willeybryan 

We're going hold on this until we get logging on AWS handling things better.

**Comment by maxneuvians** [comment]
We should leverage AWS for this
