### ISSUE TITLE
Add a system use notification as part of the logon process before granting user access to your solution (as per the TBS security workbook)

### ISSUE THREAD

**Issue by damcom333** [cds-snc/notification-api#438]
**Story** When Logging in I want to see when was the last 3 times I logged in so that I may validate that I am the only one using my account. 

**What?**
- After Login, don't fully authorize user yet, Show users a page with the last 3 times a user logged in
- Include Browser, Date, Time, (Optionally: Location, Device) (Localized to their time zone)
- Text saying "Where these last 3 logins preformed by you?
- Green friendly button in Notify system style that says 'yes' -> Advances them to the dashboard of their service (Resume normal function)
- Grey button, black text in Notify system style that says 'I don't think so' that opens a contact us form and asks them to explain which one isn't theirs. (Use the new contact us form from the home page that doesn't require login)
- After this is sent auto lock the account for security reasons until we complete our investigation. 
- Send automated notification to the user apologizing for the inconvenience and letting them know that this is the highest priority for us. 

**Why?**
- 3 was picked based 2 is not enough to ensure that it has only been you using the account in case of coincidence, but I can't remember the last 5 times I logged in. (Sample Size 1, also Googles implementation of this is account security is 3)
- People remember what browser they used and can remember a browser update between login attempts. They notice browsers that stand out and times that stand out, like 3am eastern time. (Source Googles implementation of this)
- Optional data can help with a decision but I don't know what data we have available. I know we currently have last logged in on the account info page. 

**Damien's Notes?**
This change would force the user to navigate through a login history page before being allowed to use notification features. The thinking here is that when a user is forced to view their login history at each login, they can detect when their account has been taken over by somebody else. 

This is common requirement for GC web apps. It is also mostly poorly implemented, if implemented at all. This design work would be relevant to every department.

**Comment by willeybryan** [comment]
@damcom333 Would what I have proposed here work?

Would we want to track login attempts at all?

**Comment by damcom333** [comment]
You all gonna be mad at me cause I'm here. But the following should be part of the notification of use.

System use events to record and display back to the user.

1. Password reset initiated
2. password changed
3. 2FA added with type
4. 2FA removed with type
5. Login attempt failed (with stages, 1) failed on password, 2) failed on 2FA)
6. Successful login
7. user suspended
8. user suspension removed
