### ISSUE TITLE
Implement mechanisms to appropriately handle and retain information in storage and in outputs.

### ISSUE THREAD

**Issue by ghost** [cds-snc/notification-api#439]
This task is mentioned in the TBS Security Playbook for Information System Solutions.

The task reads: Implement mechanisms to appropriately handle and retain information in storage and in outputs.

Placing this here so we can talk it out.

**Comment by willeybryan** [comment]
Notify has a mechanism that clears data after 7 days by default. It can be lowered to 3. If this clears everything from Notify is that sufficient? 

How does this impact data retention in Logs?
How does this data retention impact Backups?
The other things that are stored include, templates and public servants login accounts. Assuming no PII in templates, What sort of protection is required for those.

**Comment by willeybryan** [comment]
This just has to be a transfer of liability onto the service owner to main tain their logs from exports and adjust their retention policy if necessary
