### ISSUE TITLE
Perform penetration testing and/or run-time vulnerability assessment against publicly accessible interfaces.

### ISSUE THREAD

**Issue by damcom333** [cds-snc/notification-api#440]
**What?**
- Stand up some OWASP Zap (https://hub.docker.com/r/owasp/zap2docker-stable/ ?)
- Run it against Notify
- Send assessment to Damien, John, and Bryan

**Why?**
- We need to satisfy security controls by saying we do routine pen testing.

**Comment by willeybryan** [comment]
@damcom333 Does Pen testing need to happen on a routine at all? 

I favour just using an approved TBS vehicle for it if it only has to happen once in a while. 

Would an IDS/IPS meet this need? (https://aws.amazon.com/marketplace/solutions/infrastructure-software/ids-ips)

**Comment by damcom333** [comment]
The IDS/IPS would not satisfy the requirement for a pentest engagement. To meet the requirement to the letter I think a test every 365 days will suffice. I will research the vehicle this week and get that started.

**Comment by obrien-j** [comment]
OWASP Zap, nessus, or equivalent dynamic testing would be sufficient for this @damcom333 

I'd split the pen-test out into a separate one, and push bug bounties off entirely.

**Comment by willeybryan** [comment]
Deal https://hub.docker.com/r/owasp/zap2docker-stable/

**Comment by timarney** [comment]
Noting this:

Having issues connecting to the docker container / API on my mac.

> github.com/zaproxy/zaproxy/issues/4485#issuecomment-373442989

**Comment by timarney** [comment]
Going to mark this as complete - we need to map out how to handle auth users + logging in with 2 factor auth and see if we want to go down that road.  If we do that can be a fresh issue.

Logged out scanner is here.

https://github.com/cds-snc/owasp-zap
