### ISSUE TITLE
Implement a backup and restore process for the Notification data.

### ISSUE THREAD

**Issue by damcom333** [cds-snc/notification-api#441]
**Story** The data center(s) has/have been destroyed by a tornado(s)! We need to stand up another copy of Notify right away to ensure tornado notifications send uninterrupted. 

**What?**
- Encrypted Backup
- An Automated Encrypted Backup procedure that runs weekly and saves a copy to another physical location.
- Upon every new weekly back destroy old backup copy. (No data should be stored more than 7 days.)
- Script to restore an Encrypted Backup that can by executed by a CDSDev(Notify team at least) 
- Test the script to make sure it works (Automated tests, Testcase: sending a spreadsheet, testcase: sending with API)
- Documentation for script usage

**Why?**
- Disaster recovery is important for uninterrupted service operation of a government service

 
**Damien's Notes**
Requirements:
1. Implement a backup and restore process
2. Document and make references to contingency planning.

Note: Make sure we can restore an encrypted backup. For example. If Max backs is up, that Developer 2 can restore it.

**Comment by willeybryan** [comment]
@damcom333 should we make it run a routine automated backup in a certain cadence?

**Comment by damcom333** [comment]
@willeybryan Yes. We Discussed this inside the slack. The cadence being:
> Nightly backups that get removed every 7 days

**Comment by maxneuvians** [comment]
I have finished the script that copies backups from one AWS account to another. The requirement to copy to another region might not work as there is only one Canadian region.
