### ISSUE TITLE
Develop account anti-take over procedure 

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#443]
**Anti-Story**: A spy has pickpocketed John's Yubikey and plans to send an email notification. We want that login to fail so they can't complete their goal.  

**What?**
- on the Archiving a User page (https://notification.alpha.canada.ca/users/1b5e967a-9dc4-4d19-b3e2-cf95a94f0572)
- Create New Function Lock User (Prevents user from modifying their account)

**Why?**
 - For example when a user contacts CDS and says they have lost their yubikey
- Users can Unarchive themselves so an override is needed to lock them out.
- Locking a user out nullifies an account take over.

**Comment by willeybryan** [comment]
@damcom333 
Would the lock out method I have proposed here be a sufficient solution?

**Comment by timarney** [comment]
https://github.com/cds-snc/notification-admin/pull/279

and 

https://github.com/cds-snc/notification-api/pull/456
