### ISSUE TITLE
Établir des principes de conception - Design Principles.

### ISSUE THREAD

**Issue by AntoineGarciaSuarez** [cds-snc/notification-api#445]
Refine https://docs.google.com/document/d/1TBra7pfXOaCRX86vblCGAmY4jXZeXKiOw255rUvDzxs/edit#

**Comment by ioanacontu** [comment]
Design Principles slides deck: https://docs.google.com/presentation/d/1K6VXBmPsYSiKy1Lv7bnKrUiOfnmWeWMuNJLHspgPQDI/edit#slide=id.p1
