### ISSUE TITLE
Investigate Azure AD as a SAML SSO solution

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#448]
**Story**
When logging into Notify, GoC employees need to validate their identify in an accepted secure way to reduce risk of incident and decision maker objections.

**What?**
- TALK TO GC PASS PEOPLE and figure out how we can work this

Notes on SAML 2.0 IN Notify
- Due to complexity we need a break down of the technical tasks to build Notify SAML SSO Support acting as a Service Provider to the Azure AD Identity provider
- Ensure Notify can create a new account with only Azure AD information (Email, Fname, Lname) passed via SAML Meta data
- Ensure Notify can accept SAML 2.0 Meta data in a format like https://nexus.microsoftonline-p.com/federationmetadata/saml20/federationmetadata.xml
- Validate that Email is being passed as either as its own value or as part of the NameID
- Assume TBS SAML meta data may differ from other departments ensure that meta data can be changed per service, perhaps a field in the New control panel?

**Why?**
- TBS tablet uses Azure AD to authenticate users via a SAML transaction. This is called GC Pass. 
- You may want to find the exact format the meta data uses, including NameID format, I have provided default MS guidance.

**Notes**
- https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-fed-saml-idp
- https://pypi.org/project/python-saml/2.2.1/
- I am sorry that Generic SAML is different from MS SAML.

**Comment by maxneuvians** [comment]
My current understanding is that the existing solution is not compatible with our use case. We will revisit the issue once our use case is covered.
