### ISSUE TITLE
When trying to get Notification used by Government departments a memorable brand could improve peoples opinions

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#45]
## **What?**

- We need styling for UI elements
- A colour scheme for link colours(Current #005ea5), link hover, dashboard boxes(#005ea5), Success states, failure states(#b10d1e), no failures(#01823b), search buttons (#01823b), Link&page highlights(#ffbf47), and box/button highlights(#dee0e2)
- Font styles (Currently Arial/Helvetica has been used to replace GDS proprietary font)
- Drop shadows like they have on buttons seem to be used to denote a button or a highlight box. 

## **Why?**

- We need something that reflects the nature and ownership of the service
- We want to give it a Government of Canada or CDS feel rather than a GDS Feel

## **Notes**

![image](https://user-images.githubusercontent.com/46505127/61000045-937e6980-a32a-11e9-9363-0877620da9ae.png)

![image](https://user-images.githubusercontent.com/46505127/61000189-ebb56b80-a32a-11e9-862e-7688efabf0e3.png)

**Comment by sboots** [comment]
Canada.ca's most recent design uses `Lato` as its main display font - could be a good candidate.

<img width="1337" alt="Screen Shot 2019-07-04 at 10 34 59" src="https://user-images.githubusercontent.com/263472/60674243-b4851d00-9e47-11e9-8b8b-2144f8903aae.png">
