### ISSUE TITLE
Migrate to our forever home URL

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#450]
**What?**
We need to get from Notification.alpha.canada.ca
to
Notification.Service.Canada.Ca or Notification.canada.ca

Include a 200 redirect on the old domain to the new one indicated a permanent move

**Why?**
- We won't have to move again
- Then people won't think it is alpha

**Comment by timarney** [comment]
@willeybryan as per stand-up this a.m we should push out doing the move until the New Year.

Should this bump back to to validate ?

**Comment by willeybryan** [comment]
Yes, Won't do for now.
