### ISSUE TITLE
Review IA & Navigation as it relates to Sender task flows

### ISSUE THREAD

**Issue by ioanacontu** [cds-snc/notification-api#455]
- Review current IA & navigation to identify existing problems 
- Diagram current sitemap 
- Draw Sender task flows
- Discuss issues with design/research/development
- Prioritize issues with PM and devs

**Comment by AntoineGarciaSuarez** [comment]
Cool! we'll be able to do some research with the navigation and IA! :)

**Comment by caycefischer** [comment]
![image](https://user-images.githubusercontent.com/546495/69063090-de4f7280-09e9-11ea-9b6c-34aa26f550ec.png)

**Comment by caycefischer** [comment]
Initial priorities list (from design sync last week:

- keyboard-accessibility of navigation throughout the dashboard page and sub-pages
- Pull footer-linked pages out of /features and into consistent root-level pages
- consolidate or differentiate 'documentation' vs 'features' page (dev docs vs other user docs)
- revisit top navigation priorities
- design: take a look at the left-navigation pattern and rethink
- solve the "no root page for a service" issue
- surface core tasks (TBD - send email, add to list, etc) higher up in the page hierarchy

**Comment by willeybryan** [comment]
Research: We can use the site map to find the information I can use to test with Senders. We can test the site arch and nav with people based on their mindsets and jobs to be done.
E.G. Some one coming in to write a template is going to focus on different areas then some one coming into send.
