### ISSUE TITLE
Design a system architecture for securely connecting to GCAccounts

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#460]
**Story**
The government of canada wants it's applications to use Government sign in so that it can be confident in it's consistant security. 

**What?**
- Document Our findings
~~- White paper on GC Accounts can be found here https://drive.google.com/open?id=0B6AzJ8X-IsaKNmp4RGNZUFFDSVpsVVIwb2tZcFNtVWpMeUow~~
~~- We need to figure out how to authenticate a user against Government of Canada Credential Federation (GCCF)~~
~~- Validate that Authentication can occur securely with GCKey or SecureKey with the domain https://gcaccounts.canada.ca/~~
~~- Just see if you can figure our how to connect to it in a green fields environment then make a to do list of things we need to change in Notify to connect to it~~
~~- Once informed, can we validate that this is a good idea?~~

**Why?**
- I want to be ready when they are in 2 weeks
- Security controls
- SSO is big, we need to do investigative work first.

**Comment by willeybryan** [comment]
Max's Observations:

Section 4.5 - To use MyKey without the awful java pop-up, end users must have Enturst Entelligence installed on their machine (not sure if that is standard)
Section 4.6 - To use active directory, each department needs to install a version of server running in their network (probably not used across the GC). This would be fixed if SSC provided a GC wide active directory federation server
Section 5.2.1 - A new user would register with GCAccounts rather than with us, not sure what the user flow looks like
Section 5.5.3 - We need to know what will be in those user-attr headers and if the have enough information for account creation and if that information is consistent

**Comment by willeybryan** [comment]
Help them adopt SAML https://backstage.forgerock.com/docs/am/5/saml2-guide/ ?
Gov has draft specs for SAML supposedly due out next year.

**Comment by timarney** [comment]
Given Max's comments do we have a path forward during this sprint for this?

**Comment by willeybryan** [comment]
I think we can hold off. Max's comments are the kind of snafu's we need to look our for when we try and connect to this. 

I would just like to know that, if they get an open endpoint we can connect to, what will we need to change in our Auth system to accept users/create accounts on the fly when a user comes in from the GC Accounts.

**Comment by timarney** [comment]
Won't get into all the details but we would end up updating the api to handle a token vs doing that locally. 

Likely we would still mange a users table on our end for the system details that we need.

**Comment by maxneuvians** [comment]
Returned an onboarding document to GCAccounts

**Comment by willeybryan** [comment]
I can call that done, that advances the agenda of getting this GC accounts thing off the ground.
