### ISSUE TITLE
Refine Design for last login prototype

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#463]
*Story*
When logging in for the 2nd(or more) time the first page I see shows me when I last logged in and from where. This needs to be easy enough to understand and friendly enough that I don't ignore it or have it annoy me. 

**What?**
- Last login page is up and running great, prototype design in place could use refinement
- How much usability testing is required?
- Mock up design as you see best suited for this use case

**Why?**
- Just because it is a security requirement doesn't mean it has to be hard to use, or intrusive. 

**Before**
![image](https://user-images.githubusercontent.com/46505127/69271342-a7708c80-0ba2-11ea-9cb5-15f8f358114f.png)

**Comment by willeybryan** [comment]
add a couple more and prove it is scanning correctly.

**Comment by willeybryan** [comment]
Indicate location is best guess?

**Comment by damcom333** [comment]
Events to display back to the user.

System use events to record and display back to the user.

1. Password reset initiated
2. password changed
3. 2FA added with type
4. 2FA removed with type
5. Login attempt failed (with stages, 1) failed on password, 2) failed on 2FA)
6. Successful login
7. user suspended
8. user suspension removed

**Comment by damcom333** [comment]
Remove location for now as it may generate too much confusion and traffic to our 'help desk'

**Comment by ioanacontu** [comment]
[Last-Login-FINAL.pdf](https://github.com/cds-snc/notification-api/files/3962573/Last-Login-FINAL.pdf)

**Comment by damcom333** [comment]
I'd like to include the timezone of the last login too.

**Comment by willeybryan** [comment]
Why do we think it is a good idea to include time zone?

Pros
- Lets users get an approximation of where they logged in from (E.G. if compromised from 12 time zones away it becomes easy to see)
- User in control of their time zone unlike IP location

Cons
- We don't show time zone anywhere else in the system, it just shows local time, so adding it in here is a deviation from usual UX
- Time zone still have the inaccurate risk like location, users can have their computers set to the wrong time zone.

**Comment by ioanacontu** [comment]
I noticed that the first line of the last logins is actually the current session: the one that says "A few seconds ago". Is it possible to remove it and add a third login from the past instead? 
The current session is something the user knows about.. since they are in the process of doing it? Plus, it always says the same thing "A few seconds ago". It doesn't really bring any valuable information to users and it might end up being more confusing than helpful.. unless it's there for other reasons that I'm not aware of?

**Comment by willeybryan** [comment]
Good catch, it should be past logins, not present and past logins.

**Comment by willeybryan** [comment]
![image](https://user-images.githubusercontent.com/46505127/85461693-af4a4200-b572-11ea-9ed5-907aa208270b.png)

**Comment by willeybryan** [comment]
![image](https://user-images.githubusercontent.com/46505127/85461982-018b6300-b573-11ea-8e96-56ff726a94b6.png)

**Comment by willeybryan** [comment]
![image](https://user-images.githubusercontent.com/46505127/85462276-4c0cdf80-b573-11ea-8a27-a8fc29a95e7c.png)
