### ISSUE TITLE
SMS limit reduction to lock it down a bit

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#464]
**Story**
A live service accidentally sends a ton of SMS instead of emails  costing CDS tens, if not hundreds of dollars. To avoid that we can keep SMS in trail mode.

**What?**
- Can we make SMS go live and email go live separate entities?
- They would need separate buttons

Backup plan
- Make everyones SMS limit like 100 messages a month which would cost us about $~1 and have a seperate go live process where that limit is increased. 

**Why?**
- Reduce severity of risk as risk mitigation tactic. 
- While low risk we can't control users and SMS is new to government, we have to proceed with caution.

**Comment by maxneuvians** [comment]
I have reduced this to 100,000 per year. If an SMS costs 2c in the worst case $200 per service or ~$17 a month. The annual reports for previous organisations are hard coded to 250,000 and would need to be changed but any new service will see the 100,000 limit
