### ISSUE TITLE
Sort order on these pages provides suboptimal user experience

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#465]
**Story**
When viewing dashboard usage screens users have to scroll down to the end of the year if they only started that service in the end of the year which is confusing.

**What?**
- These two pages need a fix
( https://notification.alpha.canada.ca/services/54045ec0-c0a3-4a54-ae72-23e584ad98c8/monthly )
( https://notification.alpha.canada.ca/services/54045ec0-c0a3-4a54-ae72-23e584ad98c8/template-usage )

To quickly fix this can we just blow up this page, leave the heading and replace content with
a list of usage, where the first list entry is the current month, then previous months in descending order?

- Cut it off with July 2019, as that was the first month of our instance. Pagify every 12 items. We will revisit this when we hit 48 months of operation. 

**Why?**
We don't have a lot of usage yet, no point in having years. It doesn't have to be pretty right now, just easy to ready and understand.

**Before:**
![image](https://user-images.githubusercontent.com/46505127/69269938-054fa500-0ba0-11ea-85bd-1143ac3e2541.png)

**After:**
![image](https://user-images.githubusercontent.com/46505127/69270198-8149ed00-0ba0-11ea-97ae-633b87e85469.png)

**Comment by willeybryan** [comment]
@caycefischer Can I have a design blessing on this ask?

**Comment by caycefischer** [comment]
Let's ship this, the page will need design attention once we sort out navigation and all that, but this is way better than what's currently there! strip it back, keep it simple 💯

**Comment by willeybryan** [comment]
From the PR @timarney asked

Are we working based on Financial years? - Yes, as the GC does everything this way we should to, to avoid confusion as this is an infrequent viewed area. 
1a) If we are what is the start / end month
GC Fiscal year runs April 1st to March 31st

**Comment by timarney** [comment]
Merged this - let's open a ticket for the next sprint to look at paging moving forward to handle 2020 we need to investigate if that happens automatically or not.
