### ISSUE TITLE
Process and Scripts for restoring from backups

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#467]
**Story**
When restoring Notify from backup, I want a tested process that works so I don't have to figure it out in the middle of a crisis. 

**What?**
- Process to restore our encrypted backups of Notify
- Scripts that a developer in CDS could run to restore the backups
- Developer Documentation for CDS devs

**Why?**
- Having backups is great, not having to use them is great, but we must be prepared to use them, just in case
- Security controls.

**Comment by maxneuvians** [comment]
This is a Cthulhu issue with scope creep. I am opening new issues to break them down:

https://github.com/cds-snc/notification-api/issues/564
https://github.com/cds-snc/notification-api/issues/565
https://github.com/cds-snc/notification-api/issues/566
