### ISSUE TITLE
Email Branding and application viewport size issue

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#469]
**Steps to reproduce**
- Using outlook
- Send yourself an email with this branding from Notify (https://notification.alpha.canada.ca/email-branding/6b3804b8-ed86-4a2c-9000-221ac04c2f08/edit)
- Using this setting 
![image](https://user-images.githubusercontent.com/46505127/69456685-3e6f4d00-0d39-11ea-9aa2-acc15929105f.png)

**Actual**
- Centre aligned text looks left aligned

**Expected**
- Center alignment

**Notes**
- Seems to work fine in Gmail, or Chrome.
- The bottom corner canada logo seems to help give the email a right side bounding
- It may be the case that the content is appearing next to the image instead of below it, and so this is related to #470 

Outlook Ontario Branding
![image](https://user-images.githubusercontent.com/46505127/69348333-fde1d780-0c43-11ea-90ee-1dda8c27d9d3.png)

Outlook Canada Branding
![image](https://user-images.githubusercontent.com/46505127/69348419-2538a480-0c44-11ea-9ebe-e66a0c225913.png)

Gmail Ontario Branding
![image](https://user-images.githubusercontent.com/46505127/69349078-2918f680-0c45-11ea-8295-2ff3f8b9bcea.png)

**Comment by timarney** [comment]
Tested on gov tablet - Outlook 2013.

Those tests worked.  

Screen in this issue is Outlook on Mac

@willeybryan - I'll leave this open for you to add notes and move to closed or whatever accordingly.

**Comment by willeybryan** [comment]
Tested with Gov Tablet - Outlook 2013 - 1080p No Problem - 4k Problem occurs
Tested with Linux Think pad 1080p ok - Gmail ok - Thunderbird - 4k Thunderbird has problem

I am going to close this for now as while it is an issue I don't believe it to be a priority at this time. 

From (https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam) : We can see that adoption of resolutions about 1080p is only ~6%. And this data is from a market segment where >1080p adoption is highest. If we assume all max have this problem due to high resolution (Worst case as not all have high res screens and OSC scaling corrects most issues.) OSX has an adoption of 7% https://gs.statcounter.com/os-market-share/ this means that at most %7 of people have high res screens. 

In those situations people with higher res screens are used to some weirdness as nothing is made for them yet. 

The impact of this bug doesn't effect email content or the message. 

In the mean time, Mail chimp lets you test different email clients so we can use them for future bug investigations.
