### ISSUE TITLE
Black Branding Banner in Outlook hides content

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#470]
More info in #469 

**Steps to Reproduce**
- In Outlook send yourself from Notify something with this branding https://notification.alpha.canada.ca/email-branding/6b3804b8-ed86-4a2c-9000-221ac04c2f08/edit

**Actual**
- Black banner across top of email blocks text

**Expected**
- Content appears below text in email, like when viewed in Gmail. 

**notes**
Outlook looks like
![image](https://user-images.githubusercontent.com/46505127/69348864-dccdb680-0c44-11ea-9812-0b2f59d935d9.png)

When Gmail looks like
![image](https://user-images.githubusercontent.com/46505127/69348970-02f35680-0c45-11ea-9217-bf211a99004e.png)

**Comment by timarney** [comment]
Let's close and look into it if it comes up again for a non mac outlook (giant screen user)
