### ISSUE TITLE
Draw Sender task flows

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#471]
**Story**
When we add navigate and elements to Notify we need them to be grouped based on what a sender needs to accomplish so that they can easily find the things they need to complete their tasks.

**What?**
- by mindset, create tasks flows for how they would interact with the system

**Why?**
- We can haver a cohesive user experience that fits what tasks a particular sender needs to do.

**Comment by caycefischer** [comment]
Basic task flows for core Notify actions [TASK FLOWS.pdf](https://github.com/cds-snc/notification-api/files/3892420/TASK.FLOWS.pdf)

**Comment by caycefischer** [comment]
image version ![TASK FLOWS](https://user-images.githubusercontent.com/546495/69644586-d79cad00-1032-11ea-801b-15ed6ff3cc5e.png)

**Comment by caycefischer** [comment]
image version 
![TASK FLOWS](https://user-images.githubusercontent.com/546495/69644852-382bea00-1033-11ea-8e78-0d52df138468.png)
