### ISSUE TITLE
Fix homepage typo

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#474]
*Steps to repro*
- Log out of Notify, I know know you are logged in, I always am. 
- Go to notification.alpha.canada.com, AKA the home page
- Make sure it is in english
- press command+F search for 'stystem.'

*actual*
- One result

*expected*
- I think none

**Notes:**
![image](https://user-images.githubusercontent.com/46505127/69888536-6838ee80-12ba-11ea-840f-bf501d50aa57.png)

**Comment by timarney** [comment]
https://github.com/cds-snc/notification-admin/pull/296
