### ISSUE TITLE
Help with Social media sharing

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#480]
**Story**
When sending links to our app around on linked in or facebook the preview shows limited information. I want people to know what I am sharing so I don't have to explain it. 

**What?**
- Adding some open graph tags for nice looking social links would be a good start

**Why?**
- Recent blog post announcing Notify has revealed some weaknesses in our marketing and SEO coverage

**Comment by timarney** [comment]
Please provide a title and description that we should use.
<hr>

og:title - The title of your object as it should appear within the graph, e.g., "The Rock".
og:description - A one to two sentence description of your object.

**Comment by willeybryan** [comment]
og:title "GC Notify | GC Notification" can it contain a | ?

@caycefischer can you help me out with a a one or two sentence description of Notify for social media sharing

@timarney I imagine we need french too?

**Comment by timarney** [comment]
Correct will need translations.

**Comment by timarney** [comment]
Current description says:
```
Notification lets you send emails and text messages to your users.
```

**Comment by caycefischer** [comment]
we'd say "Notify lets you send ..." right? 
and i'd replace "users" with "clients" - which is language we know some gov't departments use
though it's not... ideal. 

"users" i think is fine until we can nail down some better messaging. 

> Notify lets you send emails and text messages to your users

**Comment by timarney** [comment]
Great - updated the text.
