### ISSUE TITLE
Go Live page notes page internal update

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#483]
**What?**
- on this page change the text https://notification.alpha.canada.ca/organisations/701f5329-ad46-4147-8d3f-353772d24b95/settings/edit-go-live-notes
- Remove Zendesk ref
- Text could read "When you turn a service live please Log which services have been turned live and why you approved the change"
- Can it save to a notes field in the DB so we can pull it later? I don't want to have to hook up a zen desk. 

**Why?**
- We need to remember why we turn stuff live

**Comment by timarney** [comment]
https://github.com/cds-snc/notification-admin/pull/304

The info already saves to the database.
