### ISSUE TITLE
Auto merge to master if snyk or dependabot for all CDS repos

### ISSUE THREAD

**Issue by damcom333** [cds-snc/notification-api#485]
Let's bring the patching latency down to minutes. If synk or dependabot makes a pull request we should auto-merge it if all our tests pass. 

**Extra requirement:** Only auto-merge during regular business hours but not after 3:00 pm.  

Dan Sinclair said this is now a best practice where he works. And nobody else in the GC I think is doing it. This will give us a unique way of describing our vulnerability and patch management capabilities. 

**Notes**
There is a github merge to master action we may be able to use

**Comment by timarney** [comment]
Any concerns here:

https://snyk.io/blog/why-npm-lockfiles-can-be-a-security-blindspot-for-injecting-malicious-modules

**Comment by timarney** [comment]
@damcom333 thoughts on this + the approval step.

**Comment by timarney** [comment]
Will look into policy-bot.

https://github.com/palantir/bulldozer#can-bulldozer-work-with-push-restrictions-on-branches

**Comment by timarney** [comment]
policy-bot looks good but this ends up being a larger decision on if we want to move to policy-bot vs built-in.

Would recommend we hold and setup a meeting or something to discuss further.

**Comment by timarney** [comment]
Calling this a no go - after further discussion.

**Comment by damcom333** [comment]
Agreed.
