### ISSUE TITLE
We need to get the nightly cron celery cron job running

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#49]
**What?**
- Get the nightly job running and see what it does

**Why?**
- We need all the parts of the service up and running for evaluation

**Comment by maxneuvians** [comment]
Turns out we did not need it

**Comment by maxneuvians** [comment]
Actually got it working correctly, https://github.com/cds-snc/notification-kubernetes-deployment/commit/7ef28c60523e68721ecf7427b9983b451ff908f7
