### ISSUE TITLE
Usage page in 2020

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#491]
**What?**
- See this page? https://notification.alpha.canada.ca/services/c31680dd-8d0d-4e9f-be06-0d2f201aeaf8/usage
- Does it automatically expand in 2020? do we have to do anything?
- Hide usage page from org level 

**Why?**
- We need to validate this won't break anything

**Notes**
- you can put ?year=2020 at the end of the url then both buttons light up.

https://notification.alpha.canada.ca/services/c31680dd-8d0d-4e9f-be06-0d2f201aeaf8/usage?year=2100

**Comment by timarney** [comment]
RE:

>Hide usage page from org level

@willeybryan @caycefischer 

Does "Team members" become the new home page by default for that section.

<img width="550" alt="Screen Shot 2019-12-05 at 3 08 46 PM" src="https://user-images.githubusercontent.com/62242/70270027-79c63e80-1771-11ea-9485-b6a3ca17f194.png">

With that ... are there any more links to the usage page if not can it go away?

**Comment by willeybryan** [comment]
Nothing else links to usage as far as we currently know. We should have killed all the rest.

But nothing else shows a list of Live services for an org. We can make the homepage Tim's choice for now. 

We will need #494 to address that. We can do this now before anyone gets to this level, that would be super.

**Comment by caycefischer** [comment]
yeah make that the homepage for now, this will definitely change with the new IA though

(i don't see "trial mode services" on my account, is that a flag or something?)

**Comment by timarney** [comment]
Okay 

> But nothing else shows a list of Live services for an org

Thinking we can keep the list but change the links to go to the services dashboard page and not the usage page.

<img width="600" alt="Screen Shot 2019-12-05 at 3 39 55 PM" src="https://user-images.githubusercontent.com/62242/70272124-bac05200-1775-11ea-88f9-d8a630e8b0fc.png">

**Comment by willeybryan** [comment]
Yes please, that works for me, and lets them see the usage.

**Comment by timarney** [comment]
> yeah make that the homepage for now, this will definitely change with the new IA though
> 
> (i don't see "trial mode services" on my account, is that a flag or something?)

I'm looking via the Platform admin view so might be that.

**Comment by timarney** [comment]
Redirect is in place
