### ISSUE TITLE
New site map, same permissions

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#493]
**Story**
When implementing the new site map having access tied to an existing permissions roles will help implementation not break RBAC. 

**What?**
- see site map
![image](https://user-images.githubusercontent.com/46505127/70164815-da7d4a80-168f-11ea-823c-3c2a4aa84220.png)
- See Permissions
![image](https://user-images.githubusercontent.com/46505127/70165013-2b8d3e80-1690-11ea-8d29-0f44a58524d4.png)
- Map the permissions levels to new site map to make sure they still work
- Identify any gaps

**Why?**
- Breaking RBAC looks bad for security

**notes**
Sitemap created on
https://github.com/cds-snc/notification-api/issues/409

**Comment by caycefischer** [comment]
Updated to add pricing page (from Ioana): 
![SITEMAP NEW](https://user-images.githubusercontent.com/546495/71109004-57311e00-2192-11ea-8201-e4f5fc568ef1.png)

**Comment by willeybryan** [comment]
duped by #516
