### ISSUE TITLE
Can we 'Turn off' SMS for a service/org?

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#495]
**Story**
A service sending text message to users accidentally messes up and texts phones  costing that people money and having them suffer a tort at hands of government. 

**What?**
- Can we see if we can wrap everything for SMS and put it behind an on off switch (platform admin settings page per service?)
- Can we leave SMS in trial so it can only go to team members?
- Test to see what this breaks?

**Why?**
- Risk mitigation
- Ross Ask

**Comment by maxneuvians** [comment]
https://github.com/cds-snc/notification-admin/blob/9fd7ef74df1db7fc3b0685eaf62a757bfffe17d0/app/notify_client/service_api_client.py#L115


https://github.com/cds-snc/notification-admin/blob/d98a980b5a18118d1cde7cd194d08a1feef293aa/tests/app/main/views/test_service_settings.py#L436
