### ISSUE TITLE
When building notify we need to review changes live so it should be connected to our K8S branch review software

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#5]
**What?**
- Get CANofity working with our Branch Review app
- Dependant on Moving CANotify to K8S

**Why?**
- usability testing our own tech
- Reviewing and approving our changes made easier

**Comment by maxneuvians** [comment]
@timarney yes, also the other issue is that you can use this with public containers only. Our container images include secrets baked in so we can't actually use these.
