### ISSUE TITLE
Build live service simulation

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/notification-api#514]
We need to build a better load testing scenario. Proposing an agent that sends emails every second/minute through the system with different amount of recipients that will simulate more of an actual usage pattern ex. 8 - 5 pm, 7 - 10 pm with varying numbers of batch jobs. Can use an AWS lambda to do this.

**Comment by timarney** [comment]
@maxneuvians thinking we could do this WP Cron style https://developer.wordpress.org/plugins/cron/#what-is-wp-cron

i.e. it can fire when a user hits https://notification.alpha.canada.ca which would give us some randomness for free.

The call on load could hit a lamda function to send the templated email.  No user details passed just using the page load to trigger a request.

Thoughts?
