### ISSUE TITLE
Design dashboard to adapt to user permissions

### ISSUE THREAD

**Issue by caycefischer** [cds-snc/notification-api#516]
Permissions - what is the experience of each type of user?
- see dashboard
- send messages
- add and edit templates
- manage settings & teams
- manage API integration

**Comment by willeybryan** [comment]
Used this to close https://github.com/cds-snc/notification-api/issues/493 as dup
this approach slices the permissions into vertical agile segments and is better than original audit approach

**Comment by willeybryan** [comment]
Broken down into next iteration of site arch work
