### ISSUE TITLE
Get sign off on SoS

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#524]
**What?**
- Ross and Anatole need to sign off on Statement of Sensitivity
https://gcdocsp/gcdocs/llisapi.dll?func=ll&objaction=overview&objid=36736560

**Why?**
- Protected A

**Comment by willeybryan** [comment]
Getting other half signed in this sprint

**Comment by damcom333** [comment]
The SoS was signed by Anatole.

**Comment by damcom333** [comment]
https://gcdocs.tbs-sct.gc.ca/gcdocs/llisapi.dll/37303293/Notification_SoS_-_Alpha_Signed.pdf?func=doc.Fetch&nodeid=37303293&viewType=1
