### ISSUE TITLE
Update Your Amazon RDS SSL/TLS Certificates by February 5, 2020

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#526]
**Story**
When connecting to Amazon RDS we need the connection to remain encrypted and functional so that stuff doesn't break creating more work.

**What?**
- Update Your Amazon RDS SSL/TLS Certificates by February 5, 2020

**Why?**
- Cert updates gotta happen

**Comment by maxneuvians** [comment]
Completed
