### ISSUE TITLE
Add another what? - Context specificity in french

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#527]
**Story**
When adding addition emails and phone numbers to safe lists in french, users should be informed of what they are adding on the button to maintain legal language reqs. 

**Page & Problem**
https://notification.alpha.canada.ca/services/14c88598-7e24-4ba2-ab3f-e06f59002662/api/safelist
- The string FR Add another is used twice but can’t be translated the same way in both cases. 
- The string FR remaining follows the number 3 but should precede it in French.

It should read:
Ajouter une autre adresse courriel (il en reste 3)
Ajouter un autre numéro de téléphone (il en reste 3)

**What?**
- Dev: Come up with minimum viable technical solution
- Design: See how it can best fit in

**Why?**
- OLA

**Comment by timarney** [comment]
We might have more flexibility if we move the label outside of the button. 

<img width="756" alt="Screen Shot 2020-01-14 at 2 36 31 PM" src="https://user-images.githubusercontent.com/62242/72376068-4dd89a00-36db-11ea-97d5-6f3511ccd8d4.png">

@ioanacontu @caycefischer super open to ideas

**Comment by ioanacontu** [comment]
![Frame 1](https://user-images.githubusercontent.com/56094538/72384689-fb53a980-36eb-11ea-8711-e71f36892ef2.png)
What about this? --> changes in **P!nk** 
Literally I take out "address" from the email fields so that everything stays as _noun masculine_. 
I don't know yet about the (3 remaining) part.

**Comment by timarney** [comment]
Okay here's what the code looks like for this.

```
{{addAnotherTranslation}} {{listItemName}} ({{entriesLeft}} {{remainingTranslation}}
```

If @ioanacontu suggestion fixes the issue - that sounds like a much easier path.

```
ListEntry.prototype.addButtonTemplate = Hogan.compile(
    '<button type="button" class="button-secondary list-entry-add">{{addAnotherTranslation}} {{listItemName}} ({{entriesLeft}} {{remainingTranslation}})</button>'
  );

```

**Comment by timarney** [comment]
https://github.com/cds-snc/notification-admin/pull/333

**Comment by timarney** [comment]
English is updated.

I'll make a separate PR to ensure we have the latest .po file at which point we can update the french. 

<img width="400" alt="Screen Shot 2020-01-17 at 8 06 14 AM" src="https://user-images.githubusercontent.com/62242/72614430-46dea100-3900-11ea-89a5-055578adf278.png">
