### ISSUE TITLE
Deploy Traffic Monitoring inside EKS

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#529]
**Story**
When evaluating Notify's systeme integrarity and security SRE's like to use inter container traffic to as a check. SO we should start monitoring this. 

**What?**
- Evaluate and improve network security (subnets, policy groups, traffic inspection)

**Why?**
- Could eventually lead to policy bot to make sure we send safe emails
- SRE team ask

**Comment by maxneuvians** [comment]
The decision to deploy something like Istio is outside of the scope of notify
