### ISSUE TITLE
Reserve SMS short code for Notify

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#530]
**Story**
When getting sms from Notify people would be less likely to think it is spam if it always came from the same number.

**What?**
- Figure out if we can get a short code
- Reserve codes
226232 = Canada
237762 = CDSSNC

**Why?**
- People thinking it is spam won't treat it as real

**notes**
https://docs.aws.amazon.com/sns/latest/dg/sms_shortcodes.html

"Short codes for Canada will incur a one-time setup fee of $3000 USD. Each short code has a recurring charge of $995 USD per month. Carrier approval may take 12-16 weeks or longer. Please note that billing for short codes start at the time the application is submitted, before the short code is registered for use. The default send rate for short codes is 100 messages per second maximum. A higher send rate will incur additional charges." -- info from AWS on short codes in canada.

**Comment by maxneuvians** [comment]
Needed content:

```
For Use Case Description, summarize your use case, and summarize how your recipients will sign up for messages sent with your short code.
```

```
A customer service associate will contact you for additional information about your use case, including the customized messages your audience members will see when they reply to your short code with HELP or STOP. AWS will work with wireless carriers on your behalf to provision your short code. It typically takes 6 - 12 weeks for all carriers to approve your use case and provision the short code so that you can send messages to the subscribers in their networks. AWS will notify you when the short code provisioning is complete.
```

Also this needs to happen on our production account.

**Comment by obrien-j** [comment]
Have gotten contacts and material from several Tier1 Aggregators, as provided by the CWTA (can wiireles telco assoc).

Investigating what the process is for acquiring codes, provisioning, and costs associated with bulk providers vs existing partners.
