### ISSUE TITLE
Update the Google Analytics ID

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#54]
**What?**
- Right now our Notify instance seems to be using the GA of Gov.uk Notify, we need to fix that
- Rip it out
- Replace it with our own if we can

**Why?**
- We don't want to send data to Gov.UK
- We want to collect our own analytics data

**Notes**
- If there isn't one to use or we can't just generate one, let me know and I will talk to outreach

**Comment by maxneuvians** [comment]
Closed i nhttps://github.com/cds-snc/notification-admin/pull/25
