### ISSUE TITLE
Plannig Research about API in Notify

### ISSUE THREAD

**Issue by AntoineGarciaSuarez** [cds-snc/notification-api#550]
research plan
https://docs.google.com/document/d/1pHV4aoNQKu3BfFGa2Iui78uIW8HvU-V34tGaHKBg11U/edit

**To Do**
- Plan research for running a developer through sending an email
- Interview guide
- Maybe send them an exercise before the interview

**Comment by timarney** [comment]
@AntoineGarciaSuarez 
@willeybryan 

Anything left to do here?

**Comment by willeybryan** [comment]
LGTM
