### ISSUE TITLE
Check boxes on sign up for research and marketing communication

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#552]
*Story:*
When signing up we should ask users these questions so we don't have to expand effort later to find that out. 

**What?**
- On this page https://notification.alpha.canada.ca/register
Ask some how:

Do you want to participate in our user research studies?
Do you want to receive outreach and updates on GC Notify?

- Ask them in french too please

- if this could be stored some where, perhaps as a bool on the user or something

**Why?**
- We need this data in a CRM eventually
- Manually asking people this for research is time consuming and soon we will have to do it for marketing too
- Some one asked to be removed from our mailing list after signing up  so asking for their consent before hand seems like an easy way to prevent that response.

**Comment by timarney** [comment]
Wondering if we should look at options that would capture outside of the signup flow.

Some sort of alert for i.e for status messages or other things we might want to draw attention to.

Something more "general purpose".



<img width="668" alt="Screen Shot 2020-01-14 at 1 55 17 PM" src="https://user-images.githubusercontent.com/62242/72373181-c177a880-36d5-11ea-9709-910eefd7f653.png">
<img width="646" alt="Screen Shot 2020-01-14 at 1 55 04 PM" src="https://user-images.githubusercontent.com/62242/72373182-c177a880-36d5-11ea-8c67-44eb68ea0d7e.png">


Also would we need unsubscribe functionality?

**Comment by timarney** [comment]
If not the above if we go the checkbox route:

Do we need unsubscribe functionality? 
Would this show up under the settings page?
Will this need to be removed again at some point?

**Comment by willeybryan** [comment]
Those alert messages are great, but I want to save things like that for actual alerts. The check boxes can be moved to stuff later. 

1) Unsub is not a priority yet as it will just be us emailing them at first personally
We can put one in later in a users account, I will put it on the backlog

2) If we can put it in the user settings not service settings, I want the value to be set per unique email that signs in

3) Probably, we may want to expand it later into some other things, perhaps build a notify wide unsub, 


This is just ment to be an easy solution for now that lets us collect this information to save us a step.

**Comment by timarney** [comment]
For the record there is no easy for this project.  Most updates touch multiple repos and many files.

That said - will get it done :)

**Comment by willeybryan** [comment]
Blarg! right ok, I will try and keep that in mind and come back to check this PR so I can get a feel for the scope I was asking for.

**Comment by timarney** [comment]
Will track here:
Step 1: Added column to the database 
https://github.com/cds-snc/notification-api/pull/568

**Comment by caycefischer** [comment]
Copy tweaks for this screen:

![image](https://user-images.githubusercontent.com/546495/72545812-a16ff280-3857-11ea-904a-b81912957c81.png)

- Password helper text: `Should be at least 8 characters long`
- checkbox 1: `I want to participate in user research studies for Notify`
- checkbox 2: `Send me newsletters about new features and updates`

**Comment by timarney** [comment]
Noting from Slack.

> For now, I’d suggest to remove it as it can dammage the onboarding experience; and I will suggest other ideas @AntoineGarciaSuarez

**Comment by timarney** [comment]
Removed the dev label from this as we don't know the path forward.
