### ISSUE TITLE
Bug: Creating from existing template causes error saying to select template

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#553]
**Steps to reproduce**
- Navigate to template page of a service with email templates
- Check a box next to an existing template
- Select add tempalte
- Select copy existing template
- Click Green button

**Expected**
- Copies selected template

**Actual**
- Error, you should select a template

**notes**
- If I select no templates, it takes me to a template picker from all services, Can we confirm non platadmin users don't see this?

**Comment by timarney** [comment]
Navigated to https://notification.alpha.canada.ca/services/c05f1302-19fa-4245-b906-5fcf53499638/templates

Click the checkbox next to the 1 existing template.

Available buttons are `Move` and `Add to new Folder`

I don't see  `Select add template`

### Screenshot
<img width="300" alt="Screen Shot 2020-01-09 at 7 47 48 AM" src="https://user-images.githubusercontent.com/62242/72069218-b1666000-32b4-11ea-9b2c-79c99d7a84e7.png">

**Comment by willeybryan** [comment]
Apologies, Mixed up steps

1. Navigate to template page of a service with email templates
2. select add template
3. Check a box next to an existing template
4. Select copy existing template
5. Click Green button

**Comment by willeybryan** [comment]
Which may mean it isn't a feature we want to support, but like the error message is crap then
Recreating here: https://notification.alpha.canada.ca/services/c31680dd-8d0d-4e9f-be06-0d2f201aeaf8/templates
![image](https://user-images.githubusercontent.com/46505127/72079470-fac0aa80-32c8-11ea-844a-aceec6a3920b.png)

**Comment by timarney** [comment]
Let's reach out to design on this.

The workflow for making a new template isn't  based on selecting the templates above.  Seems like those checkboxes shouldn't be clickable if the expectation isn't to check on of them to copy from.

**Comment by willeybryan** [comment]
kk calling @ioanacontu @caycefischer when you get a chance can one of you take a look at this user flow and advise on a quick fix. 

We can add a longer term fix tom the backlog. Not a super high priority as I imagine few people are clicking this right now

**Comment by timarney** [comment]
To summarize:

1. Navigate to template page of a service with email templates
2. select add template
3. Check a box next to an existing template
4. Select copy existing template
5. Click Green button

If the user doesn't select a template from the "first" screen the copy template actually works.

Is the solution to grey out the checkboxes if you click add template.

**Comment by willeybryan** [comment]
That seems like the easiest, cheapest solution when compared to effectiveness and was my default thought too, but I had a think and wrote out my thoughts. 

Our goal here is to prevent people having that problem, seeing that error, and submitting a support issue, which we then have to process, which is labour intensive. Due to lack of resources it is in our interest to minimize support labour. 

The risk however that any visual change in the check boxes will draw the eye, and then the user will be like, oh why can't I click these? Are my templates different? and then creating a support issue.

Mitigation idea: Could we, ignore their check mark?
So it takes you to a select page, and then a user in most of our mindsets would get confused for a second, because they thought they selected a template. But then they just select the template again, and move on with their life rather then submitting a support issue. If they are off the explorer mindset go back and play with it, they discover that isn't how it works, and the checks are for something else.

Thoughts?

**Comment by timarney** [comment]
Thought on ignoring the checkbox if checked would be after you press the button you are than asked to find a template to copy.   Which might make the user think - didn't I already select one?

**Comment by timarney** [comment]
If that section were separated out more it might feel like 2 different workflows more.

**Comment by willeybryan** [comment]
Yep, that "didn't I already select one" is the confusion I figured they would hit.

I imagine given how excellent current gov enterprise software is and how low usage this feature is, we can get away with a less than 100% solution for now, and figure out the two workflows later when we come back around to refactoring this area's UX.

**Comment by timarney** [comment]
How about a new button "copy template" which would direct you to http://localhost:6012/services/e609f6b0-0390-45b0-aaae-f4cc92c713e4/templates/copy

The option to copy under the new template would be removed.

<hr>

<img width="632" alt="Screen Shot 2020-01-09 at 1 15 05 PM" src="https://user-images.githubusercontent.com/62242/72093340-2e5bfe80-32e2-11ea-97cc-bccab6074e16.png">

**Comment by willeybryan** [comment]
Yeah that works for me! Easy and will do for now
