### ISSUE TITLE
Get rid of links out to GDS from https://notification.alpha.canada.ca/features/terms

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#556]
**story**
When accessing a canada.ca site for Notify If I click a link that takes me to a gov.uk site I am going to be confused. 

**What?**
- This page links out to Gov.uk https://notification.alpha.canada.ca/features/terms
- kill this whole part
"Consider when to send emails or text messages and how to write them. You can read more about this in the GOV.UK Service Manual.

GOV.UK developed the original notification system. Canada’s Notification team recommends following the UK guide, while adjusting for the Canadian context."

**why?**
- We need to decouple from them
- We can't rely on people to read that, we are using templates to guide them.

**Comment by timarney** [comment]
So the updated text would start with you must?

## When using Notification

You must:

- complete all security steps required by your organization.
- tell us immediately if you have any security breaches.

**Comment by willeybryan** [comment]
Yes, but can we also add above both of those "Follow Canadian law with regard to the privacy act when using this software"
