### ISSUE TITLE
Prototype and load test a celery worker far-gate pod in AWS

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#557]
**Story**
When stuck using celery we might as well make the best of it and explore reducing costs during down time with fargage

**What?**
- Prototype up a celery k8s process in farget

**why?**
- test
- redundancy
- Explore fargate as an option

**Comment by maxneuvians** [comment]
According to http://fargate-pricing-calculator.site.s3-website-us-east-1.amazonaws.com/ One celery worker will cost $20 a month. This is not economical as we can run probably 20 workers on a $70 a month machine. This becomes reasonable when you need to burst workers - which is the correct use case.

**Comment by maxneuvians** [comment]
Closed in https://github.com/cds-snc/notification-tf/pull/5
