### ISSUE TITLE
Investigate incorrect stats counts for StatsD exports in Cloudwatch metrics

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#558]
**Story**
When viewing cloud watch I want the stats to be accurate so I don't draw the wrong conclusions

**What?**
- See our https://console.aws.amazon.com/cloudwatch/home

**Why?**
- Could be a symptom of a bigger issue

**Comment by maxneuvians** [comment]
Think I found the right config will test

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-custom-metrics-statsd.html

**Comment by maxneuvians** [comment]
Increasing the resolution seems to have fixed the issue
