### ISSUE TITLE
Hide UI elements that reference Letters for now

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#57]
Dependency https://github.com/cds-snc/notifier-api/issues/43

**What?**
- Remove references to Letters in the UI
- See the list of places in https://docs.google.com/document/d/1oYgxP4K-xlN-hfE2bELWdUoJ70wtsssRaZvao1eNjyg/edit?ts=5d2382d6#

**Why?**
- Integration with letter sending is complex for minimal benefit
- We may add in letters later, but there is a lot of work and testing that can be done before that phase

**Comment by willeybryan** [comment]
Cut this entire thing from settings

![image](https://user-images.githubusercontent.com/46505127/60915074-f273ae00-a258-11e9-8271-a038b0ec9695.png)

**Comment by willeybryan** [comment]
Remove letters sent from dashboard and expand the other boxes into a 2 column layout

![image](https://user-images.githubusercontent.com/46505127/60918742-08d23780-a262-11e9-83ee-4949c1dd1b8a.png)

**Comment by timarney** [comment]
Noting:
We're going to turn off send_letters as the Database permissions level.  That is to say by default letters will be turned off.

Any UI wrapped that checks for that permission will turn off.  This will help if we want to enable the feature later.  There will be sections i.e. the HomePage where the user isn't logged in where we'll still need to remove letters from the text content.

cc @maxneuvians -
