### ISSUE TITLE
Put Calendar behind send now and send later: Default send now

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#575]
**Story**
When Sending a email blast I want to be able to send now or send later so that I don't have to see and read a calendar every time I send an email blast

**What?**
- Show send now and send later, Upon a user clicking send later expand to show the calendar
![image](https://user-images.githubusercontent.com/46505127/72919869-38382580-3d16-11ea-8925-aee160528197.png)

**Why?**
- Always showing the calendar for what is an edge case to the user is bad UX

**Comment by timarney** [comment]
@brdunfield as discussed if you can start syncing the Notify version of the Calendar with the changes from booking that would be great.

https://github.com/cds-snc/notification-scheduler


@ioanacontu @anikbrazeau 

Hopefully we can take a look at this on Wednesday from the design end of things.

RE: Send now, send later.
