### ISSUE TITLE
Add common contact use cases to form 

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#577]
**Story**
When providing feedback I want to categorize my feedback so that I feel like my concern will be heard in the appropriate context. 

As a PM collecting user feedback, I want to be able to categorize it so that I can run analysis.

**What?**
Ad a subject line with these options to the contact use form as a subject line drop down

Options
- I need help - Ask a question - Give feedback - Set up a demo - Go Live - Other

- French too, but only on french lang selected

**Why?**
- One day we will get an issue tracking system and we need to work slowly towards a world in which that exists.

**Comment by timarney** [comment]
@caycefischer @AntoineGarciaSuarez @ioanacontu please confirm what we want to use for the dropdown options

> I need help - Ask a question - Give feedback - Set up a demo - Go Live - Other

**Comment by timarney** [comment]
Can someone update this with where we landed from all the Slack comments

Was it?
Ask a question
Give feedback
Set up a demo

**Comment by caycefischer** [comment]
- Ask a question
- Give feedback
- Request a demo

**Comment by timarney** [comment]
https://github.com/cds-snc/notification-admin/pull/351
