### ISSUE TITLE
Collecting any PII means Privacy Statement

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#578]
**Story**
When creating a Notify account I want to know that my information will not be shared without my consent so I can trust the software to be legally compliant with the privacy act.

**What?**
Add to account creation screen, at the bottom, as like fine print, but obviously accessible legibility and size please add

ENGLISH
You're creating an account for GC Notify, so you can choose to stop using it at any time for any reason.

We (the Canadian Digital Service) will make sure your responses are confidential, which means they will not be linked back to anyone.

Your participation will not impact your relationship with the Canadian Digital Service or any part of the Government of Canada.

We handle all personal information in accordance with the Privacy Act, and we'll give you a copy of our Privacy Statement.

**Why?**
- Legal req
- Trust

**Notes**
FRENCH
Vous vous créez un compte pour GC Notification, vous pouvez donc choisir d'arrêter de l'utiliser à tout moment pour n'importe quelle raison.

Nous (le Service numérique canadien) veillerons à ce que vos réponses soient confidentielles, ce qui signifie qu'elles ne seront reliées à personne.

Vos réponses n'auront aucune incidence sur votre relation avec le Service numérique canadien ou toute autre partie du gouvernement du Canada.

Nous traitons tous les renseignements personnels conformément à la Loi sur la protection des renseignements personnels, et nous vous remettrons une copie de notre Déclaration de confidentialité.

**Comment by caycefischer** [comment]
> You're creating an account for GC Notify, so you can choose to stop using it at any time for any reason.

> We (the Canadian Digital Service) will make sure your data and and correspondence are confidential, which means they will not be linked back to anyone.

> Your participation will not impact your relationship with the Canadian Digital Service or any part of the Government of Canada.

> Please read our [Privacy Statement](#LINK). We handle all personal information in accordance with the Privacy Act.

some quick, easy changes. probably don't need to run this past legal/policy but... maybe?

**Comment by timarney** [comment]
> Please read our Privacy Statement. We handle all personal information in accordance with the Privacy Act.

@willeybryan we can't link this yet correct?

**Comment by willeybryan** [comment]
@timarney  can we link it out to https://digital.canada.ca/legal/privacy/ ?
That should cover us for now.
