### ISSUE TITLE
Services created in two languages need to have an email address that supports that

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#58]
**What?**
- When creating a service you use this page https://notification.cdssandbox.xyz/add-service
- Naming your service creates the email address.
- Email addresses must be bilingual
- We need an explanation on this page that your service name must be in both official languages
- Example: "Emails will have a from address based on the name of your service. Please name your service in both official languages (English-French)"

**Why?**
- Users sending one message with both languages in it has to come from a bilingual Email

**note**
- Should also update it here https://notification.cdssandbox.xyz/services/c31680dd-8d0d-4e9f-be06-0d2f201aeaf8/service-settings/name

**Comment by maxneuvians** [comment]
@willeybryan is it enough to be able to set the reply-to address?

**Comment by willeybryan** [comment]
Maaaaaybe. 

We may also just be able to have people create their service in both official languages, because the service name becomes the email name. So we may just be able to get away with an instruction to do that. 

I want to see what @sboots has to say on #37 for the email standard first.

**Comment by willeybryan** [comment]
@YedidaZalik 
I could use your input on this ticket. When naming a service it creates the From address. The From address needs to be in both official languages.

We need to write something on the page to reflect that.

**Comment by YedidaZalik** [comment]
Okay, let's have our meeting with Sean tomorrow to help me suss out the "service" issue in English and then I will include this ticket #58 in the follow-up work to that meeting.

**Comment by timarney** [comment]
Any follow up for this?

**Comment by willeybryan** [comment]
The content on the change service page is much nicer 
![image](https://user-images.githubusercontent.com/46505127/62305521-21430580-b44e-11e9-9b10-286e10ffd41c.png)
Can we add the Users will see the service name: part with its bullet points?
- Except change users to Recipients?

**Comment by YedidaZalik** [comment]
@willeybryan Please let me know if this works (I would like the bullets to be round, but they are showing up as hyphens in github):

**Name your service in both official languages**
Notification displays your service name:

- at the start of every text message
- as the ‘from’ address on emails you send

Your service name cannot be longer than 255 characters. It must include both English and French.

For example:

- Canadian Digital Service (CDS) | Service numérique canadien (SNC) 
- cds-snc.ca

What’s your service called?
You can change this later.

**Comment by willeybryan** [comment]
Works for me! Lets just make sure we update it in both places. I will add the change service name spot to the ticket.

**Comment by timarney** [comment]
@YedidaZalik @willeybryan 

Like this?

<img width="818" alt="Screen Shot 2019-08-13 at 1 19 23 PM" src="https://user-images.githubusercontent.com/62242/62962481-04eb8500-bdcd-11e9-8ce2-81b4cdb152a5.png">

**Comment by willeybryan** [comment]
LGTM!

**Comment by YedidaZalik** [comment]
LGTM2!!

**Comment by YedidaZalik** [comment]
I don't actually see this on the 'Add service' page https://notification.cdssandbox.xyz/add-service

**Comment by timarney** [comment]
@YedidaZalik just checking via a screenshot ... will push after the demo later today.

**Comment by YedidaZalik** [comment]
@timarney Great because sorry to be so annoying but I saw something I'd like to change. I used "cannot" and proper web practice is to use contractions, so "can't". So that makes me want to change that whole middle paragraph to 
"Your service name must include both English and French. It can't be longer than 255 characters."
