### ISSUE TITLE
Limit Alarm to Notify Ops slack

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#581]
**Story**
When services hit limits (# of emails, 10k) we want to be apprised so we can investigate and ensure that the recipients aren't impacted negatively. 

**What?**
- Ship a limit alarm to Notify ops with what service hit what limit

**Why?**
- We don't want a service in the future to hit a limit and shut down and now one noticed leading to people not getting important updates

**Comment by timarney** [comment]
The code part of this is done.  

AWS setup needs to be completed - watch for log events.

**Comment by damcom333** [comment]
Would be awesome if the finding could show up as a AWS security hub finding. https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-findings-format.html

**Comment by willeybryan** [comment]
Why would it be awesome? whats the benefit?

**Comment by damcom333** [comment]
The benefit would be to centralize where we receive alerts. Sometimes we get alerts in slack, somethings we get them inside AWS, sometimes we get them via email. The triage process could be simpler if all issues funnelled into the same place. Thinking about the long term maintenance when I say this. @sboisvert

**Comment by willeybryan** [comment]
A central location makes sense for lowering burden of knowledge for support teams. If Stéph wants it there then we can port it there.
