### ISSUE TITLE
API .NET

### ISSUE THREAD

**Issue by noone63** [cds-snc/notification-api#593]
I have a C# application but all I see is the API in JAVA on canada site. I followed the link to get the API in .NET, but it required an API key, and an UK gov email is required to get an API key. So, how could I use the API in .NET !?

**Comment by timarney** [comment]
The API clients are all the UK version but there is an undocumented "baseUrl" parameter that you can use to reach our endpoint.

Set the endpoint to the Canadian API and you should be all set.
```
https://api.notification.alpha.canada.ca
```

```
public NotificationClient(string baseUrl, string apiKey) 
```

https://github.com/cds-snc/notification-api/wiki/How-to-change-your-API-endpoint%3F#net

**Comment by timarney** [comment]
Closing this issue.

We can re-open if the above did not solve your issue.
