### ISSUE TITLE
Admin Change Log File

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#594]
**Story**
When auditing Notify security I want to make sure that an admin hasn't misused their power to protect the system from misuse.

**What?**
- Attach a way to track WHO committed WHAT admin api call in a log showing WHEN
- Log needed for period review so it doesn't need a fancy interface
- We want to track when platform admin stuff in these spots is triggered sections:
https://notification.alpha.canada.ca/platform-admin
https://notification.alpha.canada.ca/organisations/701f5329-ad46-4147-8d3f-353772d24b95/settings/
https://notification.alpha.canada.ca/services/c31680dd-8d0d-4e9f-be06-0d2f201aeaf8/service-settings

**Why**
- If some one changes a setting that causes a problem we need a trail to trouble shoot and trace it back. 
- If an admin is found to be untrusty worthy we can investigate other instances for potential misuse.

**Comment by timarney** [comment]
Start here:

https://flask-sqlalchemy.palletsprojects.com/en/2.x/config

```
SQLALCHEMY_TRACK_MODIFICATIONS
```
