### ISSUE TITLE
Performance dashboard

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#596]
**Story?**
When showing people the power of Notify I want to show them a dashboard so I can be confident in their understanding of it's offering. 

**What?**
- Fork This https://www.gov.uk/performance/govuk-notify
- Connect it to ours
- Leave out the service list for now
- Leave out letters
- Make sure it works
- Put Alpha Sticker on it
- attach it to /performance ?

**Why?**
- https://gcdigital.slack.com/archives/CR9E3U95F/p1579806509015300?thread_ts=1579804165.015200&cid=CR9E3U95F

**Comment by timarney** [comment]
> confident in their understanding of it's offering

From my end I don't see how showing the # of notifications sent help with people "understanding of it's offering"

I also don't think our volume is high enough at the moment to warrant build a dashboard.

**Comment by timarney** [comment]
I would prefer if we modified the the platform-admin landing page

https://notification.alpha.canada.ca/platform-admin?start_date=2018-01-01&end_date=2020-02-01

And added a filter to ignore the CDS simulator and other services as need be.

<img width="833" alt="Screen Shot 2020-02-05 at 8 15 02 AM" src="https://user-images.githubusercontent.com/62242/73844973-a2a99500-47ef-11ea-97c8-e37692e99789.png">

**Comment by willeybryan** [comment]
I am all for making the MINIMUM viable product. 

We need something out there so we can collect feedback on (or show there is little to no interest in) dashboards)

So as long as we can track views and put a feedback form on it I am ok (Which i imagine if we don't put it behind auth because GA)

**Comment by timarney** [comment]
Will build out something simple for now - utilizing some of the code from the stats email.

**Comment by timarney** [comment]
From the development end.

We now have an endpoint we can hit to give us data for a few metrics
```
{"overall":387,"last_week":36,"this_week":"0","total_services":9}
```
See:
https://xe8bci46uc.execute-api.ca-central-1.amazonaws.com/prod

To move forward with a full Dashboard we'll need design and others involved to figure out what we want to show and how + any policy level stuff to figure out if we're allowed to show.  

With what I have setup + deployed to AWS we can adjust as need be moving forward.

Given the other work design needs to do in this sprint going to close this and we can open up a new issue once we have everything sorted out.

We also have the metrics emails which will give us the same stats for now.
