### ISSUE TITLE
Update Performance Dashboard

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#597]
**Story**
When showing of a dashboard it should look like the Notify home page so the logged out user experience looks the same. 

**What?**
- Implement Figma designs from #599 

*Stretch Goal*
- French filled in with google translate

**Why?**
- Bare minimum to make it look polished enough to show off as an 'Alpha'

**Comment by timarney** [comment]
Prior to this from the design end we should.

1) Confirm the homepage design (especially the header, footer, mobile navigation).
2) Design / confirm the navigation for a logged in and "Platform Admin" view
3) Confirm layout / colours for Dashboard boxes.

We also need to layout the other signed out pages once the Homepage designed is confirmed i.e. documentation etc...

**Comment by willeybryan** [comment]
Yes, sorry this is dependant on #596 being done so it will be in a later sprint once Ioana is back
