### ISSUE TITLE
When submitting forms that call ZenDesk we should replace it with a Simple contact method for now so meet immediate needs

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#60]
Support page and form changes are on ticket https://github.com/cds-snc/notification-api/issues/68

**What?**
- (/service-settings/request-to-go-live/estimate-usage), (/branding-request/email) (https://notifier.cdssandbox.xyz/support/report-problem),(https://notifier.cdssandbox.xyz/support/ask-question-give-feedback) all use Zen Desk
- We need to remove links to Zen Desk. 

- Cut Email Branding
![image](https://user-images.githubusercontent.com/46505127/60914873-72e5df00-a258-11e9-893f-f787ee4c05c2.png)

- Change Request to go live to contact us with link to /support in order to stream line
![image](https://user-images.githubusercontent.com/46505127/60914940-9577f800-a258-11e9-85f2-c244059fdca1.png)

**Why?**
- We need to keep support just scale it back to immediate need so that is on https://github.com/cds-snc/notification-api/issues/68
- Go live can be handled manually for as we need to figure out payment it is still a ways away. 
- We can add in Email branding later and do it differently then having it create a support ticket some where. 
- Change to Platform Email CDSPlatform.PlateformesSNC@tbs-sct.gc.ca

**Comment by willeybryan** [comment]
@timarney I saw you dropped this in, I turned it to an issue and want to fill it out. 

I was wanted to confirm where it uses Zendesk?
is it in the 'Tell us how many messages you expect to send' in the 'request to go live' area? /service-settings/request-to-go-live/estimate-usage

If so is the option to have that sent out as an email instead?

**Comment by willeybryan** [comment]
I imagine these may also use zendesk https://notifier.cdssandbox.xyz/support/report-problem and https://notifier.cdssandbox.xyz/support/ask-question-give-feedback

**Comment by timarney** [comment]
Yes they do.

 First one (is when you request a template / branding for your service)
<img width="1087" alt="Screen Shot 2019-07-09 at 1 01 48 PM" src="https://user-images.githubusercontent.com/62242/60908393-c13fb180-a249-11e9-9c53-439a522690b5.png">

**Comment by willeybryan** [comment]
Yeah I see that now, under /branding-request/email
