### ISSUE TITLE
Homepage English Content

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#600]
**Story**
When viewing the home page users want to have their questions answered before they can think to ask them

**What**
- Revise english content for homepage based on Antoine's research and team feedback
- Things like: Cut scary code bits, avoid selling it as a mail chimp/mail merge replacement, Cut references to MS Office programs, and others from research & Feedback
- Figure out graphics
- We need CDS graphic in there
- Put it in Figma for Tim?

**Why?**
- Home page is main selling feature we need to get this live

**Comment by anikbrazeau** [comment]
Copy : https://docs.google.com/spreadsheets/d/1lBC7YJTAqYdWYMYuozb18Cs17MlFPcLPoFd1BHDRW8k/edit#gid=1728996690

Wireframes : https://www.figma.com/file/dxn3FzTMOoBzqFWiJxZMhc/Homepage-for-DEV?node-id=395%3A27
