### ISSUE TITLE
Critical metrics email

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/notification-api#602]
**What?**
Create a weekly critical metrics email that shows the difference between two weeks with a green or red arrows showing the % trend and absolute number.
- Notifications sent by live services
- New Notification services

**Why?**
- Growth tracking
- Sprint notes updates to leadership

**Comment by timarney** [comment]
For now tracking - 
Sent last week
Sent this week + Overall

Pushed up as a Lamda - will test sending to myself.

Will update to send once a week.
