### ISSUE TITLE
Support International.gc.ca development of GC Notify connection

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#603]
**What?**
- We had an idea of how we could connect their system to ours without server install
- Work with them to see what we can do and what is involved in helping them
- Spend some agreed upon time helping.

**Comment by sboisvert** [comment]
@willeybryan If I understand correctly @mcman12 will put me in touch with them, correct?

**Comment by willeybryan** [comment]
Yes

**Comment by timarney** [comment]
@mcman12 @sboisvert any progress on this?

**Comment by sboisvert** [comment]
Meeting has been pushed back to Wednesday at 2pm cc @mcman12
