### ISSUE TITLE
Add events to security hub

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/notification-api#604]
AWS security hub is our single pane of glass for security events. We should add custom events from the application to raise awareness into AWS security hub.

**Support Req**
- Make sure we can have those events pushed to a 3rd party support system.

**Comment by damcom333** [comment]
Add a security finding for any notify services that goes live, or any admin setting changed. For example when gmail.com gets added to the approved list, PII detected. 

Link this effort to [issue](https://github.com/cds-snc/notification-security-playbook/issues/15)
