### ISSUE TITLE
Implement new homepage as test to see what breaks

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#605]
**Story**
When visiting Notify we want people to feel invited to use it so that they stay a while and read the page. 

**What?**
- New homepage tech may break layout
- Test new layout from Figma in live page

**Why?**
- Home page is a marketing tool for us
- Home page needs to look like Canada.ca design to not draw the wrong kind of attention
- Technically a beta req

**Comment by timarney** [comment]
Works - will come up with a strategy for the forms to minimize the work that will be needed on that end.
https://notification-homepage-lpj1trqc.herokuapp.com

**Comment by willeybryan** [comment]
- strategy for the forms
 Looks at form

it's so cute and tiny

![image](https://user-images.githubusercontent.com/46505127/73945710-bbcf4600-48c2-11ea-81fa-bab9c6d84e36.png)
