### ISSUE TITLE
the FIP must flip to meet OLA req

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#607]
**Steps to Reproduce**
- Navigate to notification.alpha.canada.ca?lang=fr

**Expected**
- Federal Image goes flag -> french -> English so that it is french first compliant

**Actual**
Flag -> English -> French

**notes**
This thing 
![image](https://user-images.githubusercontent.com/46505127/74056894-d4b62500-49b0-11ea-8957-cd29977b9b4d.png)

**Comment by timarney** [comment]
Should flag for the CDS website as well -> https://github.com/cds-snc/digital-canada-ca

Can you flag where you found it mentioned as well?

**Comment by willeybryan** [comment]
Where I found it mentioned? You mean like here:
https://www.canada.ca/en/treasury-board-secretariat/services/government-communications/federal-identity-program/manual.html#toc11-7

Some one reported this as a bug to the inbox

And Yeah I can flag that on the website repo

**Comment by timarney** [comment]
https://github.com/cds-snc/notification-admin/pull/357
