### ISSUE TITLE
Translate Form request type and options

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#608]
**What?**
- Home page contact form has english options that should be french
![image](https://user-images.githubusercontent.com/46505127/74057091-2b236380-49b1-11ea-8211-94bfb290283e.png)

**Why?**
- OLA

**Comment by willeybryan** [comment]
@timarney  Are this in in translation file?

**Comment by willeybryan** [comment]
@timarney Ping

**Comment by anikbrazeau** [comment]
**EN** Ask a question
**FR** Poser une question

**EN** Give feedback
**FR** Donner votre avis

**EN** Set up a demo
**FR** Mettre en place une démo
