### ISSUE TITLE
Apply data retention to S3 buckets

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#611]
**Story**
When uploading a CSV to GC Notify I want it to be cleared out according to a services retention policy (OR sooner?) so that a privacy breach doesn't have a greater than expected privacy impact.

**What?**
- S3 buckets that contain uploads from csv sends should be purged in accordance with the service data retention policy at the time of upload (Or checking every day, or at policy change, whatever is easiest)
- Make sure the CSVs, which can contain PII are held for retention or less

**Why**
- Privacy impact assessment will not like this

**Comment by maxneuvians** [comment]
Can set this through S3 https://docs.aws.amazon.com/AmazonS3/latest/user-guide/create-lifecycle.html

**Comment by willeybryan** [comment]
Max, I recall you saying you just did this in S3
45 days Max was what I recall.
