### ISSUE TITLE
Long service names cause email sending errors

### ISSUE THREAD

**Issue by timarney** [cds-snc/notification-api#613]
Service names need to be shortened for IDNA.

@sastels reported an issue where emails we're stuck in sending.

Looking at the queue errors I found this.

<img width="775" alt="screen_shot_2020-02-13_at_2 48 49_pm" src="https://user-images.githubusercontent.com/62242/74473967-8ef6d200-4e72-11ea-9fc2-e51cea17f2b2.png">

**Comment by timarney** [comment]
@maxneuvians @willeybryan @ioanacontu we'll need to figure out the max length for service names (en | fr) + updates service name page.

Open to ideas if there's a better way to name services for reply-to emails.

**Comment by ioanacontu** [comment]
I'm counting 3 places where users can edit this info: 
1. When creating their first account (create account flow)
2. When adding a New Service (2nd, 3rd service etc)
3. Service Settings/Change Service Name
I'd suggest specifying in each of these places the restrictions for the name, as well as limiting the number of characters they can type in the service name field. 
I attached screenshots of 2. and 3. mentioned above. 

That aside, there is a lot of text on these pages, maybe we can also review/edit it a bit (since we're working on it)? Adding @caycefischer as well. 

<img width="858" alt="2_Add-New-Service" src="https://user-images.githubusercontent.com/56094538/74481363-945b1900-4e80-11ea-879f-c07714f2b40b.png">
<img width="585" alt="3_Change-Service-Name" src="https://user-images.githubusercontent.com/56094538/74481364-958c4600-4e80-11ea-9c36-2fc380c46fc3.png">

**Comment by ioanacontu** [comment]
Other solution to explore would be: 
 - Separating service name from reply-to email (any reason why the user would need a longer service name in the backend?) --> user could choose 'Service' name vs 'Display' name. I tend to find this a bit too complicated for the purpose it serves tho... what do you think?

**Comment by timarney** [comment]
The reply-to can be set by the user here:

<img width="400" alt="Screen Shot 2020-02-14 at 8 17 04 AM" src="https://user-images.githubusercontent.com/62242/74534736-674f4a80-4f02-11ea-8bf5-0834969833db.png">

The default is "auto generated" ... I think ideally all services would set the reply-to.

I think this comes down to "proper" setup vs quick on boarding.

**Comment by timarney** [comment]
As far as length:

Via - https://stackoverflow.com/questions/8717378/what-is-the-maximum-length-of-an-idna-converted-domain-name


> The answer is that the length to respect is the 255 character limit as DNS expects it.

> My suspicion was correct. The domain name and the entry in the DNS are two different things with IDN. It's the maximum length of the DNS entry that counts.

> The domain name "müller.de" has 9 characters, but the corresponding ACE (ASCII Compatible Encoding) string "xn--mller-kva.de", however, has 16 characters.

We run into the "9 characters" turning into "16 characters" characters with the French accents in the service names.

**Comment by willeybryan** [comment]
Ah so 255 is only for single bit encoded stuff. How did the UK get welsh character support in then? That change was on their roadmap for last year but it was after we forked our code. Do you think they may have an answer?

**Comment by willeybryan** [comment]
Could a quick win be just do a field validator approach, Throw an error when people put in something that won't work saying too long, or too long when encoded for DNS?

**Comment by ioanacontu** [comment]
Yes, a field validator would do, but we need to make sure that we explain the input/formatting requirements as well _before_ they get the error. Like the phrase we already have: "Your service name must include both English and French. It can't be longer than 16 characters."

**Comment by willeybryan** [comment]
"we need to make sure that we explain the input/formatting requirements as well before they get the error."
I can see that as true for the conservative mindset but not the explorer mindset.

If the message is simple "Sorry that input is too long or has unsupported characters please try again"

If 80% of people don't get the error then we have burdened them with information they don't need to get started.
The remaining 20% know to simplify their request. 

The explorer is just going to type things anyway, the conservative will follow instructions. If the instructions encourage the conservative mindset people to just try different service names, would that help get them past this point?
