### ISSUE TITLE
Github token scanning 

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#626]
**Story**
When operating Notify I want to make sure that no service user has accidentally published their API key or other credentials to github. 

**What?**
- https://developer.github.com/partnerships/token-scanning/
- Scan for all the API keys in Notify
- Alarm us if found any

(Product note, not sure if we want this as it would auto disconnect a service)
-Stretch: Enable the functionality to revoke key upon discovery 

**Why?**
- Satisfy security controls

**Comment by timarney** [comment]
I would be curious to see some stats of Gov depts using Github.

**Comment by willeybryan** [comment]
This many  https://twitter.com/cdngovrepos

**Comment by willeybryan** [comment]
@damcom333 Tim raises a good point, there aren't that many departments that use Github. While there be many repos there are few departments, especially at the gc level. There may be limited value in doing this as the risk is small right now. 

I am thinking we should push this out until later.

**Comment by timarney** [comment]
https://github.com/jpmckinney/open_source_canada/blob/master/data/organizations.txt

**Comment by timarney** [comment]
Note that list contains non Fed depts

```
cityofgreatersudbury
cityofottawa
cityofsurrey
cityoftoronto
```


I think we should be doing work around api - send counts + checking for spammy content (not sure on the policy end for that).

**Comment by damcom333** [comment]
Well, CDS using GitHub. And TBS. And the problem we have is that Notify could blow up over night. So I'd like to be prepared for disaster situations like this asap.

**Comment by willeybryan** [comment]
This may require updating all the API libraries, which means we have to fork all the clients.

**Comment by damcom333** [comment]
I don't follow. Why?

**Comment by timarney** [comment]
To ensure we have a unique API key pattern we'll need to adjust and than validate that format across all the clients.
