### ISSUE TITLE
Adding a reply to address doesn't complete

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#63]
**Steps to Reproduce**
- Go to settings
- Select to add a reply-to email
- Add one
- Validate that you got the email in your inbox

**Expected**
- Reply-to added

**Actual**
- Waits a while and fails saying that email isn't working

**Notes**
- In general Successful emails aren't reporting success, which is probably the mechanism this works with
- It seems strange you don't have to click anything to validate the email, I could set a reply-to of some one I don't like and get them some angry replies.

**Comment by maxneuvians** [comment]
I think this feature is broken - as you said, you should have to validate it with a link. I was also digging into why successful emails states do not show up and there is nothing in the code that actually updates it. There is a function that can update it `process_ses_results`, but it is never called ?!?

**Comment by willeybryan** [comment]
Just a small clarification, The email it sent didn't actually have a link, and I think it is by design. 

The contents of the message are as follows

"Hi,

This address has been provided as a reply-to email address for a GOV.​UK Notify account.
Any replies from users to emails they receive through GOV.​UK Notify will come back to this email address.

This is just a quick check to make sure the address is valid.

No need to reply.

Thanks

GOV.​UK Notify team
https://www.gov.uk/notify"

**Comment by maxneuvians** [comment]
Right so it should probably have a link if it was a functioning feature? ¯\_(ツ)_/¯

I think we should hide it.

**Comment by willeybryan** [comment]
But doesn't it just try to validate that the selected inbox got the email using the log files?

**Comment by maxneuvians** [comment]
No there is no verification mechanism - at least not one that works, because they always stay in `sending` and when you follow the code, it never updates to sent

**Comment by willeybryan** [comment]
So I think the bug here is that it never updates to sent, and it should. 

If we do that, then the dashboard will properly report emails sent (Right now they report as failed after 24 hours) and the Reply-to setting will work. 

Is there a reason to do it another way?

**Comment by maxneuvians** [comment]
Correct - but I don't think it is a bug. I think they did not document this properly. I think they have some sort of thing listening to a SNS queue that know about delivered emails and then flags them in the back end as sent.

https://github.com/alphagov/notifications-api/pull/1340
https://github.com/govau/notify/blob/e7d431163578a4813767355da2d7290a613f094d/api/app/notifications/notifications_ses_callback.py#L77

Seems to indicate this - will keep digging

**Comment by maxneuvians** [comment]
![Screenshot from 2019-07-16 11-32-03](https://user-images.githubusercontent.com/867334/61308071-767be780-a7bd-11e9-9a90-fc844712085c.png)
