### ISSUE TITLE
homepage french content

### ISSUE THREAD

**Issue by AntoineGarciaSuarez** [cds-snc/notification-api#631]

**Comment by anikbrazeau** [comment]
Texte : https://docs.google.com/spreadsheets/d/1lBC7YJTAqYdWYMYuozb18Cs17MlFPcLPoFd1BHDRW8k/edit#gid=1728996690

Écrans : https://www.figma.com/file/dxn3FzTMOoBzqFWiJxZMhc/Homepage-for-DEV?node-id=395%3A27
