### ISSUE TITLE
Investigate API for API (swagger)?

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#634]
**Story**
When using the Notify API I don't want to have to choose from a bunch of options, I just want to use it so I can advance my project.

**What?**
- Investigate a concept of API for our web api that makes it easier to use, set up, and configure.
- Swagger was a potential candidate, does it actually do this? Is there something that we could do?

**Why?**
- Explorer devs want to be able to connect to things right away
- Conservative devs don't want to be overwhelmed by choice
- Some people can't install stuff on servers easily.

**Comment by maxneuvians** [comment]
https://swagger.io/tools/swagger-codegen/

**Comment by maxneuvians** [comment]
It looks like swagger can only handle the API specification from the authentication point forward - there is no codegen for custom authentication functions, which is what we have in notify. If we were to take over all the API clients we could use swagger to do the bulk of the coding, but we would still need to write the custom auth routines or change the API auth method used in Notify.
