### ISSUE TITLE
répertorier le contenu en français de Notifications qui est erroné.

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#636]
**Story**
When viewing french content I want it to be as good as the english content so that I can feel confident in this software

**What?**
- Work with Anik to audit french content
- Pricing page strings missing
- Consistency in language across the site
- Documentation 
- UI

**Why?**
- OLA
- French speakers use the software

**Comment by anikbrazeau** [comment]
https://github.com/cds-snc/notification-admin/pull/383

https://github.com/cds-snc/notification-admin/pull/385

https://github.com/cds-snc/notification-admin/pull/391
