### ISSUE TITLE
TimeStamp that messages were sent at is in GMT

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#64]
**Steps to reproduce**
- Send a legit SMS message
- Wait
- Review dashboard time stamp for sent message

**Expected**
- Reporting the Current time

**Actual**
- A time that is 5 hours ahead

**Notes**
- Canada has a bunch of time zones, Supporting them may be complex. We just need to reflect reality. To accomplish this we could at a minimum just slap GMT into the time stamp so that people aren't shocked by it not reporting in their time zone.
- Alternatively move it to Eastern time, slap Eastern on there so that majority of Alpha users needs are met
- Perfect world, add time zone support, but this can be done later and isn't an immediate priority.

**Comment by maxneuvians** [comment]
@timarney fixed this with the timeszone issue. A longer term issue is that we need to make timezones configurable

![Screenshot from 2019-07-17 11-06-53](https://user-images.githubusercontent.com/867334/61386982-3d0daf80-a883-11e9-9e3d-923b7c3cc46b.png)
