### ISSUE TITLE
New Trial services are appearing in the list of live services

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#642]
**Steps to Reproduce**
- Create a trial service
- go to settings

**Expected**
- do not appear in live list

**Actual**
- Set to appear in live list while not live.

**Comment by timarney** [comment]
@willeybryan I seem to get different results.  Also your screen expected, actual appear to be the same. 

Created a new trial:

<img width="831" alt="Screen Shot 2020-03-02 at 8 34 07 AM" src="https://user-images.githubusercontent.com/62242/75680958-9c78ce00-5c60-11ea-9b85-85f36ea13189.png">

Showing as no by default.


https://notification.alpha.canada.ca/services/7d5cd1eb-61cb-4244-90d6-35ce9e291276/service-settings

**Comment by willeybryan** [comment]
@timarney Hopefully it isn't just me that is breaking stuff some how.

Can you pull a list of all services(GUID req, name nice to have), sorted by date created, with that boolean and the live boolean? 
IN my mind we need to see if there is a pattern, is there a better way to do that?

**Comment by timarney** [comment]
Sent you the list

**Comment by timarney** [comment]
@willeybryan anything further to be done here?

**Comment by willeybryan** [comment]
I wish we knew the pattern for why this happened.
Is it who created the service?

Can we set all the services that aren't live to not appear in the list?

**Comment by timarney** [comment]
> Can we set all the services that aren't live to not appear in the list?

Which one on the list isn't live?  I can see what's going on with those cases.

**Comment by willeybryan** [comment]
Unless I am missing something, which is a possibility. 
All the entries where:

 "go_live_at": null,
 "count_as_live": true,

Shouldn't they be:

 "go_live_at": null,
 "count_as_live": false,

**Comment by timarney** [comment]
I'm looking for the name / id of a service that you see on the live Dashboard that "shouldn't" be there.

**Comment by willeybryan** [comment]
Ah, there aren't any.

As long as the count_as_live doesn't impact anything right now then I guess it is ok. I just wish we knew why there was a variance. 

I am worried it will come back to bit us in the butt if we don't have an explanation.
