### ISSUE TITLE
Sending emails not there any more

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#645]
**Steps to reproduce**
- Send 30k emails
- Click on dashboard
- Click on sending

**Expected**
- 955 sending

**actual**
- None

**Notes**
they were there yesterday

![image](https://user-images.githubusercontent.com/46505127/75492187-3b61a980-5985-11ea-8e4c-817440d7c156.png)

**Comment by timarney** [comment]
The #'s don't quite add up but seems most of the difference ended up in the failed column.

<img width="787" alt="Screen Shot 2020-02-27 at 3 42 48 PM" src="https://user-images.githubusercontent.com/62242/75484979-d8b5e100-5977-11ea-8d9a-8fb3ad393e8c.png">

**Comment by willeybryan** [comment]
Cool, so it seems like they disappear from the UI after like 24 hours even though they keep trying in the back end for 72

This isn't a big deal but we should be away of it.
