### ISSUE TITLE
Dashboard Text message UI reports that texts sent to Canada were sent 'Internationally'

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#65]
**Steps to Reproduce**
- Send a text message to a legit number
- Wait for it to work
- Review time stamp & status in dashboard

**Expected**
- Sent (TimeStamp)

**Actual**
- Sent Internationally (TimeStamp)

**Notes**
- Easy solution may just be remove internationally for now
- If we can retarget it to some how know it is in Canada that would be optimal.

**Comment by maxneuvians** [comment]
Currently not delivering because of lack of SNS funds, but in the DB it is no longer flagged as international:

![Screenshot from 2019-07-15 14-18-19](https://user-images.githubusercontent.com/867334/61238855-8935e400-a70b-11e9-9247-63a63d0bdf4c.png)
