### ISSUE TITLE
Create lambda to handle security hub findings

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/notification-api#651]
**Story**

**What?**
- Create an AWS Lambda function to manage security hub findings

**Why??**
- Issue just stay in security hub, there is no notification.

**Comment by willeybryan** [comment]
@maxneuvians whats the story with this?
Are we using Lambda to pull out security hub alerts and send them elsewhere or is there another handling of these alerts I am missing?

**Comment by timarney** [comment]
@maxneuvians can you fill in some details here - would it send an email / alert slack etc...

**Comment by maxneuvians** [comment]
Based on https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cloudwatch-events.html we should be able to pop custom event findings into lambda
