### ISSUE TITLE
TASK: Make Service 100k per diem

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#652]
This service https://notification.alpha.canada.ca/services/11a44170-ebbc-47a3-9fb3-b6d8d173693b

Needs to support over 50k per day sending.

**Comment by timarney** [comment]
Set to 50,000 a day.

We have 100,000 total so can't make it 100,000

**Comment by willeybryan** [comment]
50K is their current limit and reason they are switching. Can we do 75K

**Comment by timarney** [comment]
Okay.

**Comment by timarney** [comment]
Okay at 75,000 now. 

Will suggest a new AWS send limit request soon after they go live.
