### ISSUE TITLE
Bounce backs can be crushing

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#656]
**Story**
When sending 100k unvalidated emails we want to reduce our bounce back from 10% to less as to appease our email suppliers. 

**What?**
- Validate emails before sending? https://neverbounce.com/email-verification
- Build a page into Notify to test? a separate page?
- Other ideas to reduce bounce back?
- Log bounce backs and prevent future sends?

**Why?**
- 30k emails produced 10% bounce back. 3k
- Spring we will want to send ~900k we don't want a90k bounce back

**Comment by timarney** [comment]
@maxneuvians talked to some folks at AWS and there's no "above board" way of doing this.
