### ISSUE TITLE
Practice Incident Response

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#659]
**Story**
When Notify goes down we want to be practiced in getting it back up so we can do it quickly and reliably. 

**What?**
- Run a drill to simulate restoring Notify from a failed state

**Why?**
- We need to validate that we can function in a reliable state during the aws outages. 

**notes**
- since we are live it may be easier to do this on staging.

**Comment by damcom333** [comment]
Could mark this as closed until the next one we run.
