### ISSUE TITLE
Users Can invite non-gov emails

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#66]
**Steps to Reproduce**
- From service page select team members
- Invite a team member
- Invite a Gmail Account
- Go to your Gmail account
- Click the invite link
- Follow the instructions

**Expected**
- Government only email should be allowed to work with the service at this time

**Actual**
- Got my gmail account into the system 

**Notes**
- Is this actually a bug? Since the services can only be created by a Gov email and we will have to approve it, do we care if a user invites a non-gov email? It is the users responsibility. 
- If we block this, then departments can't invite 3rd party contractors or similar emails

**Comment by maxneuvians** [comment]
During the AU demo this was used as a feature

**Comment by willeybryan** [comment]
Yeah, I figured that might be the case. Just wanted to get that documented and note that we won't do anything about this for now.
