### ISSUE TITLE
Update responsive design on homepage and with new banner

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#664]
**What?**
- Please to fix responsive design on the new content we made

**Why?**
- Over 20 people a day on average use Mobile site

**Comment by timarney** [comment]
<img width="811" alt="Screen Shot 2020-03-03 at 15 59 30" src="https://user-images.githubusercontent.com/62242/75915918-6769a880-5e25-11ea-81b1-267b029e146b.png">
