### ISSUE TITLE
French/English toggle only appears when signed in

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#67]
**Steps to Reproduce**
- Navigate to https://notifier.cdssandbox.xyz either signed out or incogneto
- Review top bar

**Expected**
- Since I am in English, a Toggle button that says Français

**Actual**
- No Toggle

**Note**
- Assuming my Browser is in English by default: When Signed in Shows English when I am in English, Should show Français because it should show what I want to switch to.
- Also happens on pages like https://notifier.cdssandbox.xyz/support when not signed in, but appears there when signed in

**Comment by timarney** [comment]
Adds toggle for "signed-out" template https://github.com/cds-snc/notification-admin/pull/40

**Comment by timarney** [comment]
Toggle is added we'll ensure everything is functioning as it should once we get the page content updated + translated.
