### ISSUE TITLE
Bug: Send button on 'Contact us' page in French is in English? Should be "Envoyer"

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#670]
**Steps to Repro**
- Allez au https://notification.alpha.canada.ca/support/ask-question-give-feedback
- clicquez le linge en français
- defilez en bas
- regardez 'send'

**Expected**
- Envoyer?

**Actual**
- Send

**Comment by anikbrazeau** [comment]
Fixed in https://github.com/cds-snc/notification-admin/pull/391
