### ISSUE TITLE
Adding new SMTP service removes old DNS records (need to refactor code)

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#676]
**Steps to Reproduce**
- Go to the SMTP configuration page https://notification.alpha.canada.ca/services/c31680dd-8d0d-4e9f-be06-0d2f201aeaf8/smtp
- Configure a new SMTP service
- do it again on a different service

**Expected**
- This service and the last both have DNS servers for SMTP

**Actual**
- I am told it clears our the last record from perhaps AWS

**Comment by maxneuvians** [comment]
This one is closed 🎉
