### ISSUE TITLE
Next day log switch over happens at 7pm

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#677]
**Steps to Reproduce**
- Login at 6:59 pm and check sent message logs
- Login at 7:01 pm and check sent message logs

**expected**
Stats for Today Canada eastern time

**actual**
Tomorrow (UK time zone)

**Comment by timarney** [comment]
The bug happens at 8pm UK midnight.

![daily](https://user-images.githubusercontent.com/62242/76859707-37140800-6830-11ea-9f97-e8da23e30840.gif)

@maxneuvians is working on the fix.
