### ISSUE TITLE
Back button doesn't do anything in notification preview page

### ISSUE THREAD

**Issue by brdunfield** [cds-snc/notification-api#682]
When progressing through the "Send" flow of a template, using the "use my own email" button. I entered in personalization and progressed to the Preview of my template.

Pressing the back button in the upper left just reloads the preview page.

**Comment by timarney** [comment]
@sastels might be a good one for you to pick up (it only touches the admin)

```
app/main/views/send.py
```

```
def get_back_link(service_id, template, step_index):
```

In this example - the link is trying to go back to step 4 ... step 3 is the proper back step.

![back-button](https://user-images.githubusercontent.com/62242/77413605-fc612100-6d95-11ea-9c30-6dc1ea739836.gif)

**Comment by sastels** [comment]
Should this issue be in the [notification-admin](https://github.com/cds-snc/notification-admin) repo?

**Comment by timarney** [comment]
Need to keep everything in the API repo for issues to map it back to https://github.com/orgs/cds-snc/projects/4

**Comment by timarney** [comment]
💯 @brdunfield for wrapping this up.
