### ISSUE TITLE
Fix SMS status in backend

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/notification-api#684]
Currently we are not reporting the delivery status of an SMS message in the admin. The reason is because AWS SNS delivers the message delivery status into a CloudWatch log vs into an SNS pub sub the way SES does it.

The solution is to build a lambda that subscribes to the CloudWatch log and sends the delivery status back to the API using a POST request.

**Comment by willeybryan** [comment]
Does this relate to the note I have for "Send an SMS with a test API key, might cause error"

**Comment by timarney** [comment]
Hitting this limit:

Resource limit exceeded. (Service: AWSLogs; Status Code: 400; Error Code: LimitExceededException; Request ID: 4465d44e-d9a0-4c21-a955-ce428618009a)

https://stackoverflow.com/questions/51975717/awslogs-resource-limit-exceeded-serverless-cloudwatchlog-event/52041396#52041396

**Comment by timarney** [comment]
@maxneuvians 

Can only have 1 subscriber per log.

https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html

<img width="616" alt="Screen Shot 2020-03-24 at 11 48 48 AM" src="https://user-images.githubusercontent.com/62242/77447087-a73d0380-6dc5-11ea-8273-b72a47baa061.png">

**Comment by obrien-j** [comment]
Given we'll need to move off of SNS for sms anyway, might be worth parking this one while we investigate if Pinpoint is more aligned with our existing use of SES.
