### ISSUE TITLE
Update keywords in app

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#688]
**Story**
When searching in Google for Notify I want to be able to find it by searching GC Notify so that I don't have to reverse engineer a google search

**what?**
- Update Meta Tags on Notify pages
- French tags too

**Why?**
- users search for things with Google when they don't have our URL

**Comment by timarney** [comment]
A few keywords does not a high ranking make.

We already have GC Notify in the list.  Anything else?

```

<meta name="keywords" content="gc notify, notify, canada notify, canada email, 
email notifications, Government of Canada, federal government, 
Canada SMS, | Canada Notification service" />

```

**Comment by timarney** [comment]
@willeybryan ping

**Comment by willeybryan** [comment]
e-notify
e notify
Enotify

@anikbrazeau  Any thoughts on French tags?
