### ISSUE TITLE
Bug: Invalid JWT will error 500, should be 401

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#689]
**Steps to reproduce**
- Using Postman connect to the Notify API with a valid key and a JWT invalidated through time expiry

**Expected**
- 401 Unauthorized access

**Actual**
- 500 server error

**Solution**
- Post back issue to UK repos

**Comment by timarney** [comment]
Might be worth posting this back to the UK vs us starting to fork "all the repos"

**Comment by timarney** [comment]
@maxneuvians noted we can catch this error on the way through in the api on our end.
