### ISSUE TITLE
API Key monitoring page(s)

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#695]
**Story**
As a Notify platform administrator I need to be able to monitor api key usage.

**What?**
Add additional details + a new summary page to allow better insights into api key usage. 

**Why?**
- Risk register req

**Notes**

1) API key overview (overview all keys that have sent in last X days)
=============================
Top senders last X amount of time
[Service name](link to service name)
Key name - total sends (email, sms) - services/e609f6b0-0390-45b0-aaae-f4cc92c713e4/api/keys so you can drill down

2) Key details ... services/e609f6b0-0390-45b0-aaae-f4cc92c713e4/api/keys)
=============================
​
Key name - total sends (email, sms)
  - key created, expires, last activity
  - [daily sends](link to graph sends per day)
  - Click on day

3) Day view for API key (linked from daily sends graph)
=============================
Summary of notifications sent 
date time , Template ID (link to template I

**To do for api:**
- [x] add another endpoint to get a list of api keys that have sent in the past 48 hours, sorted by number of sends
- [x] allow the client to specify the total for: last n days
- [x] allow the client to specify: email sends, sms sends, or total
- [ ] allow the client to specify: all notifications ever queued, all notifications queued but unsent, all successful sends, all failed sends, etc.

**To do for admin site:**
- [x] add a new page visible to platform admin, but not yet linked in the side nav
- [x] get the ranked list of api keys on the page, with links
- [x] add send stats
- [ ] implement some filtering/searching

**Comment by timarney** [comment]
@smcmurtry feel free to break this down into smaller tickets

**Comment by timarney** [comment]
I think we should hold on the filtering/searching for now - we'll get a better idea of what we actually need one we have the initial version of the overall summary page up.

**Comment by timarney** [comment]
Calling this "done for now". 

What @smcmurtry has built out gives us much better insights.
