### ISSUE TITLE
Better API Page for developers

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#701]
**Story**
When trying to connect Notify to my API I want all the information in the same place so I don't get lost looking for it and I know what to do next. 

**What?**
-

**Why?**
- Research showed devs didn't know what to do next and would get lost in setting up an API connection
- Developers some times connected to the Gov.uk api instead of ours because the information is on a different page

https://www.figma.com/file/IkTXhQMy88LRkxzo08SW4T/API-Integration?node-id=0%3A1

**Comment by timarney** [comment]
@anikbrazeau is any of this "fixed" given the updates in https://github.com/cds-snc/notification-admin/pull/410

Also if this is going to be fresh desk let's tag it as such

**Comment by timarney** [comment]
What's on the todo list here?  Or should we push this back to validate?

**Comment by ioanacontu** [comment]
I think we can push it back since it's in stand-by for now.
