### ISSUE TITLE
Map when/where documentation and support overlap and how the knowledge base might be structured and maintained over time

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#703]
Create logic around goals/needs/audiences of content before migrating to Freshdesk

Start with information needs.
Divide content to where it fits most appropriately.

https://docs.google.com/presentation/d/1RisdpmV8iMAFSkyEAmwnP91gVm9mR-5OlR4qHtfg6Bo/edit#slide=id.g70e53598f7_0_351

https://docs.google.com/document/d/1qtLV5wh4p7QiiHjjGIX6knBqoaSx8eYYg5NdZ0M4ZZk/edit

https://www.figma.com/file/51DIy8fmnxAjE24atIgddq/Notify-Information-Needs-Content-Model?node-id=0%3A1

**Comment by sboisvert** [comment]
just in case we need it: http://notification.assistance.cds-snc.ca/en/support/home
