### ISSUE TITLE
Increase SEND RATE with AWS & Notify

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#704]
Task:
- Current send rate of 120/sec or 10 million a day
- Can we bump it up to 5 million an hour? 3 million an hour
- Scale server infrastructure for queues
- Log DB size
- API Rate limits

**Comment by obrien-j** [comment]
Increased rate to ~ 50/s.

Suggest closing this until there's a proven need for the above rate limits.

**Comment by maxneuvians** [comment]
https://github.com/cds-snc/notification-tf/pull/26
