### ISSUE TITLE
Can't Download Logs

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#709]
**steps to reproduce**
- Navigate to here:
https://notification.alpha.canada.ca/services/11a44170-ebbc-47a3-9fb3-b6d8d173693b/notifications/email?status=sending%2Cdelivered%2Cfailed
- CLick download report

**Expected**
a CSV with the Dashboard info

**Actual**
A CSV where the only email is 'internal server error"

**Comment by timarney** [comment]
<img width="741" alt="Screen Shot 2020-03-24 at 1 38 02 PM" src="https://user-images.githubusercontent.com/62242/77458554-c000e580-6dd4-11ea-8c00-147086de94ea.png">

**Comment by willeybryan** [comment]
NVM NOT AN ISSUE

**Comment by timarney** [comment]
```
Recipient,Template,Type,Sent by,Sent by email,Job,Status,Time
__________,Questions and comments - Acknowledgement - English,email,,,,Delivered,2020-03-24 13:38:40
```
