### ISSUE TITLE
Enhance 96 hr scheduling block

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#716]
**Story**
When scheduling a email job with a CSV I want to be able to book jobs 2 weeks out so I can schedule an entire  2 weeks of quarantine notices in advance.

**What?**
- When uploading a CSV we offer a calendar selection, but if you choose something more than 4 days away you get an error so this needs to be changed.
- Can we change the the Calendar to only show 2 weeks +4 days out
- Can we update this also to reflect that https://github.com/cds-snc/notification-admin/commit/324e1f9ef400f0129940c5c217d6b76eb4c38342
- The error page itself will need to be updated so that if I choose 2weeks plus 5 it won't work,

**Why?**
- Notify wasn't designed for this but we have people who can't develop a scheduling app in time who need to prep notices to go out for two weeks. 
- if this is easy to do it would be a big help
- We need to sync the calendar and the back end time anyway
- 2w+4 was chosen because Original was 4 days so that you could do Monday from a Friday. This is handy and I want to be able to do the Monday 2weeks+a weekend out from a friday, this means adding 14 days or 336 hours to the existing 96 for a total of 432

**Comment by timarney** [comment]
@maxneuvians @damcom333 if we're scheduling further out any concerns about data retention storing?  I haven't looked at the code for this yet.

**Comment by timarney** [comment]
... and I looked at the code

<img width="1044" alt="Screen Shot 2020-04-03 at 2 12 04 PM" src="https://user-images.githubusercontent.com/62242/78391981-70c96a80-75b5-11ea-9fd8-a6888d775c0a.png">
