### ISSUE TITLE
When using Notification I don't need to be nagged about cookies because I don't live in the EU

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#72]
**What?**
- on home page before you sign in https://notifier.cdssandbox.xyz/
- There is a banner that says 'Notify uses cookies to make the site simpler. Find out more about cookies'
- I want it cut

**Why?**
- EU law says you have to tell people what you use cookies for and I don't want to care about that. People can go look it up on the cookies page here https://notifier.cdssandbox.xyz/cookies

**Comment by timarney** [comment]
We should be able to cut the 
```
Introductory message cookie
```
And just keep the admin session cookie part.

**Comment by timarney** [comment]
Note:

The client cookie code is here

https://github.com/cds-snc/cds_template_jinja/blob/master/assets/javascripts/govuk-template.js

**Comment by willeybryan** [comment]
Yeah, cut the cookie too.

**Comment by timarney** [comment]
Removes banner:
https://github.com/cds-snc/notification-admin/pull/32

**Comment by willeybryan** [comment]
Yeah, banner is gone for me when I test.
