### ISSUE TITLE
Silent Failure when uploading CSV with Internet Explorer on TBS tablet

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#720]
**Steps to Reproduce**
- Try to send a template to a CSV file. 
- Click send 
- Go to upload the CSV file
- Find file on computer and select

**Expected**
- Upload file and advance
- Error is something fails

**Actual**
- Nothing happens

**Notes**
- Reproduced with IE on my TBS tablet, reported by users in other departments on other devices, all using IE.

**Comment by timarney** [comment]
@anikbrazeau @willeybryan 

Can you copy the error message here for us?  As in the if you open the JavaScript console you should see an error - or is it just nothing.  No console errors or anything.

**Comment by timarney** [comment]
Yes IE has bad dev tools

**Comment by timarney** [comment]
Had a feeling that would be the case.  

Object Doesn't Support this Action is the worst IE error message ever.

Thanks for checking.

**Comment by anikbrazeau** [comment]
How about this? @timarney @willeybryan 

"We do not support Internet Explorer. Please try again using a different web browser, such as Google Chrome, Mozilla Firefox, or Microsoft Edge."

"Nous ne supporting pas Internet Explorer. Veuillez réessayer en utilisant un autre navigateur Web tel que Google Chrome, Mozilla Firefox ou Microsoft Edge."

**Comment by willeybryan** [comment]
That works for me!
If this appeared when an IE user tried to upload a CSV this would reduce the number of tickets we get.

**Comment by timarney** [comment]
https://github.com/cds-snc/notification-admin/pull/432
