### ISSUE TITLE
500 error during CSV download

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/notification-api#722]
When download a CSV report with more than 5000 results, the download causes a 500 error when you call for the second page, ex:

```
192.168.47.121 - - [30/Mar/2020:22:21:07 +0000] "GET /service/70996de4-ebe2-44c6-a0da-5587a86f37bd/job/0ed297cc-04a4-438f-be2f-fcbb6a9eec0d/notifications?page=2&page_size=5000&template_type=email&status=created&status=pending&status=sending&status=pending-virus-check&status=delivered&status=sent&status=returned-letter&status=failed&status=temporary-failure&status=permanent-failure&status=technical-failure&status=virus-scan-failed&status=validation-failed&format_for_csv=True HTTP/1.1" 500 53 "-" "NOTIFY-API-PYTHON-CLIENT/5.5.1"
```

**Comment by timarney** [comment]
@willeybryan or @maxneuvians 

Can either of you point me to a page to re-create this issue?  I downloaded from a few services and seemed to be fine.

<img width="500" alt="Screen Shot 2020-04-03 at 2 01 19 PM" src="https://user-images.githubusercontent.com/62242/78391143-cdc42100-75b3-11ea-89cb-aa33fc63545e.png">

**Comment by willeybryan** [comment]
Hey, it is no longer happening for me. 
Good work Tim. You fixed the quantum problem by measuring.
