### ISSUE TITLE
Runbook on how to push to production on Notify

### ISSUE THREAD

**Issue by sboisvert** [cds-snc/notification-api#726]
Max will find the thing in the thing and copy it over as a runbook

**Comment by sboisvert** [comment]
This probably needs to be @maxneuvians

**Comment by timarney** [comment]
I can pick this up at some point or if someone else can (it will get done sooner) 

The process is outlined here:

https://github.com/cds-snc/notification-tf#deploying-a-new-release

**Comment by maxneuvians** [comment]
https://docs.google.com/document/d/1_emxQQ5a_Slzue9Huk0PI-edY30-OUeoPmgv4enhkhE/edit#
