### ISSUE TITLE
How many templates will the average user have?

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#73]
**What?**
- I want to know how many templates a person creates for notification purposes in situations when they write notifications
- I want to know how long they use those templates, is it a one time thing? 
- How often are they making new templates?

**Why?**
- Notification lets you create and send from templates
- Notification has a folder structure for templates
- Folders are familiar but not great, we could improve them with tags, or a search, but in order to know how deep to go I want to know more about the template usecase

- How long do they use templates for?

**Comment by timarney** [comment]
"How often are they making new templates?"

Noting: The they in this case would be us - user requests a custom template.

**Comment by willeybryan** [comment]
am I unaware of something? I thought the users who create a log into the service would be creating templates for their service?

**Comment by timarney** [comment]
Mixup on my end:

The "branding" is also a template.
https://github.com/cds-snc/notification-utils/tree/master/notifications_utils/jinja_templates

But in the admin... "templates" are user controlled. 

============================

<img width="686" alt="Screen Shot 2019-07-12 at 7 51 56 AM" src="https://user-images.githubusercontent.com/62242/61126262-fdf1ef80-a479-11e9-9b1d-3ce198e76ed9.png">

**Comment by willeybryan** [comment]
Good to know. Let is be known there are system templates (jinja) and user templates. 

My gut is a folder structure sucks for organizing templates but I want to validate that.

**Comment by willeybryan** [comment]
Closing for now. Accessibility audit is going to force changes to this system anyway and as part of that we can change its UX.
