### ISSUE TITLE
Branding technical debt clean up phase 1

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#737]
**Story**
When uploading branding for a service I want to be able to be able to use the french FIP just like the english one and easy to use, and to one day support different branding for different templates in a service. 

**What?**
- Branding needs some fixing, can we make a plan on how to accomplish this without breaking stuff?

Rough plan
- [ ] Clean up the branding system to use the same code for every message
- [ ] Clean up code and technical debt relating to preview
- [ ] Make default dynamic
- [ ] Allow banner heigh to be dynamic
- [ ] Get us back down to one branding option, replaces FIP
- [ ] Tim?

**Why?**
-Branding causes a lot of problems
- We don't want to manage branding for users forever. 
- Cleaning up branding allows us to potentially make it more self serve or at the very least easier for SRE to manage

**Comment by timarney** [comment]
https://github.com/cds-snc/notification-api/issues/744

**Comment by willeybryan** [comment]
closing this in favour of #744
