### ISSUE TITLE
CSV - List splitting as a service

### ISSUE THREAD

**Issue by timarney** [cds-snc/notification-api#746]
As part of creating a secure CSV uploader and bulk sender we've written code to split csv lists into chunks.

## Idea
To keep as many people as possible using the default csv upload - we could offer a service that would split an uploaded list and return a .zip file with the split lists <50k per file.

## Why not to do this
We don't want to do mass mailings so we shouldn't make to easier (true or false)

**Comment by smcmurtry** [comment]
There are existing services that do this already, so we may not have to do this ourselves: https://www.splitcsv.com/

Would have to investigate if there are any that don't require you to transfer the file to their servers. This is probably a requirement since the files contain PII.

**Comment by timarney** [comment]
I wouldn't want to pass the data to an external service.

**Comment by timarney** [comment]
Lots of options

https://gist.github.com/jrivero/1085501/a2401c345e8abb46f3623e08afbe36e59923f94e
