### ISSUE TITLE
French bug: Dashboard grammatical error

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#751]
Pluralize the adjectives in French:

"courriels envoyé**s**"
"messages texte envoyé**s**"

![Screen Shot 2020-04-08 at 7 27 59 AM](https://user-images.githubusercontent.com/38330843/78791991-8c01f480-797e-11ea-8598-4755475e9b70.png)

**Comment by anikbrazeau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Audit copy in the interface for each level of permission EN / FR](https://trello.com/c/eRCKBnf2/31-audit-copy-in-the-interface-for-each-level-of-permission-en-fr)

**Comment by anikbrazeau** [comment]
For messages texte vs. messages texte**s** ... seems both are acceptable plural versions.
http://gdt.oqlf.gouv.qc.ca/ficheOqlf.aspx?Id_Fiche=26506622

Might it be easier to keep it as "Messages texte" ?

**Comment by sastels** [comment]
fixed in https://github.com/cds-snc/notification-admin/pull/480
