### ISSUE TITLE
Move "nothing selected" text down so we don't get overlap on the french template selection page

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#753]
Hide checkboxes and the "Nothing is selected" state, the interaction does not work and it does not show up well in French.

![Screen Shot 2020-04-08 at 8 07 51 AM](https://user-images.githubusercontent.com/38330843/78792468-25310b00-797f-11ea-813d-8609fd73511c.png)

![Screen Shot 2020-04-20 at 12 21 49 PM](https://user-images.githubusercontent.com/38330843/79778950-8b1a7c80-8307-11ea-96f3-6b6e53e27737.png)

![Screen Shot 2020-04-20 at 12 21 45 PM](https://user-images.githubusercontent.com/38330843/79779275-24e22980-8308-11ea-829e-87eb82882507.png)

**Comment by timarney** [comment]
> Hide checkboxes 

Are we removing the copy template button?

**Comment by timarney** [comment]
> Hide checkboxes

<img width="500" alt="Screen Shot 2020-04-28 at 8 43 01 AM" src="https://user-images.githubusercontent.com/62242/80488428-51abc780-892c-11ea-87d3-585acca5c210.png">

How will move work?

**Comment by smcmurtry** [comment]
@anikbrazeau How about we leave the checkboxes but move the "Nothing selected" text down to its own line below the buttons? That would fix the overlap problem.

**Comment by anikbrazeau** [comment]
Sounds good @smcmurtry ! Let's fix one problem at a time :D
