### ISSUE TITLE
French Characters can't be uploaded in a csv to Notify

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#760]
**Steps to Reproduce**
- Make a template
- Upload a CSV with François or John O'Brien's email in it (é also bad)

**Expected**
- It sends the emails to emails with double byte encoded characters

**Actual**
- Error saying they aren't valid emails

**Done When**
- You can email the completely valid email  John.O'Brien@tbs-sct.gc.ca in Notify with a CSV file

**Comment by AntoineAugusti** [comment]
@willeybryan Can you share some (fake) email addresses that you know are failing at the moment? An example CSV file works also 👌

**Comment by willeybryan** [comment]
Oh dear Fake ones?
Ok. I made them up based on https://en.wikipedia.org/wiki/Email_address#Local-part to screw with the system. 

fançoisthe'éüî@mailinator.com
Jean-o'briån@mailinator.com
Tom!the#taglover?@mailinator.com
2+2={5*4/5}@mailinator.com

**Comment by AntoineAugusti** [comment]
@willeybryan Read the SES AWS doc this morning discovered that they don't support non-ASCII characters.

https://docs.aws.amazon.com/ses/latest/DeveloperGuide/troubleshoot-error-messages.html

> There are non-ASCII characters in the email address—The email address string must be 7-bit ASCII.

Tried sending an email to `antoine.augusti+é` and it failed in staging, `technical failure`. If we want to be able to send emails to these addresses, they should be sent with another provider.

**Comment by willeybryan** [comment]
@AntoineAugusti  Well zut. Thanks for figuring that out. We will need to keep this in mind. So far the only people who have email address with those in them is internal GoC emails. 

If this starts to impact public communication with those in a french speaking province we will need to make sure we find an alternative provider.
