### ISSUE TITLE
Make French FIP more robust

### ISSUE THREAD

**Issue by brdunfield** [cds-snc/notification-api#762]
Towards #737 

**Story:**
A stop-gap french FIP was implemented to address #742. A more long-term solution needs to be put in place.

**Proposal:**
- Create a second 'default' branding which is French first

Both FIP branding styles would need to be considered 'default' and not 'custom' (i.e. both have a footer, etc). Note: When branding markup is simplified in #761 , this may affect the concept of default vs custom anyways.

**Comment by ClementineHahn** [comment]
Task pretty good defined for @brdunfield , should be a matter of a couple of days still minus any surprise so realistic to have it done by end of sprint.
