### ISSUE TITLE
As CDS/TBS/GoC, Whom we can provide this service to?

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#77]
**What?**
- Whom can we legally provide this service to?
- What law, act, statute, policy, agreement, or other is preventing us from providing this to all levels of government in Canada?
- Are we allowed to provide it to Federal? CrownCorp? Provincial? Territorial? Regional? Municipal? Academic? Schools? First Nations? Social Services? Food Banks? Non-profits? 
- Is there a special process we have to go through? MOUs?
- What are the consequences of violating this restriction if any?
- Who is responsible for enforcing this restriction?
- If the email service is offered for free does that change anything?
- What if money doesn't change hands?
- What is stopping us from sending invoices for incurred costs after the fact and accepting credit card payments?
- What are the consequences of 'accidentally' allowing the service to be used by other levels of government than federal?

**Why?**
- Out of the 1,000 Services using GOV.UK Notify https://www.gov.uk/performance/govuk-notify/government-services
Over 50% are local groups, if we can't target those groups, we are limiting our use cases and that will impact how we build the software, who we test with, and what features we add/remove.
- If allowing other levels of government to use it is complicated but not outright illegal then we need to start that process early or make a partner aware of it should it be handed off.

**Comment by maxneuvians** [comment]
I think an alternative strategy is to make this generic enough so each of the other entities can easily stand up their own service, example: customize name and timezones

**Comment by willeybryan** [comment]
Yeah! That is a good idea. The thought had occurred to me, that is Plan C  of the decision tree though.  
Plan A is we run it, starting our Government as a Service Platform
Plan B is we give it over/sell to another group that has the ability to provide the service.
Plan D is make it a nice demo to show off and then ditch it. 

Depends on the complexity of the findings in this ticket and how meetings with that other group go.

**Comment by willeybryan** [comment]
So we will be targeting federal government primarily first as per Ross instruction. 
Keeping it available for customization is a bonus.

**Comment by willeybryan** [comment]
Seeking ATO though leadership
