### ISSUE TITLE
Add in French for the string that indicates how long ago a password was changed in profile ( X days ago) 

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#774]
Add space between last change and timeframe in English : "Last changed # days ago"

Add translation in French :
"Dernier changement il y a # jours"

![Screen Shot 2020-04-15 at 1 51 46 PM](https://user-images.githubusercontent.com/38330843/79776231-720fcc80-8303-11ea-95a6-d9f1d4128819.png)

**Comment by anikbrazeau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Audit copy in the interface for each level of permission EN / FR](https://trello.com/c/eRCKBnf2/31-audit-copy-in-the-interface-for-each-level-of-permission-en-fr)

**Comment by smcmurtry** [comment]
I did some digging and the string `36 days ago` is being returned by a library called [ago](https://pypi.org/project/ago/):
https://github.com/cds-snc/notification-admin/blob/e4240c690b75c7b8a2d9818d1c1b4b833ea56bd5/app/__init__.py#L361

There doesn't seem to be any i18n support in this library. So we either have to change it out completely, or use a different library just to return the french strings. This is a larger task so I will put it on hold for now in favour getting some quicker FR fixes in.

**Comment by smcmurtry** [comment]
I just thought of a simpler solution here:
What if we just list the date that the password was last changed? That would be much easier to translate than "x time ago". Are you okay with that solution @anikbrazeau?

**Comment by anikbrazeau** [comment]
Yes! Great idea!

**Comment by anikbrazeau** [comment]
Perhaps something like this? 

Dernier changement : DD month YYYY

Example: 4 mai 2020
