### ISSUE TITLE
Translate the line indicating how long messages are kept "les messages sont conservés pendant *None* jours"

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#775]
Make sure variable is showing up correctly in both languages "None" should be a number of days or hours

<img width="729" alt="Screen Shot 2020-04-16 at 2 53 11 PM" src="https://user-images.githubusercontent.com/38330843/79777076-b64f9c80-8304-11ea-8db2-91b13df83e22.png">

**Comment by anikbrazeau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Audit copy in the interface for each level of permission EN / FR](https://trello.com/c/eRCKBnf2/31-audit-copy-in-the-interface-for-each-level-of-permission-en-fr)

**Comment by brdunfield** [comment]
Possibly fixed by https://github.com/cds-snc/notification-admin/pull/500 ? Can we confirm this is still a bug? My services all show 7 days / jours here. @anikbrazeau

**Comment by anikbrazeau** [comment]
Yes this looks to be fixed! 🥇 

<img width="814" alt="Screen Shot 2020-05-25 at 3 55 02 PM" src="https://user-images.githubusercontent.com/38330843/82840346-30dd8000-9ea0-11ea-9f5a-8fa69602a9c1.png">

<img width="997" alt="Screen Shot 2020-05-25 at 3 55 10 PM" src="https://user-images.githubusercontent.com/38330843/82840350-32a74380-9ea0-11ea-9b0a-52ae02f3f557.png">
