### ISSUE TITLE
Missing FR string for "Uploaded files" title and page

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#780]
Everything on the "Uploaded files" page shows up in English when using the site in French:

Uploaded files = **Fichiers téléchargés**

Files = **Fichiers**

Sending = **Envoi en cours**

Delivered = **Livraison réussie**

Failed = **Échec**

Sent = **Envoyé**

![Screen Shot 2020-04-20 at 12 04 36 PM](https://user-images.githubusercontent.com/38330843/79779816-fadd3700-8308-11ea-9e81-89e175b078c3.png)

**Comment by anikbrazeau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Audit copy in the interface for each level of permission EN / FR](https://trello.com/c/eRCKBnf2/31-audit-copy-in-the-interface-for-each-level-of-permission-en-fr)

**Comment by smcmurtry** [comment]
From @anikbrazeau:
"File" => "Fichier"
