### ISSUE TITLE
Preview of template shows "To: [phone number] in English rather than French

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#782]
"To:" should be **"À :"**

Phone number should be **Numéro de téléphone**

Email address should be **Adresse courriel**

[Templates FR.pdf](https://github.com/cds-snc/notification-api/files/4505035/Templates.FR.pdf)

![Screen Shot 2020-04-30 at 1 05 37 PM](https://user-images.githubusercontent.com/38330843/80977916-65a36d80-8df3-11ea-8bbe-606b17d1e003.png)

**Comment by anikbrazeau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Audit copy in the interface for each level of permission EN / FR](https://trello.com/c/eRCKBnf2/31-audit-copy-in-the-interface-for-each-level-of-permission-en-fr)

**Comment by smcmurtry** [comment]
This is done except for the yellow placeholder text. I made a separate issue for that here: https://github.com/cds-snc/notification-api/issues/850
