### ISSUE TITLE
Date in FrenchAPI key page is in English

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#783]
Apr 20, 10:13 AM --> 20 avril, 10 h 13 
![API keys FR](https://user-images.githubusercontent.com/38330843/79780624-2f052780-830a-11ea-957a-90a68df60b69.png)

**Comment by anikbrazeau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Audit copy in the interface for each level of permission EN / FR](https://trello.com/c/eRCKBnf2/31-audit-copy-in-the-interface-for-each-level-of-permission-en-fr)

**Comment by smcmurtry** [comment]
This is done! Hooray! 
<img width="797" alt="Screen Shot 2020-05-04 at 3 49 09 PM" src="https://user-images.githubusercontent.com/5498428/81017083-e035b280-8e1e-11ea-9763-1bde8932be00.png">

Fixed in https://github.com/cds-snc/notification-admin/pull/484
