### ISSUE TITLE
Error message refers to GOV.UK Notify rather than GC Notify

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#784]
"Your invitation to GOV.UK Notify has expired. Please ask the person that invited you to send you another one."

Change name to Notify in EN and Notification in FR

![Screen Shot 2020-04-20 at 10 39 25 AM](https://user-images.githubusercontent.com/38330843/79780805-7ab7d100-830a-11ea-8836-2f61d48209cb.png)

**Comment by sastels** [comment]
@anikbrazeau do you still have a link around to verify that this is still a problem? I can't find this text in the admin repo 😞

**Comment by anikbrazeau** [comment]
https://notification.alpha.canada.ca/invitation/ImMxNTIxNzk1LTI4NjEtNDk5Yy05Nzg2LTVhNDM2MzYxOTUyMyI.EZw0DA.4po5sWleWo1xQ67932SLpOatE7k

**Comment by sastels** [comment]
@anikbrazeau what's the full French translation of these error messages (or different content as you see fit)

Your invitation to Notify has expired. Please ask the person that invited you to send you another one.

Something’s wrong with this link. Make sure you’ve copied the whole thing.

**Comment by anikbrazeau** [comment]
@sastels 

**EN** "Your invitation to Notify has expired. Please ask the person who invited you to send you another invitation."

**FR** "Votre invitation à Notification a expiré. Veuillez demanded à la personnel qui vous a invité de vous envoyer une autre invitation."

**Comment by anikbrazeau** [comment]
@sastels 

**NEW EN** "Something’s wrong with this link. Make sure you’ve copied the whole thing."
**NEW FR** "Ce lien ne fonctionne pas. Assurez-vous queue vous avez bien copié le lien au complet."

---

**NEW EN** "You’re logged in as [EMAIL]. This invite is for another email address. Sign out and click the link again to accept this invite."

**NEW FR** "Vous êtes connecté avec : [EMAIL]. Cette invitation est pour une autre adresse courriel. Veuillez vous déconnecter et cliquer à nouveau sur le lien pour accepter cette invitation."
