### ISSUE TITLE
English grey text on French interface in Sent messages page

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#785]
[EN Name] Template = **Gabarit [FR Name]**

Envoi en cours since = Envoi en cours **depuis**
[Insert French date (20 avril, 11 h 05 ]

![Screen Shot 2020-04-20 at 12 04 42 PM](https://user-images.githubusercontent.com/38330843/79781120-03cf0800-830b-11ea-96a7-6ada94cd325e.png)

**Comment by anikbrazeau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Audit copy in the interface for each level of permission EN / FR](https://trello.com/c/eRCKBnf2/31-audit-copy-in-the-interface-for-each-level-of-permission-en-fr)

**Comment by willeybryan** [comment]
Also 'SENT MESSAGES' should be translated
