### ISSUE TITLE
Confirmation message to hide personalisation is missing in French

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#787]
Are you sure you want to hide personalisation after sending? = **Êtes-vous certain de vouloi cacher la personnalisation après l'envoi?**

You won't be able to see personalised content in Notification for this template = **Vous ne pourrez pas voir le contenu personnalisé dans Notification pour ce gabarit.**

You can't undo this = **Vous be pouvez pas annuler cette action.**

Confirm = **Confirmer**

Also change "Notification" in English to "Notify"

![Screen Shot 2020-04-20 at 12 10 26 PM](https://user-images.githubusercontent.com/38330843/79788471-b5276b00-8316-11ea-950c-def0a52a4426.png)

**Comment by anikbrazeau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Audit copy in the interface for each level of permission EN / FR](https://trello.com/c/eRCKBnf2/31-audit-copy-in-the-interface-for-each-level-of-permission-en-fr)

**Comment by smcmurtry** [comment]
@anikbrazeau should "Vous be pouvez pas..." be "Vous ne pouvez pas..."?
