### ISSUE TITLE
Add French for reply-to address

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#799]
**EN:** Add email reply-to address
**FR:** Ajouter une adresse courriel de réponse

**EN:** We're checking that _____ is a real email address.
**FR:** Nous vérifions que l'adresse _____ est valide.

**EN:** This can take a minute.
**FR:** Cela peut prendre une minute.

<img width="694" alt="Screen Shot 2020-04-27 at 8 17 31 AM" src="https://user-images.githubusercontent.com/38330843/80371424-e5fc2880-885f-11ea-9f6f-28f20f2c1c6c.png">

**EN:** ______ is ready to use
**FR:** ______ est prête à être utilisé

**EN:** Continue
**FR:** Continuer

![Screen Shot 2020-04-27 at 8 15 50 AM](https://user-images.githubusercontent.com/38330843/80976605-a39f9200-8df1-11ea-810c-f01dc3851b11.png)

**Comment by smcmurtry** [comment]
Found some more text on that page that needs translating:
here it is:
“There’s a problem with your reply-to address”
“You can try again, or use a different address.”
“We sent an email to _____ but it wasn’t delivered.”

**Comment by anikbrazeau** [comment]
**EN:** “There’s a problem with your reply-to address”
**FR :** “Il y a un problème avec votre adresse courriel de réponse”


**EN:** “You can try again, or use a different address.”
**FR :** “Vous pouvez réessayer, ou utiliser une autre adresse courriel.”


**EN:** “We sent an email to _____ but it wasn’t delivered.”
**FR :** “Nous avons envoyé un courriel à _____ mais le message ne s'est pas rendu.”

**Comment by smcmurtry** [comment]
And here's another missing translation: If you have more than 1 reply-to address set, you see "...and 4 more" on your settings page:
<img width="778" alt="Screen Shot 2020-05-11 at 11 06 33 AM" src="https://user-images.githubusercontent.com/5498428/81590160-a06b4f80-9377-11ea-9fd1-0e47ae90a0e7.png">

**Comment by smcmurtry** [comment]
On second thought I'll open another issue for that: https://github.com/cds-snc/notification-api/issues/848
