### ISSUE TITLE
Missing FR: Delete confirmation for reply-to email and text message sender

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#801]
**EN:** Are you sure you want to delete this reply-to email address?
**FR:** Êtes-vous certain de vouloir supprimer cette adresse courriel de réponse?

**EN:** Yes, delete
**FR:** Oui, _supprimer_

<img width="705" alt="Screen Shot 2020-04-27 at 8 26 15 AM" src="https://user-images.githubusercontent.com/38330843/80372223-3031d980-8861-11ea-9a27-0dfbf233b0de.png">

**EN:** Are you sure you want to delete this text message sender?
**FR:** Êtes-vous certain de vouloir supprimer cet expéditeur de message texte?

**EN:** Yes, delete
**FR:** Oui, _supprimer_

![Uploading Screen Shot 2020-04-27 at 8.31.18 AM.png…]()

**Comment by sastels** [comment]
Button fixed in #499 

<img width="746" alt="image" src="https://user-images.githubusercontent.com/8228248/81575833-7c0e7380-9375-11ea-8fbc-7346147a6099.png">
