### ISSUE TITLE
Missing FR on message sent page

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#803]
EN : Data available for 7 days

FR : **Les données seront disponibles pour 7 jours.**

<img width="518" alt="Screen Shot 2020-04-27 at 12 18 22 PM" src="https://user-images.githubusercontent.com/38330843/80489266-9126e380-892d-11ea-81c1-b071163149cf.png">

**Comment by smcmurtry** [comment]
@anikbrazeau It looks like this one is already fixed:
<img width="758" alt="Screen Shot 2020-04-30 at 3 24 49 PM" src="https://user-images.githubusercontent.com/5498428/80760855-d1858d80-8af6-11ea-88ef-531ae42cefd3.png">

Could you double check to make sure I'm not missing something?

https://staging.notification.cdssandbox.xyz/services/ea608120-148a-4eba-a64c-4d9a8010e7b0/notifications/email

**Comment by anikbrazeau** [comment]
Looks fixed!
