### ISSUE TITLE
Dashboard should reflect what users needs are

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#806]
**Story**
When I login to Notify I would like to land on a page that allows me to preform an action related to my role so that I have a clear path forward and I am not confused about what to do next.  

**What?**
- Dashboard needs some new new action component for users so that they aren't confused as what to do next based on the task they should be preforming for that role. 
- Keep API integration link open and visible for developers.

**Why?**
- To improve self serve we want to make sure that people are motivated to explore the software organically. 
- Users looking to send messages in the UI are getting confused when they are taken to the dashboard
- Developers testing showed developers clicking API integration first consistently. 

**Done When**
- We have a peer reviewed mockup of the dashboard to share with the team for feedback and integration by development (With french and a11y considerations)
- Stretch goal: Depending on size of feedback integrating feedback into mockup. 

**Notes**
https://www.figma.com/file/fRVRKm7cM8MUuBWUJbrfgU/Senders-content-creators-service-operators?node-id=948%3A1306

https://trello.com/c/75YC9VfY/59-redesign-dashboard-as-a-landing-place-with-clear-actions-for-different-access-levels

**Comment by ClementineHahn** [comment]
Meeting with dev happened May 7th to assess feasibility of envisioned options

**Comment by anikbrazeau** [comment]
FIGMA: https://www.figma.com/file/fRVRKm7cM8MUuBWUJbrfgU/Senders-content-creators-service-operators?node-id=948%3A1306
