### ISSUE TITLE
SMS load Balancer rate limiting

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#807]
**Story**
When sending SMS I want it to come from a canadian number so that  can build a trusting communication relationship with my recipients.

**What?**
- Rate limit SMS long codes to 1per second per long code or less, like .75 to be safe. CWTA says max is 1/sec and more that that is blocked. 
- Stretch Goal, keep SNS up and running for our two factor and other testing. 

**Why?**
- Government comms people don't want to send from US numbers, they don't think it will be trusted
- SMS scams are everywhere
- SMS use cases are not more than a couple 100 at once so max speed isn't essential. 
- Helps use cases for embassy staff, geographically remote staff, Quarantine patients. 

**Done When?**
- We can safely offer a long code to a client for their use case and trust it.

**Comment by brdunfield** [comment]
Pre-requisite for #1046

**Comment by brdunfield** [comment]
SMS rate limiting will be implemented for all SMS providers:
- Only Pinpoint requires it for the dedicated long code situation
- However, we have been seeing throttling errors from Celery - if we make it SMS wide this should solve that.

**Comment by ClementineHahn** [comment]
Temporary Blocked at testing stage without flooding personal phone. 
Resolved will be continued today

**Comment by brdunfield** [comment]
This is just in staging, not actually finished yet.

In order to address the issue of bulk SMS sends blocking system messages, we have decided to move system messages to the priority queue. Since this is a different queue, the rate limit will not apply, and they should be sent immediately on other workers, instead of waiting for the SMS queue to clear.
