### ISSUE TITLE
HELP, STOP, INFO, AIDE, ARRET General Messages 

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#809]
**Story**
When I get a text from Notify I need to be able to reply Help so that I can learn more and trust it is a legitimate communication.

**What?**
- We need responses for HELP, STOP, INFO, AIDE, ARRET

**Why**
- Short code request needs them
- Long code numbers need them

**notes**
https://docs.google.com/document/d/1IbBHE_hDtXmV03FJFeB5wRWUekzmEP4Ky2x0a_lDBtg/edit

**Comment by ClementineHahn** [comment]
@anikbrazeau Reworked to make it consistent compatible with all possible Notify services

**Comment by anikbrazeau** [comment]
Something like this could work. Ideally, we would eventually link INFO to be service-specific. @willeybryan you okay with the proposed texts below? 
@ClementineHahn could you proofread the French?

HELP:
To learn more, text INFO to 226. Text STOP to unsubscribe. Standard message rates apply.

AIDE:
Pour en savoir plus, envoyez INFO au 226. Envoyez ARRET pour vous désabonner. Les frais de messagerie texte standard s'appliquent.

INFO:
You’re subscribed to notifications from a Government of Canada service. | Vous êtes abonné aux notifications d’un service du gouvernement du Canada.

STOP:
You are now unsubscribed. You will not receive any more notifications from the Government of Canada.

ARRET:
Vous êtes maintenant désabonné. Vous ne recevrez plus de messages du gouvernement du Canada.
