### ISSUE TITLE
Notify's documentation and information sharing - offboarding

### ISSUE THREAD

**Issue by AntoineGarciaSuarez** [cds-snc/notification-api#813]
Notify Research Repo

https://airtable.com/tbl9mgHWtOcaAotaR/viw4K1dYZxWvjvwFY?blocks=hide

**Comment by ClementineHahn** [comment]
@AnneMarieMulumba to add link of new research of repository when ready

**Comment by AntoineGarciaSuarez** [comment]
Notify research repo
[https://airtable.com/tbl9mgHWtOcaAotaR/viw4K1dYZxWvjvwFY?blocks=hide]

**Comment by ClementineHahn** [comment]
Objective before @AntoineGarciaSuarez  leaves is to have refined objectives in alignment with @AnneMarieMulumba for the survey with specific focus on the feedback component

**Comment by ClementineHahn** [comment]
@AnneMarieMulumba is creating an executive summary of past research done as part of the off-boarding of Antoine and sharing information , to be linked here soon

**Comment by ClementineHahn** [comment]
Presentation of the executive summary done during the demo closing Sprint 22, documentation of this presentation is here : https://docs.google.com/presentation/d/13yvP15tPRxWNuTr3vPSAOp3nTfHwrwWZ_pXk4zdxKSg/edit
