### ISSUE TITLE
Review and test the survey's plan (questionnaire and research) with quant. researchers.

### ISSUE THREAD

**Issue by AntoineGarciaSuarez** [cds-snc/notification-api#817]
+
Get the survey's execution ready (tools, consent forms)

**Comment by AnneMarieMulumba** [comment]
It is a medium task, indeed

**Comment by AnneMarieMulumba** [comment]
The survey plan: https://docs.google.com/document/d/1Iso6pfI3APU9j2b0E006ErlBe9FpTzTuwgX2b5oeLIs/edit?usp=sharing

**Comment by jeanafrost** [comment]
I have a draft of the questions here:
https://docs.google.com/document/d/1aabUYN8ubDQbxPrhaF1GTEDFU3rLANfTkaROJ7IPbYM/edit#
