### ISSUE TITLE
"Secure" the survey's plan with quant. research (questions + plan)

### ISSUE THREAD

**Issue by AntoineGarciaSuarez** [cds-snc/notification-api#821]
+
Get the survey's execution ready (tools and capacity)

**Comment by ClementineHahn** [comment]
To note the outcome of meeting of May 6th with @AnneMarieMulumba @AntoineGarciaSuarez @willeybryan  in there for line of sight

**Comment by ClementineHahn** [comment]
One survey was actually aiming to understand 2 things so we're going to make it more explicit and have on one side :
- a feedback component
- a survey

+ a need to explore feedback component with dev to understand impact on foreseen dev tasks that will be needed to make it happen

**Comment by ClementineHahn** [comment]
@AnneMarieMulumba Would like to present before the executive summary to the team before the end of the sprint, date to be found today with @willeybryan  and @ClementineHahn
