### ISSUE TITLE
Missing FR: Save and Remove individual team member

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#830]
When you edit a team member's permission, the 
"Save" button is in English and the "Remove this team member" link is in English.

Save = "Enregistrer"

Remove this team member = "Enlever ce member de l'équipe"

![Screen Shot 2020-04-27 at 8 36 52 AM](https://user-images.githubusercontent.com/38330843/80974833-49053680-8def-11ea-9204-026df0197441.png)

**Comment by brdunfield** [comment]
Looks like this has been fixed!

<img width="550" alt="Screen Shot 2020-05-29 at 9 46 47 AM" src="https://user-images.githubusercontent.com/5032149/83278777-5533a800-a191-11ea-9a44-b4995321c6b0.png">
