### ISSUE TITLE
FR Confirm button when changing service name

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#831]
When changing the service name in FR, button should be in FR.

**EN** Confirm
**FR** Confirmer

<img width="723" alt="Screen Shot 2020-04-27 at 8 23 55 AM" src="https://user-images.githubusercontent.com/38330843/80978175-b5823480-8df3-11ea-9c78-856bace68f26.png">

**Comment by brdunfield** [comment]
<img width="524" alt="Screen Shot 2020-05-28 at 11 17 07 AM" src="https://user-images.githubusercontent.com/5032149/83172440-ca8d7300-a0d4-11ea-8ec8-d86f9dfb8c6a.png">

Looks like this has already been fixed. Closing!
