### ISSUE TITLE
FR Trial mode onboarding experience

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#845]
Title:
Example email template ---> **Exemple de gabarit de courriel**

Preview: 
[From] ---> **De**
[To] ---> **À**
[Subject] ---> **Objet**

Button: 
Continue ---> **Continuer**

Button: 
Send 1 courriel ---> **Envoyer 1 courriel**

Link to "Allez à votre tableau de bord" is cut off on the third step

Template is also in English only, is it possible to have a French one on the French side of Notify?

![Onboarding FR 1](https://user-images.githubusercontent.com/38330843/81408284-f25b6d80-910a-11ea-8c40-a04417928a0c.png)

![Onboarding FR 2](https://user-images.githubusercontent.com/38330843/81408288-f2f40400-910a-11ea-8aee-db8e50aa2ba6.png)

![Onboarding FR 3](https://user-images.githubusercontent.com/38330843/81408289-f38c9a80-910a-11ea-9292-c9b2944b6d63.png)

**Comment by smcmurtry** [comment]
The plan is to remove the onboarding experience: https://github.com/cds-snc/notification-api/issues/901 

So if we are removing it there is no reason to translate it.
