### ISSUE TITLE
FR Archive Error Message

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#847]
Translate error message

"There's no way to reverse this! Are you sure you want to archive this user?"

**"Êtes-vous certain de vouloir archiver cet utilisateur? Vous ne pourrez pas revenir sur cette décision."**

![image](https://user-images.githubusercontent.com/38330843/81562637-33e65580-9363-11ea-8947-c3574c45cb25.png)

**Comment by sastels** [comment]
Two other English-only strings in the same file are:
- "Are you sure you want to block this user?"
- "Are you sure you want to unblock this user?"

**Comment by sastels** [comment]
<img width="983" alt="image" src="https://user-images.githubusercontent.com/8228248/84697924-fa35db00-af1c-11ea-9ce6-cf0804c3b79c.png">

**Comment by anikbrazeau** [comment]
**EN:** "Are you sure you want to block this user?"
**FR:** "Voulez-vous vraiment bloquer cet utilisateur?"

**EN:** "Are you sure you want to unblock this user?"
**FR:** "Voulez-vous vraiment débloquer cet utilisateur?"
