### ISSUE TITLE
Remove Templates for Templates selection option when creating template

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#852]
Currently we have a default or suggested 'Confirmation Message' template available in English only.

We should consider offering an equivalent in French as well, as an example.

We could start by translating the current template to cover both languages, knowing there will likely be many more associated tasks. For example translating all aspects of examples, like how to upload and match a CSV.

![Screen Shot 2020-05-12 at 8 13 33 AM](https://user-images.githubusercontent.com/38330843/81690521-65295900-9429-11ea-8d2e-d57200845140.png)

"Bonjour ((prénom)),

Ce message confirme <action à confirmer> le ((date de confirmation)). Votre numéro de référence est le ((numéro de référence)).

Vous pouvez utiliser ce numéro de référence pour vérifier votre <rendez-vous, demande, etcetera – à completer> en vous connectant à votre <MonCompte//autre service en ligne du GC> ou en appelant <Nom du département> au <NUMÉRO DE TÉLÉPHONE>.

Merci,

NOM ET/OU NOM DU DÉPARTEMENT"

![Screen Shot 2020-05-12 at 8 13 57 AM](https://user-images.githubusercontent.com/38330843/81690618-88540880-9429-11ea-9d63-1415b39220a1.png)

**Comment by anikbrazeau** [comment]
Perhaps this issue is bigger than it appears...

We might have a lot of figuring out to do as we only offer default templates right now in EN.

If we offer a bilingual template (with both EN and FR) it might be confusing for users to have to enter each variable in both languages….

We may need to figure out a way to get around the French branding at the service level and make it at the template level to make a FR basic default template option possible?

**Comment by anikbrazeau** [comment]
From discussion with Bryan:

Fixing it properly depends on per template language branding.

Currently, no one is using the feature, it never got adopted or asked about due to content ownership problem.

We could hide it and restrict it to platform admin to continue developing it on staging later if we want to come back to it.

Since it is currently kind of broken anyway, if it breaks more, maybe no one will notice?

**Comment by willeybryan** [comment]
@sastels Could a solution for this ticket be to remove the templates4templates dropdown feature altogether thus hiding the template and removing the need to change it?
I can provide more info on what dropdown I mean if you like, but you see it when you create a new template.

**Comment by sastels** [comment]
You mean this dropdown?
<img width="691" alt="image" src="https://user-images.githubusercontent.com/8228248/82830372-89525480-9e83-11ea-8dcf-3bee3d1ef1d5.png">

Yes, it would be easy to remove this.

**Comment by willeybryan** [comment]
Yeah, plus the drop down title, and I imagine one of those line breaks

**Comment by sastels** [comment]
basically just have to delete this:
https://github.com/cds-snc/notification-admin/blob/master/app/templates/views/edit-email-template.html#L19-L33

**Comment by anikbrazeau** [comment]
Perhaps we can hide rather than delete, in case we want to reuse in future?

**Comment by sastels** [comment]
Deleting keeps the codebase cleaner IMO... And with git(Hub) we really have the best of both - just have to go to the deleting PR to see exactly what code was removed.

**Comment by willeybryan** [comment]
There is already a ticket to remove it https://github.com/cds-snc/notification-api/issues/841
