### ISSUE TITLE
FR Confirm changes to variables page

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#855]
![Confirm](https://user-images.githubusercontent.com/38330843/81692947-2ac1bb00-942d-11ea-90ab-60b36a517dd1.png)

EN: Confirm changes
**FR: Confirmer les modifications** 

EN: You removed
**FR: Vous avez enlevé**

EN: You added
**FR: Vous avez ajouté**

EN: Save changes to template
**FR:** Enregistrer les modifications au gabarit

EN: When you send messages using this template you'll need # columns of data:
**FR: Lorsque vous envoyez des messages avec ce gabarit vous aurez besoin de # colonnes de données :**

EN: Developers, you'll need to update your API calls.
**FR: Développeurs, vous devrez mettre à jour vos appels API.**

**Comment by sastels** [comment]
"Confirm changes" and "Save changes to template" already (now) done

<img width="810" alt="image" src="https://user-images.githubusercontent.com/8228248/82834020-d20f0b00-9e8d-11ea-9f84-e025976af6e9.png">
