### ISSUE TITLE
FR continue button on reply-to selection step

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#856]
<img width="475" alt="Screen Shot 2020-05-11 at 9 19 23 AM" src="https://user-images.githubusercontent.com/38330843/81693541-0fa37b00-942e-11ea-9032-0eb036e3eb4f.png">

**EN** Continue
**FR** Continuer

**Comment by smcmurtry** [comment]
This was fixed in https://github.com/cds-snc/notification-admin/pull/518
<img width="1121" alt="Screen Shot 2020-05-15 at 10 10 03 AM" src="https://user-images.githubusercontent.com/5498428/82072341-d28cf200-9694-11ea-8569-89fd8d6e5924.png">
