### ISSUE TITLE
FR template folder

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#857]
**"Templates"** top-level folder should be **Gabarits** in French

**Empty** should be **Vide** in French

<img width="800" alt="Screen Shot 2020-05-12 at 9 18 56 AM" src="https://user-images.githubusercontent.com/38330843/81697311-f224e000-9432-11ea-9dfa-71c2489573bf.png">

**Comment by willeybryan** [comment]
@anikbrazeau or en vide?

**Comment by brdunfield** [comment]
Looks like the Header has already been fixed, but 'Empty' is still present! Will fix!
