### ISSUE TITLE
Translate "hide personalization after sending" flow

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/notification-api#859]
<img width="794" alt="Screen Shot 2020-05-12 at 2 52 39 PM" src="https://user-images.githubusercontent.com/5498428/81744312-485c4800-9460-11ea-8a80-5e589ea9fbaf.png">

@anikbrazeau could you put the translations in a comment?

**Comment by anikbrazeau** [comment]
See: https://github.com/cds-snc/notification-api/issues/787

**Comment by smcmurtry** [comment]
Of course you found this already! Thanks 😄
