### ISSUE TITLE
Data for Product for Business Analysis

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#861]
**Story**
I need data so I can figure out why trails left us and figure out how to make less of them leave us. 

**What?**
If I had a sql interface I would do something like this:

SELECT service_name date_created count_delivered count_sent FROM (Source of 'https://notification.alpha.canada.ca/platform-admin/reports/usage-for-all-services') WHERE (Live=NO, if possible, but I can filter out live myself.)  ORDER BY date_created

**Why?**
- people who signed up for a trial and sent many  messages but didn't go live have a story and I want it. 

**Done when**
I have my data

**Comment by sastels** [comment]
This query might do the trick
```sql
with ns as
(
select service_id, notification_type, notification_status, notification_count, created_at 
	from ft_notification_status
),

data as
(
select ns.notification_type, ns.notification_status, ns.notification_count, 
    services.name as service_name, ns.service_id, services.restricted as trial_mode, services.count_as_live, services.created_at as service_created_at
	from ns inner join services on ns.service_id=services.id
),

rollup as
(
select sum(notification_count) as notification_count,  service_name, service_id, service_created_at, trial_mode, count_as_live, notification_type, notification_status 
	from data
	group by service_name, service_id, service_created_at, trial_mode, count_as_live, notification_type, notification_status
)

select service_name as name, service_id as id, service_created_at as created_at, trial_mode, sum(notification_count) as count_delivered_or_sent from rollup
    where (notification_status='delivered' or notification_status='sent') and trial_mode=true
    group by name, id, created_at, trial_mode
    order by created_at
```

**Comment by sastels** [comment]
Results
https://docs.google.com/spreadsheets/d/1PPKfXyGhwsJsYCfbc13e15DcdjJNfSHjGG0rY127wEo

**Comment by sastels** [comment]
@willeybryan are we good to close this issue?

**Comment by willeybryan** [comment]
Yes!
