### ISSUE TITLE
Migration off of .alpha.

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#862]
**Story**
When getting messages from Notify I want to see them from Notificaiton.canada.ca and not from notificatoin.alpha.canada.ca so that I can more easily trust the government domain. 

**What?**
- Encourage Max and SRE to move Notify to Notification
- Ensure all redirects are permanent
- Make sure not a single API integration will break
- No SMTP integrations should break either. 

**Why?**
- Looks cleaner which inspires trust
- Is shorter which ensures greater system compatibility with Microsoft email RFCs

**Done When?**
- A user can type notification.canada.ca into their browser bar and get to Notification
- All client API integrations pointing to the old domain still work
- api.notification.canada.ca accepts new incoming API connections
- notification.canada.ca messages satisfy DMARC compliance
- That one user on a custom sending domain isn't affected (They target our SES and shouldn't be affected but edge cases)

**STEPS**
- [ ] Make an API app connection to staging like the one at the end of the [scavenger hunt](https://docs.google.com/document/d/1MmKBZqMNpsLU0TlURGCyOlByZHGfZccteuYdGZ9amwM/edit#)
- [ ] Migrate Staging from Notification.cdssandbox.xyz to notify.cdssandbox.xyz?
- [ ] Test The Site, Your app, and validate login, sending, downloading of logs works, uploading of CSVs and uploading branding images
- [ ] Test Email DMARC using [MX toolbox](https://mxtoolbox.com/) or something.
- [ ] Tell everyone we are going to move to production and to validate this work on Slack #notify-dev
- [ ] Repeat for Prod

**Optional Steps** (Do before repeat for prod)
- [ ] Set up Notification.canada.ca first with everything redirecting to alpha 
- [ ] Test Redirect with API app Browser

**Comment by sastels** [comment]
From @maxneuvians:

> This is on the books for SRE
we need to move AWS contracts
so I have John figuring that out
