### ISSUE TITLE
CSS Fixes for Canda log and text alignment

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#863]
**Story**
When sending and receiving emails on a variety of devices I want the emails to be responsive so that I can view the same information everywhere.

**What?**
- Fix CSS in our 2 default branding confirmations 

**Why?**
- Certain elements are responsive in different ways and it creates a variety of responses across email clients

**Done When?**
- Default branding isn't huge on screen windows where width isn't communicated
- Logo and text are inline in accordance with Fip Compliance.

**Comment by anikbrazeau** [comment]
https://www.canada.ca/en/treasury-board-secretariat/services/government-communications/federal-identity-program/manual.html

**Comment by sboots** [comment]
Short summary of FIP from an email standpoint is: there aren’t any email-specific instructions (the FIP manual was last updated in 1997), but there are instructions for general use of the GC signature and wordmark. And, there are general trends (almost de facto standards) of how the GC signature and Canada wordmark are used that it’s helpful to be consistent with.

The short answer is, 

- use the GC signature (the flag + Government of Canada + Gouvernement du Canada) in the top left of the email / webpage / document / etc.
- use the version of the GC signature that starts with the language of the rest of the content (e.g. if they’re receiving French notifications, it should be the flag + Gouvernement du Canada + Government of Canada version)
- use the Canada wordmark in the bottom right or bottom centre of the email (I’ve seen both but would recommend bottom right for consistency with how it’s used on GC webpages)

If in the future we add other email “footer” content, the Canada wordmark should be at the bottom below everything else.

Even if we’re tight on space, we should still use the regular GC signature (e.g. we can’t cut off the second Government of Canada / Gouvernement du Canada text); maybe we could use max-width CSS to help shrink it down on small phones but email clients seem pretty inconsistent with CSS. I definitely trust your judgment on what works best.

Confusingly, there are two widely used versions of the SVG for the GC signature; the one used on Canada.ca until fairly recently had a lot of strange SVG artefacts in it that were noticeable on retina displays. It’s fixed now and we should make sure that we’re using the non-strange version. 😅 

And, at the moment (in the COVID emails for example) the Canada wordmark looks good on retina screens but the GC signature looks a bit blurry; if we’re updating the images that might be something we could fix as well.

Lastly, departmental comms teams often have very strong feelings about FIP (and varying interpretations of what is required). If this ever comes up, happy to help mythbust things. 

Hope this is useful – rock on all!

**Comment by brdunfield** [comment]
Just flagging for this issue that the CSS alignment of the default FIP is different than the custom branding sizing being off. For this card, I'll focus only on the CSS.

Problems with custom branding are captured here:
https://github.com/cds-snc/notification-api/issues/832
