### ISSUE TITLE
Draft a Beta research plan: qual and quantitative.

### ISSUE THREAD

**Issue by AnneMarieMulumba** [cds-snc/notification-api#872]
- Add Jeana as a co-writer to this card once she joins.

**Comment by mcman12** [comment]
Préparer le document, insérer le background de la recherche

**Comment by AnneMarieMulumba** [comment]
Beta research plan, currently a draft, but excited to present it soon: https://docs.google.com/document/d/1mHfOz_SmavsERF8to-wawBA3d60nJpYzhSS0b0slQCw/edit?usp=sharing
