### ISSUE TITLE
 Improve collaboration and interdisciplinary work within team members

### ISSUE THREAD

**Issue by ClementineHahn** [cds-snc/notification-api#873]
--
**WHY** : 
why are we doing this ?
What is the scope ?
Who does it involve ?

**DONE WHEN** : 
What artifacts are we looking to get when its done ?
What changes, consequences we are looking for ?

**Comment by amazingphilippe** [comment]
This is how this issue could take shape. Feel free to update the main description and title to fit.

- [ ] Improve collaboration and interdisplinary work within team members
- [ ] Improve the efficiency of the design-dev workflow
- [ ] Set up and try the process for one feature. Such as the main dashboard
- [ ] Involves the whole team, lead by designers and devs

Artifacts when done:
- [ ] a figma component library for Notify. Processes to maintain both the figma file, stylerguide documentation up to date.
- [ ] Identification of design patterns and components that shape the product's ui and experience

Changes and consequences we are looking for:
- [ ] A more integrated design-dev process, where inputs from both skillsets are considered and acted upon when planning or syncing up.
- [ ] Changing how we approach changes and new features

**Comment by amazingphilippe** [comment]
[Artefact](https://docs.google.com/presentation/d/1GH2cVKwujzSLA3lwh-0YVyHiupr2-GQKQNZDTz_mWds/edit?usp=sharing): Shareback presentation on what we've learned during sprint 22
