### ISSUE TITLE
GOC logo in notifications on dark mode

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#877]
How should the FIP show up on a dark background?

![Image from iOS copy](https://user-images.githubusercontent.com/38330843/82379623-372db100-99f5-11ea-8902-eabdad06add7.png)

**Comment by brdunfield** [comment]
This also affects the footer "Canada" image.

We may be able to leverage this: https://drafts.csswg.org/mediaqueries-5/#prefers-color-scheme
and use alternate logo images if dark mode is detected!

**Comment by willeybryan** [comment]
That sounds complicated. If a user is smart enough to put their their app into dark mode then they can survive with this. Long term it would be nice to be able to detect that, for a small section of users that are using dark mode, this isn't the first time they have seen this bug. 

I googled some Usage on dark mode, and it seems like the best case scenario is that 20% of phone app users put on dark mode. However the only data sources I could find tracking this are Beta apps and Preview iOS versions. People using Beta are explorers by nature, so I believe true dark mode usage is far less than 20%.

Full disclosure, I use dark mode a bunch and love it.
