### ISSUE TITLE
When using the Notify API we need to make sure that the ProductionAPI isn't hard coded to gov.uk

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#88]
**What?**
- the api_client.js node client is hard coded the production version of the API to api.notifications.service.gov.uk and we need to to be able to target our API location. 
- We need to alter this in notifications-node-client repo that GDS uses
- We need this to be an environment variable instead of a hard coded URL and GDS needs to accept this change. 

![image](https://user-images.githubusercontent.com/46505127/61243342-bab3ad00-a715-11e9-837a-32dff75cf13c.png)

**Why?**
- As a developer if you follow the instructions for a language i.e. Node JS https://docs.notifications.service.gov.uk/node.html#install-the-client
- Your send attempt will fail as the code tries to hit the UK API (url hardcoded) but with a Service ID from the Canadian Notifications database i.e. you will never be able to send an email via the API as is.
- We need the endpoint to hit our API.
- The same is true for the other API clients - PHP etc..

**Comment by timarney** [comment]
Why? 

As a developer if you follow the instructions for a language i.e. Node JS 

https://docs.notifications.service.gov.uk/node.html#install-the-client

Your send attempt will fail as the code tries to hit the UK API but with a Service ID from the Canadian Notifications database i.e. you will never be able to send an email via the API as is.

**Comment by willeybryan** [comment]
Ah, thank you for explaining that. I was missing that peice.

**Comment by timarney** [comment]
Submitted an issue / request here https://github.com/alphagov/notifications-node-client/issues/83

**Comment by willeybryan** [comment]
![giphy](https://user-images.githubusercontent.com/46505127/61545486-94dc2000-aa15-11e9-8d2a-2ebbc1550c1b.gif)

**Comment by timarney** [comment]
Turns out the code allows this:
```javascript
var notifyClient = new NotifyClient('https://example.canada.ca', apiKey);
```

The main docs for the Node client for the install section don't mention that.

```javascript
var NotifyClient = require('notifications-node-client').NotifyClient
var notifyClient = new NotifyClient(apiKey)
```

See: https://github.com/alphagov/notifications-node-client/blob/master/client/api_client.js#L24

Closing this as the response from the UK covers our needs .
