### ISSUE TITLE
Focus styles for new UI elements are inconsistent with existing focus styles

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/notification-api#887]
New focus styles:
<img width="417" alt="Screen Shot 2020-05-22 at 10 23 39 AM" src="https://user-images.githubusercontent.com/5498428/82688677-8272da00-9c16-11ea-86c3-314b5bfdc914.png">
<img width="305" alt="Screen Shot 2020-05-22 at 10 24 00 AM" src="https://user-images.githubusercontent.com/5498428/82688700-8a327e80-9c16-11ea-833d-8b47a35f2eaf.png">

Existing focus styles:
<img width="342" alt="Screen Shot 2020-05-22 at 10 23 49 AM" src="https://user-images.githubusercontent.com/5498428/82688728-961e4080-9c16-11ea-8956-c7f27e6c80c4.png">

**Comment by brdunfield** [comment]
Duplicated by #929
