### ISSUE TITLE
FR Dashboard post-sending

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#889]
<img width="746" alt="Screen Shot 2020-05-25 at 3 53 44 PM" src="https://user-images.githubusercontent.com/38330843/82840519-e6a8ce80-9ea0-11ea-9828-94aa63dd2e02.png">

After sending an email using a live service, a few strings show up in EN on the FR interface:

EN: **"Data available for 7 days**
FR: **"Données disponibles pendant 7 jours**

EN: **"since" __date__**
FR: **"depuis" __date__**

**Comment by brdunfield** [comment]
Can I get more specific steps / permissions / info on how to reproduce? I'm not seeing the missing translations.

<img width="751" alt="Screen Shot 2020-05-28 at 11 14 34 AM" src="https://user-images.githubusercontent.com/5032149/83172197-7a161580-a0d4-11ea-9a1a-838c5bf88fd0.png">

**Comment by anikbrazeau** [comment]
I think this has been fixed through another issue since! 

Though I did find another unwrapped string that appears in English only, when trying to reproduce this:

**EN** No messages to show
**FR** Aucun message à afficher

![Screen Shot 2020-06-01 at 4 16 25 PM (2)](https://user-images.githubusercontent.com/38330843/83450514-65fb4c80-a423-11ea-9af0-e30a6e5a0504.png)
