### ISSUE TITLE
Phase Banner (Alpha) Needed to communicate to Alpha users expectations

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#89]
**What?**
- On the home page before you sign in we need a phase banner expressing this is alpha
- Put it where the cookie banner is now, or put it in the top black bar. Follow standard CDS design on this.
- If in the top black bar, carry it over to every page

**Why?**
- We need to set expectations that this is an alpha service and it is under active development.

**Comment by timarney** [comment]
https://github.com/cds-snc/notification-admin/pull/32
