### ISSUE TITLE
Untranslated error messages

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/notification-api#891]
Trying a new low-effort approach to documenting these issues: Screenshots from VS code 😄 

`flash` is the function that displays error messages, so I was able to find untranslated error messages by searching for `flash('` and `flash("`. Here are the results:
![Screen Shot 2020-05-25 at 2 03 45 PM](https://user-images.githubusercontent.com/5498428/82840773-fddfc000-9e90-11ea-8f08-677e4c3c14ad.png)
![Screen Shot 2020-05-25 at 2 03 59 PM](https://user-images.githubusercontent.com/5498428/82840778-ffa98380-9e90-11ea-81e7-000cedd9424b.png)

@anikbrazeau Would you mind posting the translations below? Feel free to ignore the ones about letters.

**Comment by smcmurtry** [comment]
Here are the error messages that need translating:

"There’s something wrong with the link you’ve used."
"The link in the email we sent you has expired. Enter your email address to resend."
"The link in the email has already been used"
"Invite sent to {email_address}"
"Are you sure you want to remove {user_name}"
"This organisation name is already in use"
"Couldn’t read {filename}. Try using a different file format."
"{filename} contains numbers or dates that Notification can’t understand. Try formatting all columns as ‘text’ or export your file as CSV."
"Are you sure you want to remove security key {keyname}?"
"You can't accept an invite for another person."


The text in `{}` doesn't need translating - they are just variable names.

**Comment by anikbrazeau** [comment]
**EN** "There’s something wrong with the link you’ve used."
**FR** "Il y a un problème avec le lien que vous avez utilisé."

**EN** "The link in the email we sent you has expired. Enter your email address to resend."
**FR** "Le lien que nous vous avons envoyé par courriel a expiré. Entrez votre adresse courriel pour le renvoyer."

**EN** "The link in the email has already been used"
**FR** "Le lien envoyé par courriel a déjà été utilisé"

**EN** "Invite sent to {email_address}"
**FR** "Invitation envoyée à {email_address}"

**EN** "Are you sure you want to remove {user_name}"
**FR** "Êtes-vous certain de vouloir enlever {user_name}"

**EN** "This organisation name is already in use"
**FR** "Ce nom d'organisation est déjà utilisé"

**EN** "Couldn’t read {filename}. Try using a different file format."
**NEW EN** "**_Could not_** read {filename}. Try using a different file format."
**FR** "{filename} ne peut pas être lu. Veuillez essayer un format de fichier différent"

**EN** "{filename} contains numbers or dates that Notification can’t understand. Try formatting all columns as ‘text’ or export your file as CSV."
**NEW EN** "{filename} contains numbers or dates that **_<i>Notify</i>_** can’t understand. Try formatting all columns as ‘text’ or export your file as CSV."
**FR** "{filename} contient des nombres ou des dates que <i>Notification</i> ne peut pas comprendre. Veuillez essayer de modifier le format des colonnes en 'texte' ou exportez votre fichier en CSV."

**EN** "Are you sure you want to remove security key {keyname}?"
**FR** "Êtes-vous certain de vouloir supprimer la clé de sécurité {keyname}?"

**EN** "You can't accept an invite for another person."
**FR** "Vous ne pouvez pas accepter une invitation pour une autre personne."

**Comment by smcmurtry** [comment]
Thank you @anikbrazeau!!!
