### ISSUE TITLE
Export a route-map of Notify for A11Y scanning

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#894]
**Story**
When a11y scanning Notify(with our tools), we want to scan all the public facing URLs, so that we might be confident there are no glaring road blocks for Beta. 

**What?**
- Route map containing at least the Non-auth logged in URLs

**Why?**
- Finding any red flag blockers is important to avoid risk

**Comment by willeybryan** [comment]
https://notification.alpha.canada.ca/
https://notification.alpha.canada.ca/features
https://notification.alpha.canada.ca/features/email
https://notification.alpha.canada.ca/features/sms
https://notification.alpha.canada.ca/features/templates
https://notification.alpha.canada.ca/features/terms
https://notification.alpha.canada.ca/documentation
https://notification.alpha.canada.ca/features/messages-status
https://notification.alpha.canada.ca/features/security
https://notification.alpha.canada.ca/support/ask-question-give-feedback
https://notification.alpha.canada.ca/support/thanks
https://notification.alpha.canada.ca/register
https://notification.alpha.canada.ca/sign-in
https://notification.alpha.canada.ca/forgot-password
https://notification.alpha.canada.ca/pricing
https://notification.alpha.canada.ca/privacy
https://notification.alpha.canada.ca/404
https://notification.alpha.canada.ca/_styleguide

**Comment by anikbrazeau** [comment]
Updated here: https://trello.com/c/Z9q69jlv/131-inclusive-design-review-unauthenticated
