### ISSUE TITLE
GC Office 365 Migration Broke Email 2fa for GC staff M/L

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#895]
**Steps to Reproduce**
- Invite your TBS email to a Notify service
- using your CDS user Set your TBS user to Email sign in
- Try to log in as your TBS user

**Expected**
- Clicking the link logs me in

**Actual**
- Href is destroyed by security software that opens the link before hand to scan it, causing the link to show up as expired to the user. 
- The user has to copy and paste it into the browser

**Proposed Solution**
- SMS texts a 5 digit # Code that you enter into a field in the web browser.
- Email a 5 digit number code instead. (Steam by Valve does email 2fa in this fashion)

**notes**
- Related issue https://github.com/cds-snc/we_are_platform/issues/214

**Comment by obrien-j** [comment]
https://github.com/cds-snc/notification-api/issues/858

**Comment by brdunfield** [comment]
Ticket is blocked by #932
