### ISSUE TITLE
Remove/hide English tutorial

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#901]
**Done When**
- A new user can come to notify and create a trial service without having to create a template and go through the tutorial

**Note**
- We need to make sure we introduce step by step template creation or something to teach people the power of variables in Notify.

**Comment by sastels** [comment]
This was really a "small" in the end, as I just had to remove a couple lines of code (that were easy to figure out)

**Comment by sastels** [comment]
left in the "start-tour" route as it is called in another place in the app.
