### ISSUE TITLE
Missing FR on Thanks page after contact us

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#911]
https://notification.alpha.canada.ca/support/thanks

**EN** Thanks for contacting us

**FR** Merci de nous avoir contacté

![Screen Shot 2020-05-29 at 1 13 06 PM](https://user-images.githubusercontent.com/38330843/83286724-66d77880-a1ae-11ea-80f7-ad6b0c94f001.png)

**Comment by smcmurtry** [comment]
Hmm, it looks like there is a lot of conditional text on this page that doesn't show up in this screeenshot, but would if it is an out of hours emergency, etc. Here is the text:

"We’ll reply in the next 30 minutes."
"We’ll reply within one working day."
"We’ll read your message in the next 30 minutes and reply within one working day."
"We’ll read your message when we’re back in the office."
"We’ll read your message in the next 30 minutes."

**Comment by anikbrazeau** [comment]
@willeybryan do you know if these set standards/time expectations are fair for Notify? Or whether they're possibly inherited from GOV.UK?

**Comment by smcmurtry** [comment]
Looks like they're from gov.uk: [commit](https://github.com/cds-snc/notification-admin/commit/83017fd096ae167393ed2d45b8909f3bc5823fa2#diff-db8cfcb09c972cd378f5d403defd4df6)

So nevermind! The text will remain hidden.
