### ISSUE TITLE
Remove the route to the legacy Gov.UK content for Pricing and How-to-pay

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#920]
Found legacy content on pricing

https://notification.alpha.canada.ca/

https://notification.alpha.canada.ca/pricing/how-to-pay

We could remove these page (or at least the routes to them) so that people don't navigate to them?

These pages add no extra value that isn't found in homepage or features content

**Done When**
- Content is inaccessible

**Why?**
- Slight risk of someone finding that page, noticing it isn't translated and cause trouble. Much easier to disable the route then worry.

**Comment by sastels** [comment]
I think we should 🔥 the how-to-pay page - we currently don't even link to it.
