### ISSUE TITLE
Translations for HC bulk send flow

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/notification-api#931]
Here is the content that needs translating:

"Use a list of email addresses from Amazon S3"
"Choose a list of email addresses from Amazon S3"

<img width="815" alt="Screen Shot 2020-05-22 at 8 33 42 PM" src="https://user-images.githubusercontent.com/5498428/82719891-b9bfa600-9c6b-11ea-804c-015f20d6a074.png">

<img width="897" alt="Screen Shot 2020-05-22 at 8 34 09 PM" src="https://user-images.githubusercontent.com/5498428/82719895-c7752b80-9c6b-11ea-95ef-17773d2dd415.png">

**Comment by anikbrazeau** [comment]
As is:

**EN** "Use a list of email addresses from Amazon S3"
**FR** "Utiliser une liste d'adresses courriel de Amazon S3"

**EN** "Choose a list of email addresses from Amazon S3"
**FR** "Sélectionner une liste d'adresses courriel de Amazon S3"

---

Wondering: Will the audience here know what Amazon S3 is? Could the platform possibly change?

---

Possible alternative could be to use a "stored list", or something of the sort if it's more meaningful, in which case we might say something like:

**EN** "Use a stored list of email addresses"
**FR** "Utiliser une liste stockée d'adresses courriel"

**EN** "Choose a stored list of email addresses"
**FR** "Sélectionner une liste stockée d'adresses courriel"

**Comment by smcmurtry** [comment]
Thanks @anikbrazeau! I don't think we will change from using Amazon S3 for this.
