### ISSUE TITLE
New Content for Email Code-based 2FA

### ISSUE THREAD

**Issue by brdunfield** [cds-snc/notification-api#932]
**Blocks** #895 

**Done When**
- Template is updated on Staging so that @brdunfield can push to production. 

Email templates and sign-in pages need content changes to reflect that a code is being mailed / inputted, instead of a link to be clicked.

Current sign-in page:
<img width="516" alt="Screen Shot 2020-06-05 at 12 31 14 PM" src="https://user-images.githubusercontent.com/5032149/83916627-bda2fc00-a732-11ea-92b7-0388cb6b5e4b.png">

Current Production sign-in template:
<img width="519" alt="Screen Shot 2020-06-05 at 1 45 27 PM" src="https://user-images.githubusercontent.com/5032149/83916696-dd3a2480-a732-11ea-8948-76d00839bce8.png">

There may be other content areas that need updating, but design would know better than I do!

**Comment by willeybryan** [comment]
@brdunfield While I assume we will need to edit the templates on Staging first.
Which template is the current one for sign-in on Prod?
templates/ece42649-22a8-4d06-b87f-d52d5d3f0a27 Or templates/299726d2-dba6-42b8-8209-30e1d66ea164

And what does the ((Variable)) need to have in it for the number code. Is it going to be ((verify_code))like the SMS template here? 
https://notification.alpha.canada.ca/services/d6aa2c68-a2d9-4437-ab19-3ae8eb202553/templates/36fb0730-6259-4da1-8a80-c8de22ad4246

**Comment by willeybryan** [comment]
UX note for designers:
If you make the code the first thing in the email body then people with phone notification previews will show it and it will make the UX more SMS like.

**Comment by brdunfield** [comment]
> And what does the ((Variable)) need to have in it for the number code. Is it going to be ((verify_code))like the SMS template here?
> https://notification.alpha.canada.ca/services/d6aa2c68-a2d9-4437-ab19-3ae8eb202553/templates/36fb0730-6259-4da1-8a80-c8de22ad4246

I haven't changed this, so it's still ((url)) in the code (mostly so the existing email template still works on my local environment), however it would be very easy (and probably a good idea) to make it ((verify_code)).

**Comment by brdunfield** [comment]
> Which template is the current one for sign-in on Prod?
> templates/ece42649-22a8-4d06-b87f-d52d5d3f0a27 Or templates/299726d2-dba6-42b8-8209-30e1d66ea164


looks like `templates/299726d2-dba6-42b8-8209-30e1d66ea164` on prod

**Comment by anikbrazeau** [comment]
Found another spot where it might be affecting content:

`set-auth-type.html`
('Your team members can sign in with either a text message code or an email link.')

**Comment by brdunfield** [comment]
Looks like the title of the link has expired page will also need an update:

Currently: "Invalid email link"

**Comment by anikbrazeau** [comment]
Does this mean the security code is a clickable link in the email message template? 
Or should this simply be an error message?

EN "Invalid security code"
FR "Code de sécurité non valide"

**Comment by brdunfield** [comment]
for the above, it was just the page title that displays in the browser tab.

Also flagging that error messages are not the same as they were - there's no separate email error page anymore. Errors will just show up in red text above the code entry as they do on the SMS page.
That said, those errors don't appear to be translated:

"Code not found"
"Code has expired" (for this one I found / used "That security code has expired" from the CSV - let me know if you want a different one)

It looks like the "code has expired" message is used for a code that has already been used as well. Is that acceptable, or should I do some work to restore the "code has already been used" type of message?

**Comment by anikbrazeau** [comment]
Perfect :) 
Here are all the messages in EN and FR:

EN: "Code not found" 
FR: "Code non trouvé"
Link https://github.com/cds-snc/notification-api/issues/953

EN: "Code has expired"
FR: "Le code a expiré"

EN: "Code has already been used"
FR: "Le code a déjà été utilisé"
