### ISSUE TITLE
Notify in top banner is not being read [S]

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#935]
Inconsistent across pages. 

Ensure that it's actually being read by screenreaders on different pages.

Read only if don't skip to main content (read on unauthenticated pages)

Consider hierarchy of page with subsequent headings

https://docs.google.com/document/d/1JaJzEnQ7M6tQRziwEC1q8_UUQBizAdVRtUashXdYZeo/edit

**Comment by brdunfield** [comment]
This will possibly be fixed by #902 . I recommend we wait to investigate this further until that ticket has been completed.
