### ISSUE TITLE
Landmarks are in English only [S]

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#936]
**Done When**
- Landmarks are in the correct language for the correct user.

Landmarks are all in English, get read in English to French user.

Every page landmark named will need a French name.

ARIA label -- identifies menu bar and content area

https://docs.google.com/document/d/1JaJzEnQ7M6tQRziwEC1q8_UUQBizAdVRtUashXdYZeo/edit

**Comment by sastels** [comment]
@anikbrazeau  we're going to need some tranlations for the landmark aria-labels, such as
- "language & login"
- "main navigation"
- "sub-navigation"
- "footer menu"

landmarks such as "banner" and "main" are part of HTML, I assume the screen readers know what they are(?)

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/8228248/84693966-5ea16c00-af16-11ea-9d17-a1ae7811140d.png">

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/8228248/84694043-81338500-af16-11ea-8983-1bfc4c97d72e.png">

**Comment by anikbrazeau** [comment]
**EN** "language & login"
**FR** "langue et connexion

**EN** "main navigation"
**FR** "navigation principale"

**EN** "sub-navigation"
**FR** "sous-navigation"

**EN** "footer menu"
**FR** "menu de bas de page
