### ISSUE TITLE
Template formatting - Redesigned

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#939]
**Done When**
- A new template formatting page that is easy to read and understand has been pushed to production. 
- Future goal: It can be pushed to people when they first create a template as a way to teach them how the template system works. 

Consider formatting it in a different way to make it more meaningful to users:

Could be a box?
Overhaul this page fully?

Currently
-- looks like block quotes
-- asterisks read as stars
-- hash reads as pound sign

https://docs.google.com/document/d/1JaJzEnQ7M6tQRziwEC1q8_UUQBizAdVRtUashXdYZeo/edit

Latest wireframes on far right: https://www.figma.com/file/qSW5XL4PpjbC8SyZAl2bkS/Unauthenticated-pages?node-id=1%3A58

**Comment by anikbrazeau** [comment]
Looking at examples of what others have done:
https://www.figma.com/file/qSW5XL4PpjbC8SyZAl2bkS/Formatting-Guide?node-id=1%3A34

Looking at what we have currently and the usability and accessibility issues:
https://www.figma.com/file/qSW5XL4PpjbC8SyZAl2bkS/Formatting-Guide?node-id=0%3A1

Working on new version in Figma here:
https://www.figma.com/file/qSW5XL4PpjbC8SyZAl2bkS/Formatting-Guide?node-id=1%3A58

**Comment by ClementineHahn** [comment]
Worked on the content and accessibility of the new template

**Comment by anikbrazeau** [comment]
Design finalized v4 on far right in Figma here: https://www.figma.com/file/qSW5XL4PpjbC8SyZAl2bkS/Unauthenticated-pages?node-id=1%3A58

**Comment by mcman12** [comment]
will be reviewed today to merge.
