### ISSUE TITLE
Technical Documentation: Rethink how API endpoint link appears [S-M]

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#940]
-- Link looks like a button
-- If it's a button immersive reader ignores it

-- Reads out entire URL "https://api.notification.alpha.canada.ca"

-- Better contextualize what the link is for, select and copy or some sort of contextualizing

https://docs.google.com/document/d/1JaJzEnQ7M6tQRziwEC1q8_UUQBizAdVRtUashXdYZeo/edit

**Comment by anikbrazeau** [comment]
Non-clickable link for endpoint

**Comment by brdunfield** [comment]
We also have a text-field that looks like a button in the csv sender flow (the csv name if i recall correctly).
