### ISSUE TITLE
CSV File upload strings are missing in french

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-api#944]
csv files:
```
"Message about email address does not exist. Some one needs to figure out the words here."," "
```

**Comment by willeybryan** [comment]
here https://notification.alpha.canada.ca/user-profile/password ?

**Comment by willeybryan** [comment]
C'est repairé!

**Comment by sastels** [comment]
I don't know if I'd call this fixed... it's still in the code in a branch where a user is trying to change their password but somehow the user doesn't actually exist. maybe to prevent someone from trying to hack in a user somehow? Possibly we should just say something like "I cannot find this user. If this is a mistake then please contact us"

https://github.com/cds-snc/notification-admin/blob/master/app/templates/views/new-password.html#L29

**Comment by willeybryan** [comment]
How can I replicate this to generate the error message. I need to context. 

Is it upload a csv with a fake email in it?

**Comment by sastels** [comment]
> How can I replicate this to generate the error message. I need to context.
> 
> Is it upload a csv with a fake email in it?

I have no idea. Maybe if you were logged in but then your account got deleted? If you aren't logged in and navigate there then you get bounced to the log in page.

**Comment by anikbrazeau** [comment]
Do we know the context for this message to show up? or what the equivalent SMS one would be?

**Comment by willeybryan** [comment]
Ok so I did some testing and found some english strings


UPLOADING A SPREAD SHEET IN TRIAL MODE WITH EMAILS NOT ON YOUR TEAM
![image](https://user-images.githubusercontent.com/46505127/86628514-fc2d1000-bf97-11ea-998b-a15bc8854b06.png)

UPLOADING A SPREADSHEET WITH AN INVALIDLY FORMATTED EMAIL
![image](https://user-images.githubusercontent.com/46505127/86628598-1f57bf80-bf98-11ea-9a92-1974dfc0418d.png)

**Comment by willeybryan** [comment]
UPLOADING A SPREADSHEET WITH MISSING COLUMN (too many columns is fine)

**Comment by willeybryan** [comment]
NOT A VALID PHONE NUMBER WHEN UPLOADING FOR SMS

![image](https://user-images.githubusercontent.com/46505127/86628934-9f7e2500-bf98-11ea-9e28-c2aa455ac0d6.png)

**Comment by willeybryan** [comment]
SMS DOES THE SAME AS THE FIRST ONE 
![image](https://user-images.githubusercontent.com/46505127/86629025-c3da0180-bf98-11ea-9144-b4135ede4f2d.png)

**Comment by anikbrazeau** [comment]
For the line "Message about email address does not exist. Some one needs to figure out the words here."," "

Is it email address at the point of sending from CSV, or email address at the point of login?

Perhaps something general and simple like this could work?
"Email address does not exist."
"L'adresse électronique n'existe pas".

**Comment by anikbrazeau** [comment]
Old FR: "En mode d'essai you can only send to yourself and members of your team"
New FR: "En mode d'essai, vous ne pouvez envoyer qu'à vous-mêne et aux membres de votre équipe
(here, we could also remove the link to trial mode page, as we're planning to remove this page in #981) 

Old FR: "Vous avez besoin de fix 1 email address"
New FR: "Vous avez besoin de réviser 1 adresse courriel"
(here if it's 1 it should be singular for email address, if it's more than 1 it should be plural for email addresses)

Old FR: "Vous avez besoin de fix 2 phone numbers"
New FR: "Vous avez besoin de réviser 2 numéros de téléphones"

Old FR: "Re-upload your file"
New FR: "Téléverser de nouveau votre fichier"

Old FR: "Not a valid email address"
New FR: "Adresse courriel non valide"

Old FR: "Not a valid international number"
New EN: "Not a valid phone number"
New FR: "Numéro de téléphone non valide"

Old FR: "The columns in your file need to match the double brackets in your template"
New FR: "Les colonnes de votre fichier doivent correspondre aux parenthèses doubles de votre gabarit"

There's also an issue with "Ne montre que la première 1 rangées avec des erreurs"
--- here "rangée" should be singular if just 1. and plural "rangées" when more than 1.

**Comment by brdunfield** [comment]
Also have found:
"Must be a valid phone number"
"Not enough digits" (in a phone number)
"Not a valid country prefix"

cc @anikbrazeau

**Comment by brdunfield** [comment]
also
"enter missing data in 1 row", and "x rows"

**Comment by anikbrazeau** [comment]
EN: "Must be a valid phone number"
FR: "Doit être un numéro de téléphone valide"

EN: "Not enough digits"
FR: "Pas assez de chiffres"

EN: "Not a valid country prefix"
FR: "Entrer un préfixe de pays valide"

EN: "enter missing data in 1 row"
FR: "entrer les données manquantes dans 1 rangée"
(if X = 1)

EN: "enter missing data in X rows"
FR: "entrer les données manquantes dans X rangées"
(if X = 0 or if X > 1)

**Comment by brdunfield** [comment]
I am going to split out some of these into a separate card - some of them are located in the notification-utils repo, and I am not sure how to best translate them.
