### ISSUE TITLE
Make cards from ATO work

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#947]
**Story**
When advancing to Beta we need to make sure that we can have the confidence of the Security Boss so that they can sign the ATO.

**What?**
- Review to do list on this doc https://docs.google.com/document/d/1UYqSxPDxRBSuyEv37w_79RLEll1zaL7VS26_fGESoFw/edit?ts=5ed95d3c#heading=h.63mwsy7anz17
- Decide if skills are in team for each item
- Create ticket for each item for either team fix or SRE help. 

**Why?**
- Alpha ATO expires August. Beta ATO needed. 

**Done When**
- We have cards ready for next sprint 
- We actions out to the other skills needed and identified and raised with SRE.

**Comment by sastels** [comment]
https://github.com/cds-snc/notification-api/issues/961

**Comment by mcman12** [comment]
Continue reviewing evidence collections.
book meeting to review policies
