### ISSUE TITLE
Send Survey to GC Notify Users

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#948]
**Story**
When learning what people thing of Notify quantitatively we need to sample a large group so that we can get enough valid results to form a statistically significant sample size. 

**What?**
- Send Survey to Audience of GC Notify users having sent messages or logged in more than once. 

**Why?**
- So that we may have a baseline Notify sentiment to measure future adjustments too. 

**Done When**
- Survey is sent out.

**Comment by ClementineHahn** [comment]
Survey sent Thursday 11th of June to 80 users of Notify
