### ISSUE TITLE
Finalize interview guide for Public Research

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#949]
**Done When**
- We have a peer reviewed interview guide.

**Comment by ClementineHahn** [comment]
Thanks to the feedback of recrutement with participants, questions will need to be reworked

**Comment by AnneMarieMulumba** [comment]
Interview guide, questions: https://docs.google.com/document/d/1a_36p53iptKfkVW3tmCRYFR3xnG74sVbCb6g1Sa5uA4/edit?usp=sharing
