### ISSUE TITLE
Finalising Public Recruitment

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#950]
**Done When**
- We have recruited at least 20 people for potential usability testing with 5-7

**Comment by ClementineHahn** [comment]
@AnneMarieMulumba currently contacting organisations to recruit (Code for Canada, Litteracy Quebec ...)

**Comment by AnneMarieMulumba** [comment]
Follow the recruitment process on airtable: https://airtable.com/invite/l?inviteId=invZlskBxGWwVg86W&inviteToken=96fcfad644902d7d28199dd2342a8f316881b239934705705592321dd23c7728

**Comment by ClementineHahn** [comment]
2 people recruited so far. 
Minimum still 3 participants to go. 
Outreach sent out tweets and help to recruit more.

**Comment by ClementineHahn** [comment]
4 new people interested, sill to confirm, 
@AnneMarieMulumba connected with Sean on privacy statement, soon to be ready to send to ATIP for 👍

**Comment by ClementineHahn** [comment]
- in contact with 16 potential participants 

- among them 5 francophone : which complete the objective of yesterday ! 

- virtual compensation still in discussion with Policy, figure out how much of a blocker it is (not)

**Comment by ClementineHahn** [comment]
- Aujourd'hui commencer a envoyer les documents de consentement aux participants (MVP)

**Comment by ClementineHahn** [comment]
Apres envoie, on est a 4 participants qui ont consenti et ont donne leur dispo.

**Comment by ClementineHahn** [comment]
Session to help note-takers to be done today, 
Not enough french participants to start to schedule them yet but should be comoing in the next couple days. 
Today compensation meeting with policy to make it possible starting next couple week (YES)

**Comment by ClementineHahn** [comment]
It is done as we have all the people we needed to. Still in doing is refinement of the meetings to run the interviews with people that are recruited.
