### ISSUE TITLE
FR Bug: Security code error message

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#953]
<img width="436" alt="Screen Shot 2020-06-10 at 1 51 39 PM" src="https://user-images.githubusercontent.com/38330843/84303451-fec95080-ab24-11ea-9453-e42a1887518f.png">

Code not found = **Code non trouvé**

How might we reveal more of these error messages that remain without translation rather than stumble across them?

**Comment by brdunfield** [comment]
Here are the ones I've found so far:

"Code not found"
"Code has expired"
"Code already sent"
"Code already sent, wait 10 seconds" (not sure why there are two, will need to dig more)
"Too many verify codes created for user {}"

Will fix as part of https://github.com/cds-snc/notification-api/issues/932

**Comment by brdunfield** [comment]
"Code already sent, wait 10 seconds" is its own page that you're directed to if you click the send a new code button too quickly.

"Code already sent" seems to be if you enter a code too quickly after a new one is sent to you? I'm having trouble with this one.
It seems to appear if you resend a code too quickly to get to the above "wait 10 seconds" page, then navigate back in your browser and then enter a code very quickly in the box.

**Comment by anikbrazeau** [comment]
EN: "Code not found"
FR: "Code non trouvé"

EN: "Code has expired"
FR: "Le code a expiré"

EN: "Code already sent"
FR: "Le code a déjà été envoyé"

NEW EN: "Code already sent, wait 10 seconds"
FR: "Le code a déjà été envoyé, veuillez attendre 10 secondes"

EN: "Too many verify codes created for user {}"
FR: "Trop de codes de vérification créés pour l'utilisateur {}"

**Comment by brdunfield** [comment]
Once I'm done 2fa I will go through and do a pass for other api errors that may not be translated and add them to this issue.

**Comment by brdunfield** [comment]
These strings are outstanding and were not implemented as part of the 2fa PR:
NEW EN: "Code already sent, wait 10 seconds"
FR: "Le code a déjà été envoyé, veuillez attendre 10 secondes"

EN: "Too many verify codes created for user {}"
FR: "Trop de codes de vérification créés pour l'utilisateur {}"

I have found the following `InvalidRequest` error strings in the api that are not translated in admin.
- "You must have at least one reply to email address as the default"
- "User can’t be removed from a service - check all services have another team member with manage_settings"
- "Organisation not found"
- "Cannot send to international mobile numbers"
 
Note for above: There are MANY more error strings in the API. However, I believe those strings are being used for direct API calls, and are not visible in the admin interface, and therefore do not require translating.

Other bugs I found:
- "you can only send to yourself and members of your team". This translation is already in the csv, but isn't being displayed in the UI

**Comment by anikbrazeau** [comment]
**EN** "You must have at least one reply to email address as the default"
**FR** "Vous devez avoir au moins une adresse courriel de réponse par défaut""

**NEW EN**"User cannot be removed from service. Check that all services have another team member who can manage settings"
**FR** "L'utilisateur ne peut pas être enlevé du service. Vérifiez que tous les services ont un autre membre de l'équipe qui peut gérer les paramètres"

**EN**"Organisation not found"
**FR** "Organisation non trouvée"

**EN**"Cannot send to international mobile numbers"
**FR** "On ne peut pas envoyer à des numéros de téléphone internationaux""

---

**EN** "you can only send to yourself and members of your team"
**FR** "vous ne pouvez envoyer qu'à vous-même et aux membres de votre équipe"

**Comment by brdunfield** [comment]
From Anik:
“Your service already uses {} as an email reply-to address”
“Votre service utilise déjà {} comme adresse courriel de réponse”

NEW EN “You cannot delete a default reply-to email address”
“Vous ne pouvez pas supprimer l'adresse courriel de réponse réglée par défaut”
