### ISSUE TITLE
Default brandings are difficult to distinguish in french

### ISSUE THREAD

**Issue by brdunfield** [cds-snc/notification-api#956]
<img width="737" alt="Screen Shot 2020-06-11 at 1 56 07 PM" src="https://user-images.githubusercontent.com/5032149/84433554-b2951380-abeb-11ea-85a5-531e9022ec23.png">
It is impossible to tell which language branding is being used here.

Options:
- Rename the brandings so the language is at the start
- (probably better) Use text wrapping to display the entire name of the branding

Done When:
- Text wrapping

**Comment by anikbrazeau** [comment]
Exploring options in Figma here: https://www.figma.com/file/fRVRKm7cM8MUuBWUJbrfgU/Senders-content-creators-service-operators?node-id=1672%3A5306
