### ISSUE TITLE
Sent Notification page missing french strings

### ISSUE THREAD

**Issue by brdunfield** [cds-snc/notification-api#959]
From the dashboard, click on an individual notification that was sent.
On that page, there are some missing french strings above the email preview

<img width="776" alt="Screen Shot 2020-06-12 at 8 36 19 AM" src="https://user-images.githubusercontent.com/5032149/84514324-1240fc80-ac88-11ea-9665-62249d70fe92.png">

**Comment by anikbrazeau** [comment]
['Test'] a été envoyé **à une adresse courriel de** [TESTcsv5.csv] le 12 juin 8 h 32
