### ISSUE TITLE
API keys not handled with care (AWS, Twilio, etc)

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#971]
**Story**
When working with API keys for vendors and 3rd party systems we need to make sure the API keys are handled appropriately so some one can't send as us. 

**What?**
- Put all out API keys in a last pass folder for Notify that only the Notify developers and SRE team would have access too

**Why?**
- Outstanding Security Control from Notify Alpha ATO needs to be resolved before we can move to Beta.

**Comment by sastels** [comment]
I've created two new shared LastPass folders, Notify staging and Notify prod, and divided up the files from the old shared Notify folder appropriately.

**Comment by brdunfield** [comment]
I will do a pass of the code to ensure there aren't any stray keys left behind

**Comment by brdunfield** [comment]
It looks like there are no stray API keys that I can find in either API or Admin!

**Comment by ClementineHahn** [comment]
Work finished by @brdunfield waiting for @willeybryan to review and close it once considered done

**Comment by ClementineHahn** [comment]
@willeybryan to review and close when ok
