### ISSUE TITLE
Hasura Logging

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#972]
**Story**
When using Hasura to interact with the database via query or sproc logging must be enabled to we can forensically figure out what a developer has done in case of incident. 

**What?**
- Set up some kind of logging on our Hasura instance
STRETCH GOAL:
- Collect a random selection of use cases where one might need to manually interact with the database so we can in the future track them and evaluate building outside the database systems to support these actions based on their complexity and frequency.

**Why?**
- Satisfy outstanding security control

**NOTES**
- see https://hasura.io/docs/1.0/graphql/manual/deployment/logging.html
- First use case for the list
Pulling reports about trial accounts.

**Comment by sastels** [comment]
Can access the existing logs via
```
 kubectl logs -f -n notification-canada-ca hasura-54b48fcc6b-m97ll
```

**Comment by sastels** [comment]
If we add the env var `HASURA_GRAPHQL_ENABLED_LOG_TYPES` to
https://github.com/cds-snc/notification-tf/blob/master/manifests/base/hasura-deployment.yaml#L31-L39
then we could log the entire queries as described in
https://hasura.io/docs/1.0/graphql/manual/deployment/logging.html#different-log-types
