### ISSUE TITLE
Font changes in header on unauthenticated pages from Lato to Arial (except for homepage)

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#975]
Bug: typeface changes

Should consistently be Lato for banner and global navigation items.

<img width="695" alt="Screen Shot 2020-06-19 at 9 41 20 AM" src="https://user-images.githubusercontent.com/38330843/85138630-184b5600-b211-11ea-8e21-267e7a702f93.png">

<img width="699" alt="Screen Shot 2020-06-19 at 9 41 12 AM" src="https://user-images.githubusercontent.com/38330843/85138632-18e3ec80-b211-11ea-885e-af58d46d7544.png">

**Comment by ioanacontu** [comment]
As we will at some point move ahead with changing Lato to Noto Sans everywhere as we discussed earlier, and this is not a noticeable issue (unless you have designer eyes 👀). we could probably leave this in the backlog for now (to not forget that it exists).
