### ISSUE TITLE
Allow users to change between English and French default brandings

### ISSUE THREAD

**Issue by brdunfield** [cds-snc/notification-api#977]
Currently a platform admin has to update the branding for a service. This is because before, we had only a single default branding, and we needed to validate a change to a custom brand.

In addition to this, we should allow users to be able to change between the English and French default brandings without requiring CDS support.

I'm thinking maybe radio buttons above the existing custom branding upload page? This probably needs Design input before it's ready for Dev.

<img width="1074" alt="Screen Shot 2020-06-19 at 8 51 13 AM" src="https://user-images.githubusercontent.com/5032149/85145616-0f0abb00-b20a-11ea-9712-358498a781da.png">

**Comment by anikbrazeau** [comment]
Linked to https://github.com/cds-snc/notification-api/issues/956

**Comment by anikbrazeau** [comment]
Exploring options in Figma here: https://www.figma.com/file/fRVRKm7cM8MUuBWUJbrfgU/Senders-content-creators-service-operators?node-id=1672%3A5306

**Comment by sastels** [comment]
Should this be under "to do" but marked ready to implement?

**Comment by anikbrazeau** [comment]
Yeah, we could do that :D
