### ISSUE TITLE
Allow users to set the default branding for a service when it is created

### ISSUE THREAD

**Issue by brdunfield** [cds-snc/notification-api#978]
In concert with: #977 

Note: Eventually this will move to a setting when creating a template (See #744 ), but for now this is still at the service level.

When creating a service, the default branding defaults to English and there is currently no way for a user to change this without contacting CDS. They may not even be aware that a French-first branding exists. This should probably be a setting while creating the service.

This probably needs Design input before it is ready for Dev.

**Comment by anikbrazeau** [comment]
Exploring options in Figma here: https://www.figma.com/file/fRVRKm7cM8MUuBWUJbrfgU/Senders-content-creators-service-operators?node-id=1672%3A5306

**Comment by sastels** [comment]
Should this be under "to do" but marked ready to implement?
