### ISSUE TITLE
Remove Trial mode page and routes

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#981]
Kill this page and all routes to it : 
https://notification.alpha.canada.ca/features/trial-mode

Information in second half is irrelevant and it doesn't fit.

**Comment by sastels** [comment]
Also delete any content from the csv's that is only used on this page.

**Comment by sastels** [comment]
So where we link to the page, ie
```
In <trial mode> you can only send to yourself and members of your team
```
do we just want to leave the sentence without the link?

**Comment by anikbrazeau** [comment]
Yes that's perfect, just removing the hyperlink in EN/FR works!

**Comment by mcman12** [comment]
PR ready for review, will be looked at today!

**Comment by mcman12** [comment]
PR approved, waiting on Steve's comeback!
