### ISSUE TITLE
Search the CSV translation files for negative messages

### ISSUE THREAD

**Issue by brdunfield** [cds-snc/notification-api#982]
List from Anik: `can’t / cannot / won’t / will not / shouldn’t / should not / haven’t / have not / try again / retry / couldn’t / could not / might not`

To complete this issue I am going to write a simple script that will filter out and copy searched for phrases into a separate file, as this is and likely will remain a relatively frequent ask as we iterate our content!

**Comment by anikbrazeau** [comment]
Made a new issue for actually rewriting some of these messages, rather than piggy-backing off this one 😃
