### ISSUE TITLE
Allow French values when setting conditional personalisations

### ISSUE THREAD

**Issue by brdunfield** [cds-snc/notification-api#983]
Currently, when manually sending notifications, conditional personalisation variables can only be set to display with the following values:

"yes", "y", "true", "t", "1", "include", "show" (found in notification-utils)

We should include some french values as well. CC: @anikbrazeau

**Comment by anikbrazeau** [comment]
For Yes, we could add: "oui", "vrai", "inclure", "afficher" ?

For No, we could add: "non", "faux", "enlever", "cacher" ?

**Comment by brdunfield** [comment]
We don't actually need to add any no values. Just anything that isn't in the "yes" list will be treated as a "no". :)

**Comment by anikbrazeau** [comment]
Perfect! 👍
