### ISSUE TITLE
Check and fix missing and extra translations

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-api#984]
- [x] write a script to check if we are missing any strings in `en.csv` or `fr.csv` or if we have extra strings we don't use anymore
- [ ] fix anything the script flags

**Comment by anikbrazeau** [comment]
@sastels do you need anything from me on this?

**Comment by sastels** [comment]
> @sastels do you need anything from me on this?

woot! just came here now to ask for translations for:
* There’s something wrong with the link you’ve used.
* That verification link has expired.

**Comment by anikbrazeau** [comment]
**EN** There’s something wrong with the link you’ve used.
**FR** Il y a un problème avec le lien que vous avez utilisé.

**EN** That verification link has expired.
**FR** Ce lien de vérification a expiré.

_---> question: is this now a code rather than a link with new 2FA?_

**Comment by sastels** [comment]
> _---> question: is this now a code rather than a link with new 2FA?_

We're still using a link in the registration.

**Comment by mcman12** [comment]
Merge conflicts to fix.
