### ISSUE TITLE
Fix Default SMS help message

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#985]
**Steps to reproduce**
1) Send your self a Notify SMS
2) Reply to it

**Expected**
This inbox does not accept replies | Cette boite de SMS n'aime pas les messages

**Actual**
'Default Help Message'

![image](https://user-images.githubusercontent.com/46505127/85450934-545f1d80-b567-11ea-86fa-da6411a8c81a.png)

**Comment by anikbrazeau** [comment]
@willeybryan how about this, is this accurate?

**EN** Message failed to send. This inbox is not set up to receive messages.
**FR**  L'envoi du message a échoué. Cette boîte de réception n'est pas configurée pour recevoir des messages.

**Comment by willeybryan** [comment]
Yes that works great! Even with double byte encoding the french message is just under 140 characters so that works amazingly. 

I hope there is an AIDE setting. 

@anikbrazeau if there is one help setting can we do a back up one message?
"This inbox is not set up to receive messages. / Cette boîte de réception n'est pas configurée pour recevoir des messages."

Then we can have a developer implement it.

**Comment by brdunfield** [comment]
It looks like we can register whatever keywords we want with Pinpoint. So we can register AIDE.

However, that said, the default help message seems to send when you reply with anything other than a registered keyword, so we should probably use the shortened bilingual one.

**Comment by willeybryan** [comment]
Does "This inbox is not set up to receive messages. / Cette boîte de réception n'est pas configurée pour recevoir des messages."
work for you @anikbrazeau ?

**Comment by anikbrazeau** [comment]
Yes that works perfectly! 
@willeybryan @brdunfield

**Comment by willeybryan** [comment]
Sweet. If only we could jam GC Notify branding in there. 

Push it up as soon as you can we can polish it later. A bilingual message incidentally is Canada branded.

**Comment by brdunfield** [comment]
![Screenshot_20200709-102104_Messages](https://user-images.githubusercontent.com/5032149/87065514-5b746580-c1ce-11ea-8cfb-4ebdaf9fb84b.jpg)

Seems to be working!
