### ISSUE TITLE
Investigate Notify User Time out

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#988]
**Task**
For security control AC-12 I need to know what our timeouts are for:
- API session time out
- Closed my browser session time out
- How long can I just sit with my Browser open to Notify before I log out?

**Personal experience**
I am logged in all the time. I sleep my computer by closing the lid at night. I only have to log in every Monday.

**Comment by brdunfield** [comment]
On the Admin Side: Sessions are stored in a Cookie that is valid for 20 hours.

<img width="563" alt="Screen Shot 2020-06-30 at 11 16 34 AM" src="https://user-images.githubusercontent.com/5032149/86156519-4eb38b80-bac3-11ea-9b5d-9a0889d58e8b.png">
The above config variable sets a flask value: https://flask.palletsprojects.com/en/1.1.x/api/#flask.Flask.permanent_session_lifetime

Which determine's the cookie's lifetime.

There is also "cookies.html" with this info correctly written, however it looks like this route is inaccessible, and shows the "Page cannot be found" page instead.

I will investigate the API next.

**Comment by brdunfield** [comment]
It looks like the API doesn't handle any of this, just the admin. The API will refuse unauthenticated connections to admin routes though, so that's probably why.

**Comment by willeybryan** [comment]
Great, I tested. Once the user logs out if they try to click anything it makes a request which then redirects them to a log in page.
