### ISSUE TITLE
Analyze interview findings (5) with the public

### ISSUE THREAD

**Issue by AnneMarieMulumba** [cds-snc/notification-api#989]
**Done When**
- Analysis prepared and prepared for sharing
- Share with design and PMs
- Ready for communicating

Analysis board:
https://app.mural.co/t/cppd0120/m/cppd0120/1593451090599/e6262eba81a99814171ba295bfee02bb12398b51

**Comment by ClementineHahn** [comment]
Anne-Marie Still working on this today. By Friday should be done 🤞

**Comment by ClementineHahn** [comment]
At the point of synthesis today  progressing fast ! 💪

**Comment by AnneMarieMulumba** [comment]
Synthesis is on! https://docs.google.com/document/d/1lro504OzM0SpTzhZz6mFQvHwfQ77iDnphnFp1t0Yco4/edit?usp=sharing

**Comment by mcman12** [comment]
WIP, synthesis, going through findings, working on the journey map, a11y. Looking good for end of sprint.

**Comment by mcman12** [comment]
Started presentation, should be ready for Friday.
