### ISSUE TITLE
Update Notify Privacy Page with New Legal Content

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#991]
**Story**
When evaluating Notify government decision makers need to see a long legal looking privacy policy to imbue them with the confidence that take their data security and privacy seriously.  

**Done When**
This Privacy page https://notification.alpha.canada.ca/privacy

Has this content on it: https://docs.google.com/document/d/186Bp_Blv9PBcWhUhw9FBy5SBEHFiRlONTIi0cksvogA/edit

and this better privacy page
https://notification.alpha.canada.ca/privacy?lang=fr

Has this amazing content on it
https://numerique.canada.ca/transparence/confidentialite/
with similar edits made to the english content.

**Comment by anikbrazeau** [comment]
Latest EN version here: https://docs.google.com/document/d/186Bp_Blv9PBcWhUhw9FBy5SBEHFiRlONTIi0cksvogA/edit#
Latest FR version here: https://docs.google.com/document/d/1ZW9nEdHWizTH-Th4xddc1-J3EFhYBi0lOjhdslO1D-I/edit#

**Comment by anikbrazeau** [comment]
New bilingual privacy content for https://notification.alpha.canada.ca/privacy is ready for dev 👍 

https://docs.google.com/document/d/186Bp_Blv9PBcWhUhw9FBy5SBEHFiRlONTIi0cksvogA/edit#heading=h.wzb9zfqp9k4v
