### ISSUE TITLE
Create plan for marketing and storytelling tasks / activities / strategy

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#992]
Narrative plan
https://docs.google.com/document/d/1E7bPyCMLbKBGQ_7iSIGhkhyhM5HvxHVbizquq5wND7A/edit

Links to relevant marketing docs
https://docs.google.com/document/d/1kiboCC8GjGKgUh2YTR4tu1Vot8Z0jYua3a_kxqgOfy8/edit

**Comment by mcman12** [comment]
Prep for next sprint, will create new cards for next sprint
