### ISSUE TITLE
Create more helpful/positive error messages

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#993]
See list Bethany generated:
https://docs.google.com/spreadsheets/d/1fFDQnHS9BmDzYgsMw4lKbm-rm5cO2bOXqgusNrOFKBM/edit#gid=918675824 

Review messages to see how they might be rewritten to be more positive and useful

Link to https://github.com/cds-snc/notification-api/issues/982

Related to https://github.com/cds-snc/notification-api/issues/963

**Comment by mcman12** [comment]
Anik starting to look at them and will probably need dev help to prioritize the work
