### ISSUE TITLE
Proof that we encrypt data at rest.

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#994]
To satisfy the security control:

"CSE ITSA-11 Approved Cryptographic Algorithms for the Protection of Protected Information [Reference 8]. 
CSE ITSB-40A Government of Canada Policy for the Protection of Classified Information Using Suite B Algorithms [Reference 28]."

We need proof that the data is encrypted at rest and what algo is doing so.

**Comment by sastels** [comment]
Looks like it's built into AWS RDS and we have it turned on:
![image](https://user-images.githubusercontent.com/8228248/86810000-7b7b1c00-c04a-11ea-942f-873fd80f0851.png)

Also, the algorithm is AES-256 according to
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.Encryption.html

> You can encrypt your Amazon RDS DB instances and snapshots at rest by enabling the encryption option for your Amazon RDS DB instances. Data that is encrypted at rest includes the underlying storage for DB instances, its automated backups, read replicas, and snapshots.
>
> Amazon RDS encrypted DB instances use the industry standard AES-256 encryption algorithm to encrypt your data on the server that hosts your Amazon RDS DB instances. After your data is encrypted, Amazon RDS handles authentication of access and decryption of your data transparently with a minimal impact on performance. You don't need to modify your database client applications to use encryption.

**Comment by ClementineHahn** [comment]
@sastels worked on it, waiting for @willeybryan to review and close it when considered done

**Comment by ClementineHahn** [comment]
@willeybryan to review and close when ok

**Comment by willeybryan** [comment]
and in transit 
![image](https://user-images.githubusercontent.com/46505127/87091979-9d220200-c208-11ea-943a-2840a4da61f8.png)
