### ISSUE TITLE
Proof we have documented our AWS configuration settings and Notify configuration settings

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#995]
Security control CM-6

**Done When**
- Screen shot(s) AWS configuration to redeploy Notify.
OR
- Doc on how to redeploy Notify if it exists.

**Comment by sastels** [comment]
The Notify internal configuration (ie environment variables) are documented in LastPass, and the kubernetes configuration is documented in the terraform repo
https://github.com/cds-snc/notification-tf
