### ISSUE TITLE
Update terms of use

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#996]
**Story**
We need to ensure that our terms of use are clearly labeled and out there so that lawyers won't email us.

**Done When**
The content from
https://notification.alpha.canada.ca/features/terms
In replaced with
https://docs.google.com/document/d/1wLTU2vYDbkrHz9uyA47R433HpBLoMX-X4eyHwIVhcrA/edit

And then it is done again in French for https://notification.alpha.canada.ca/features/terms?lang=fr

**Comment by anikbrazeau** [comment]
Reviewing with Sean.
Finalizing to send to translation.

Latest EN: https://docs.google.com/document/d/1wLTU2vYDbkrHz9uyA47R433HpBLoMX-X4eyHwIVhcrA/edit#

**Comment by anikbrazeau** [comment]
Finalized [Terms of use](https://docs.google.com/document/d/1wLTU2vYDbkrHz9uyA47R433HpBLoMX-X4eyHwIVhcrA/edit#) in translation.

Expect back from translation Friday July 10, 2020.

**Comment by anikbrazeau** [comment]
Considering merging with this new doc https://docs.google.com/document/d/1GYWPqCe6cL72yKPSTrnhV0_3ZXFjXlMX6NpO1y3NIvI/edit?ts=5e5fcd31#heading=h.fx03axyrinl

**Comment by anikbrazeau** [comment]
Ready for dev :)

**Comment by ClementineHahn** [comment]
About to be done, PR today :)

**Comment by brdunfield** [comment]
I will need to get a csv list of users exported from the DB to send Bryan as part of this issue.

**Comment by brdunfield** [comment]
Email list sent to Bryan
