### ISSUE TITLE
Product lifecycle map: Identify opportunities in current service experience where there are gaps/barriers (match up mental models)

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#997]
Figure out: 
- who are the current actors/services
- what do we know from clients/users
- identify gaps and barriers to awareness, understanding, persuasion, adoption and use
- interview chats with key stakeholders
- improve experience at touchpoints in the product lifecycle

Mapped what we know from clients vs. what we assume we offer at each stage in the adoption process in the [Product lifecycle map] which shows whether mental models clients' have align with what we offer at each stage (https://app.mural.co/t/cppd0120/m/cppd0120/1593542890988/aaaa6f4b991175d41f835e60940f53809c405e0a).

--

[Marketing plan](https://docs.google.com/document/d/1E7bPyCMLbKBGQ_7iSIGhkhyhM5HvxHVbizquq5wND7A/edit#heading=h.knjlmeuwwf4q)

**Comment by anikbrazeau** [comment]
Done when 

[Product life cycle map](https://app.mural.co/t/cppd0120/m/cppd0120/1593542890988/aaaa6f4b991175d41f835e60940f53809c405e0a) is filled in

[SWOT analysis](https://app.mural.co/t/cppd0120/m/cppd0120/1593542474785/a49276abc84edf8a6982a9cf8b202a467305df82) is complete

Use these to feed into Business Model Canvas

**Comment by ClementineHahn** [comment]
Anik with Ioana is working on it today.

**Comment by ClementineHahn** [comment]
Still in progress, could be demoed at show the done of the 10th of July to react on state of progress

**Comment by mcman12** [comment]
Presented to the team on Friday, WIP, stakeholder interviews this week.

**Comment by mcman12** [comment]
Chat with John O on marketing and how we can do better. 
Going through leads and opportunities.
