### ISSUE TITLE
Update the Business model canvas + value proposition

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/notification-api#999]
- Use the value proposition framework
- Focus on key partners
- Add key activities
- Outline customer relationships
- Influence on channels, social media, events, etc.
- Possible interviews with stakeholders
- Possibly do a workshop with the whole team?

[Business model canvas](https://app.mural.co/t/cppd0120/m/cppd0120/1593196576167/11a3ecfbb06258c128ccc5b64e88d3baeafadb54)

[Value proposition](https://drive.google.com/drive/folders/1vsMr_e9KZHUbUwZC6lCRKVR_ypr7rVE_)

[Marketing plan](https://docs.google.com/document/d/1E7bPyCMLbKBGQ_7iSIGhkhyhM5HvxHVbizquq5wND7A/edit#heading=h.knjlmeuwwf4q)

**Comment by ClementineHahn** [comment]
Should be progressed on today, done approximatively by end of week

**Comment by ClementineHahn** [comment]
no update. still on progress. To figure out when/if to play back to team

**Comment by mcman12** [comment]
WIP, still on track for sprint end

**Comment by anikbrazeau** [comment]
Ran workshop with team to define different customer segment profiles based on their role in adoption. To create a value proposition canvas we started with thinking about their jobs/pains/gains.

- [Decision Makers](https://funretro.io/board/5631fd9a-757c-43eb-9fc5-2010860cd91c/6c6ba999-5b39-4dfb-98ba-13c83dfa1c4a)
- [Influencers/Recommenders](https://funretro.io/board/5631fd9a-757c-43eb-9fc5-2010860cd91c/078e33df-66f7-46fd-9ede-10bf369ca613)
- [Saboteurs](https://funretro.io/board/5631fd9a-757c-43eb-9fc5-2010860cd91c/7a1689ff-ae31-4c51-ab6f-d87f58488877)

Then, we ideated about ways to relieve pains or create gains or make their jobs better.

- [Value by segment](https://jamboard.google.com/d/1SQ0kqqiEYouK4vfB_AFXaBj_CtdZIJAQTiduogrykuY/viewer?f=0)
